### ISSUE TITLE
Enable creating a KeyPass password from browser extension

### ISSUE THREAD

**Issue by Austin1** [keepassxreboot/keepassxc-browser#2083] opened 2024-01-16 14:55 UTC
I'd like to be able to generate a password while creating a username/password for a new website instead of having to open the desktop app and flip flop between multiple programs.

## Expected Behavior
Click the extension icon when creating a password or even show a "generate" icon overtop the password field on the website during generation.

## Current Behavior
No ability to generate a password, at least that I can easily find, using chrome browser with Microsoft Edge

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.11
Operating system: Mac/
Browser: Edge

**Comment by varjolintu** [comment] 2024-01-16 15:31
That has been already requested. Duplicate of: https://github.com/keepassxreboot/keepassxc-browser/issues/1234

**Closed by varjolintu** 2024-01-16 15:31 UTC
