### ISSUE TITLE
Firefox extension now linking to desktop version

### ISSUE THREAD

**Issue by beachbardave** [keepassxreboot/keepassxc-browser#1531] opened 2022-01-18 18:53 UTC
Despite many attempts I can not get the desktop and browser versions to communicate.

This was fine until the latest Librewolf update.

## Expected Behavior
 The Browser extension should link to desktop add (I have followed the instructions)

## Possible Solution

Possibly due to a change in Librewold?

## Steps to Reproduce (for bugs)

Open KeepassXC, load database and keyfile. 
Launch Librewolf, attempt login.

"

KeePassXC-Browser has encountered an error:

Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. "

Reloading does now solve the issue.

1.
2.
3.
4.

## Debug info

KeePassXC - unknown
KeePassXC-Browser - 1.7.11
Operating system: MacIntel
Browser: Mozilla Firefox 91.0

**Comment by varjolintu** [comment] 2022-01-18 19:41
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/559 and https://github.com/keepassxreboot/keepassxc-browser/issues/1353.

LibreWolf is not supported directly. Use the Custom Browser feature from the Advaced tab of Browser Integration settings in KeePassXC. You'll need the path for LibreWolf's NativeMessagingHosts folder.

**Closed by varjolintu** 2022-01-18 19:41 UTC
