### ISSUE TITLE
Error! No logins found.

### ISSUE THREAD

**Issue by Mega-Cookie** [keepassxreboot/keepassxc-browser#979] opened 2020-08-24 18:20 UTC
## Current Behavior
It worked fine until today when I updated to 2.6.1. Now for most sides I get this error. Some sites still work, but I can't figure out what makes those site special.

## Steps to Reproduce (for bugs)
1. Start KeePassXC
2. Start FireFox
3. Try to log in somewhere (Google, Github, Protonmail, a private nextcloud instance)
4. Always get the same Error

## Debug info
KeePassXC - 2.6.1
KeePassXC-Browser - 1.6.6
Operating system: Win 10
Browser: Firefox 79.0

**Comment by varjolintu** [comment] 2020-08-24 18:26
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/978.

Workaround for now is to disable Best-Matching credentials setting.

**Closed by varjolintu** 2020-08-24 18:26 UTC
