### ISSUE TITLE
Browser integration does not search in all open databases

### ISSUE THREAD

**Issue by mattuschek** [keepassxreboot/keepassxc-browser#2179] opened 2024-04-25 07:50 UTC
## Current Behavior
I have always opened 4 KeePass databases.
The browser integration does not work unless the correct database tab is selected.
The KeePass icon in the "username" field remains grey, when the wrong database tab is selected.

## Possible Solution
The correct database tab must be selected.

## Steps to Reproduce (for bugs)
Select wrong database tab.

## Debug info
KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.0.3
Operating system: Windows 10 64-Bit
Browser: Chrome/Firefox
Browser: other not tested

![KeePassXC_GUI_mehrere_DBs_offen](https://github.com/keepassxreboot/keepassxc-browser/assets/96886632/46da8aec-2047-4195-acf4-4f9d1a459b3b)

![KeePassXC_andere_DB_01](https://github.com/keepassxreboot/keepassxc-browser/assets/96886632/f9018cc4-6e20-41f2-a96e-5bbc5985250f)

![KeePassXC_andere_DB_02](https://github.com/keepassxreboot/keepassxc-browser/assets/96886632/0af03435-945e-45a2-8517-af9f9c26494c)

![KeePassXC_richtige_DB](https://github.com/keepassxreboot/keepassxc-browser/assets/96886632/43c558e1-b47e-46f0-912a-2dfdf2533201)

![KeePassXC_Browser-Integration_alle_DBs_suchen](https://github.com/keepassxreboot/keepassxc-browser/assets/96886632/e6579997-0ff5-43a0-b7b6-ec7a44220fbb)

**Comment by varjolintu** [comment] 2024-04-25 09:27
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/7269

**Closed by varjolintu** 2024-04-25 09:27 UTC
