### ISSUE TITLE
Database connection not possible on terminalserver environment

### ISSUE THREAD

**Issue by lbayerlein** [keepassxreboot/keepassxc-browser#1014] opened 2020-09-15 15:27 UTC
## Expected Behavior

Open the browser (firefox, chrome) after starting KeePassXC as the first user logged in. KeePassXC is configured as documented in the wiki (browser integration activated, checked all dependent browsers). Establishe database connection via Firefox.

After successfully connected to the database for user1, this should work for userX, too.

## Current Behavior

If I click on the Firefox KeePassXC browser plugin icon, it asks, if KeePassXC is running. By clicking on "reload", it tells me "key exchange not possible".

On configuration settings page, I can not connect to the database. Nothing happened by clicking on "connect" on "connected database".

Maybe there is a conflict by running multiple proxy instances? I checked the users AppData\Local\KeePassXC folder and the registry entries. Everything seems fine. I do not know, if there is an issue with the new version. We used this for a long time with no issues.

## Possible Solution

Unfortunately, I do not have a possible solution. On a daily reboot, it works at the morning. If I log out my current user and log in agagin, it does not work anymore.

## Steps to Reproduce (for bugs)

1. Login as first user, install KeePassXC, enable Browser integration, open database in KeePassXC
2. Open Firefox, install KeePassXC browser plugin, establish connection to existing database
3. Login as second/third/x user on the terminal server, open firefox and install browser plugin
4. Try to connect to database - it does not work

## Debug info

KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.1
Operating system: Win
Browser: Firefox 80.0

Thanks for reading and for your time. If you need further information, please tell me.

**Comment by varjolintu** [comment] 2020-09-15 17:52
Probably a duplicate of https://github.com/keepassxreboot/keepassxc/issues/5393.

**Comment by droidmonkey** [comment] 2020-09-15 19:08
It is

**Closed by droidmonkey** 2020-09-15 19:08 UTC
Labels: bug

**Comment by lbayerlein** [comment] 2020-09-16 06:44
Yes, sorry I didn't notice. Thanks very much.
