### ISSUE TITLE
Save site specific sides in database itself

### ISSUE THREAD

**Issue by felixschndr** [keepassxreboot/keepassxc-browser#2250] opened 2024-06-19 10:25 UTC
I have a Keepass Database which is synced across multiple computers. All computers have the browser extension installed.
When I come across one site where I need to manually specify the username/password/TOTP field this information is only saved in the browser and not in the database. Thus when I enter into the same site on a different computer I have to manually specify the fields again on this computer.

## Possible Solution
Change the save location of the manually specified fields from the browser to a field in the corresponding entry in the keepass database.

## Debug info

KeePassXC - 2.7.8
KeePassXC-Browser - 1.9.0.5
Operating system: Win
Browser: Chrome

**Comment by varjolintu** [comment] 2024-06-19 10:36
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/1664.

**Closed by varjolintu** 2024-06-19 10:36 UTC
