### ISSUE TITLE
Extension spawns unused keepassxc-proxy.exe processes

### ISSUE THREAD

**Issue by sheavner** [keepassxreboot/keepassxc-browser#226] opened 2018-07-07 07:27 UTC
## Expected Behavior
I expect there should be only one keepassxc-proxy.exe running per browser even if keepass is not running.

## Current Behavior
Pressing the reload button in the plugin window spawns multiple keepassxc-proxy.exe.   When I do launch keepass, the button changes and it retains its connection to the last spawned keepassxc-proxy.exe.

## Possible Solution
* Have keepassxc-proxy.exe shutdown if it loses connection to the plugin.   
* Maybe the plugin isn't closing its connections to the keepassxc-proxy.exe when it spawns a new instance.
* Maybe the plugin shouldn't launch more than one instance of keepassxc-proxy.exe

## Steps to Reproduce (for bugs)
1. Setup keypass browser integration to use a proxy application.
2. Stop all instances of chrome and keepass.
3. Launch chrome.   Do not start KPXC.
4. Open task manager.  Observe number of running keepassxc-proxy.exe processes
5. Click KP icon in chrome toolbar,    Click Reload button.
6. See number of keepassxc-proxy.exe processes has gone up by one.
7. Repeat step 5 & 6 ad nauseam

## Debug info
KeePassXC-Browser Version: 1.1.7
KeePassXC Version: 2.3.3
Operating system: Win10-64bit
Browser: Chrome
Proxy used: YES

##Chrome about: 
Google Chrome | 67.0.3396.99 (Official Build) (64-bit) (cohort: Stable)
Revision | a337fbf3c2ab8ebc6b64b0bfdce73a20e2e2252b-refs/branch-heads/3396@{#790}
OS | Windows
JavaScript | V8 6.7.288.46
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

**Comment by varjolintu** [comment] 2018-07-08 06:07
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/227.

**Closed by varjolintu** 2018-07-08 06:07 UTC
Labels: duplicate
