### ISSUE TITLE
Custom login fields doesn't work on multi-page login

### ISSUE THREAD

**Issue by johnvirg** [keepassxreboot/keepassxc-browser#1629] opened 2022-05-20 15:37 UTC
For Sonicwall firewall logins, the login name and password fields are properly detected automatically and filled in just fine. If the login also has a TOTP entry, the form to enter the code appears on second page loaded after the main login page. Keepassxc doesn't recognize the field so you have to copy/paste.

If you use the Choose Custom Login Fields from the Chrome extension to detect the field, if you skip the first two fields (login and password) and just assign the TOTP field, it no longer recognizes the fields on the main login page. If I manually select the fields on main login page and then assign just the TOTP field (skipping the login and password on the second page), it wipes out the selections from the first page.

It seems like you can't set the fields when they span multiple pages. Not all sites present the TOTP entry on the same page as login. Maybe this is something specific to a Sonicwall page or workflow? Thanks.

**Comment by varjolintu** [comment] 2022-05-28 08:58
This is probably already solved in 1.8.0. I can inform when the dev version is ready for testing.

**Comment by varjolintu** [comment] 2022-06-04 07:21
Duplicate of: https://github.com/keepassxreboot/keepassxc-browser/issues/1149

**Closed by varjolintu** 2022-06-04 07:21 UTC
