### ISSUE TITLE
Firefox 100 User Agent?

### ISSUE THREAD

**Issue by MPW1412** [keepassxreboot/keepassxc-browser#1626] opened 2022-05-16 08:47 UTC
Hello,

I can't use the pairing between Firefox's Keepass-Plugin and KeepassXC 2.7.1 anymore since I upgraded the former to version 100. 

As KeepassXC can be enabled for different browsers separately, I assume it matches the user agent. And KeepassXC wouldn't be the only software, that runs into the limit to two digit version number isuse. Might that be the case?

Best,
Matthias

**Comment by varjolintu** [comment] 2022-05-16 10:08
The user agent's browser version has nothing to do with the key pairing. I need more information about your system. Are you using Ubuntu Linux and Firefox has upgraded to Snap?

**Comment by MPW1412** [comment] 2022-05-16 11:35
Correct. Ubuntu 22.04 unfortunately moved Firefox by default into snap.

**Comment by varjolintu** [comment] 2022-05-16 11:39
Then this is a duplicate of: https://github.com/keepassxreboot/keepassxc-browser/issues/1426. Please follow the instructions on that thread to install a normal version of Firefox.

**Closed by varjolintu** 2022-05-16 11:39 UTC
Labels: duplicate, more info needed
