### ISSUE TITLE
Add URL to title option

### ISSUE THREAD

**Issue by sebast889** [keepassxreboot/keepassxc-browser#374] opened 2019-01-11 03:13 UTC
I'm currently using an addon to do this to help with auto-type finding the right credentials but adding it into keepassxc-browser would eliminate the need for me to trust another addon. It would be good to have this as an option in keepassxc-browser.

**Comment by varjolintu** [comment] 2019-01-11 05:49
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/274.

**Closed by varjolintu** 2019-01-11 05:49 UTC
Labels: duplicate
