### ISSUE TITLE
KeepassXC browser plugin breaks XML pretty-printing in Firefox

### ISSUE THREAD

**Issue by baszoetekouw** [keepassxreboot/keepassxc-browser#301] opened 2018-09-24 09:35 UTC
When the KeepassXC browser plugin in Firefox is enabled, some XML documents are no longer pretty-printed, but rather shown as a big mess of XML-interpreted-as-HTML.

Note, this only seems to occur for XML sent with "Transfer-Encoding: chunked" and no Content-Length header.

## Expected Behavior
Firefox pretty-prints XML like this:

![screenshot_20180924_113209_1470x1387](https://user-images.githubusercontent.com/1461740/45945389-a8814a80-bfed-11e8-937c-0df6687ee890.png)

## Current Behavior
Firefox shows a big XML mess like this:

![screenshot_20180924_113202_1470x1387](https://user-images.githubusercontent.com/1461740/45945393-ae772b80-bfed-11e8-823d-6d906b0ee30c.png)

## Possible Solution
No idea what is causing this.

## Steps to Reproduce (for bugs)
1. Disable keeypassxc browser extansion
2. Open https://zoetekouw.net/keepassxc-bug.php and observe pretty-printed XML 
3. Keep tab open and reenable keepassxc browser extension
4. Observe that pretty-printed XML in open tab has disappeared and has been replaced with something that looks like XML-interpreted-as-HTML.  
5. Close tab and open url https://zoetekouw.net/keepassxc-bug.php again.  Observe the same mess.

## Debug info
Nothing to see in the console 

KeePassXC - 2.3.4
KeePassXC-Browser - 1.2.0 
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment] 2018-09-24 09:39
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/50.

**Closed by varjolintu** 2018-09-24 09:39 UTC
Labels: duplicate
