### ISSUE TITLE
Database entry properties wrong allow value

### ISSUE THREAD

**Issue by Moooartin** [keepassxreboot/keepassxc-browser#684] opened 2019-11-14 09:51 UTC
KeepassXC-Browser on an input password show a list of all entries even if it's not the same URL at all. Database entries property key KeepassXC-Browser Settings have wrong Allow values.

## Expected Behavior
Only the entries with the same URL should be listed.

## Current Behavior
KeePassXC -Browser ask for Confirm access, and a list of all entries.
When I select the entry, and choose to remember this decision. Then inside input KeepassXC-Browser will show me a list of possible entries that I didn't select for this URL.

## Steps to Reproduce (for bugs)
1. Got to KeePassXC -> Select Database settings -> Browser Integration -> Click Forget all site-specific settings on entries
2. Go to the desired URL (example.com), KeePassXC -Browser ask for Confirm access with a list of all entries
3. Select the relevant entry, and select "Remember this decision" then click Allow
4. Back to KeepassXC database, and **all entries not only the one selected before**, have a property key : "KeepassXC-Browser Settings" with the value : {"Allow":["example.com"],"Deny":[],"Realm":""}
5. Go to your URL, and inside the input KeepassXC-Browser will show a list with all the entries inside the database.

## Debug info
KeePassXC - 2.5.1
KeePassXC-Browser - 1.5.3
Operating system: Linux x86_64 Ubuntu 18.04
Browser: Chrome/Chromium 78.0.3904.97 or Mozilla Firefox 70.0

**Comment by varjolintu** [comment] 2019-11-14 09:53
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/3848.

**Closed by varjolintu** 2019-11-14 09:53 UTC
