### ISSUE TITLE
Firefox browser plugin: discard button does not close the overlay

### ISSUE THREAD

**Issue by jelle-ingambh** [keepassxreboot/keepassxc-browser#1658] opened 2022-06-28 08:33 UTC
The plugin overlay does not close when clicking the discard button. I am using Firefox 101.0.1 with plugin version 1.8 (23-06-2022).
Closing the browser tab or browser does not help. It worked once but fails most times.
The installed KeyPassXC versions were 2.7.0 and now 2.7.1.

**Comment by varjolintu** [comment] 2022-06-28 09:29
What overlay are you talking about? This is a possible duplicate of #1656.

**Comment by jelle-ingambh** [comment] 2022-06-28 09:35
> What overlay are you talking about? This is a possible duplicate of #1656.

Yes, it's a duplicate. Thanks

**Closed** 2022-06-28 09:35 UTC
Labels: more info needed
