### ISSUE TITLE
"Fill TOTP" gives no option for multiple logins, unlike username/password

### ISSUE THREAD

**Issue by jahomax** [keepassxreboot/keepassxc-browser#460] opened 2019-04-02 10:11 UTC
I have multiple accounts on a single website. For username and password, I'm given a dropdown list to choose which account logins to use. However, on the next page, for TOTP, I right-click the form, navigate to "Fill TOTP"...

## Expected Behavior

I expect that either my selected login account is remembered from the previous page and the associated TOTP is filled; or I should see another dropdown menu to select an account which has TOTP settings.

## Current Behavior

I select "FIll TOTP" and with no further interaction a TOTP is filled in. This TOTP is the one associated with the alphabetically-first login associated with the website. There is no option within the browser to select other logins.

## Steps to Reproduce (for bugs)

1. Go on a website for which you have multiple accounts with TOTPs
2. Fill in details with alphabetically-first login, and use "Fill TOTP" to fill in TOTP - observe successful login
3. Log out and repeat with a different login, and use "Fill TOTP" to fill in TOTP - observe a failed TOTP.

## Debug info

KeePassXC - 2.4.0
KeePassXC-Browser - 1.3.3
Operating system: Linux
Browser: Firefox 66.0.1

**Comment by varjolintu** [comment] 2019-04-02 10:27
If no TOTP is filled or you want to select the credentials, there's a workaround to select the credentials via the popup icon and then try to fill it.

Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/337. So it will be possible in th future.

**Closed by varjolintu** 2019-04-02 10:27 UTC
Labels: duplicate
