### ISSUE TITLE
Fill user+pass option often does not work on username only pages

### ISSUE THREAD

**Issue by nbartos** [keepassxreboot/keepassxc-browser#217] opened 2018-06-27 15:52 UTC
## Expected Behavior
Right click and select "Fill User+Pass" option in a username field on a page where there is no password field often does not work.

Here are 2 sites I'm currently having problems with:
https://www.paypal.com/signin?country.x=US&locale.x=en_US
https://www.amazon.com/ (click "Hello Sign in" -> "Sign in")

## Current Behavior
Right click and select "Fill User+Pass" does not fill anything on the above sites.  On other sites, sometimes reloading the page helps (even after trying "redetect credential fields") , sometimes not.

## Possible Solution
Switching back to the chromeIPass plugin seems to work on all sites everywhere.  If possible, seeing how that extension does the field detection may provide a solution.

## Steps to Reproduce (for bugs)
1.  Go to one of the URLs above.
2.  Right click "Fill User+Pass" in the username field.
3.  If it works once, try reloading the page and trying again.

## Debug info

KeePassXC - 2.3.1
keepassxc-browser - 1.1.7
Operating system: Linux
Browser: Chrome
Proxy used: YES

**Comment by varjolintu** [comment] 2018-06-27 16:12
I cannot reproduce the issue. Both sites worked fine with Firefox and Chromium. The fill even activates the autocomplete for that input field.

The next version of the extension includes a Site preferences tab in the settings where you are able to define pages that have only username field visible and allow better input field detection. It might help for the issue.

Can you debug the extension (use Inspector on the web page) and see if there's any error messages when trying to fill the username?

**Comment by nbartos** [comment] 2018-06-27 16:43
I was getting this:
```
signin?country.x=US&locale.x=en_US:1 Uncaught (in promise) 
{message: "The message port closed before a response was received."}
Promise.then (async)		
Promise	@	keepassxc-browser.js:1453
cip.receiveCredentialsIfNecessary	@	keepassxc-browser.js:1448
(anonymous)	@	keepassxc-browser.js:46
(anonymous)	@	browser-polyfill.min.js:1
EventImpl.dispatchToListener	@	VM182 extensions::event_bindings:403
publicClassPrototype.(anonymous function)	@	VM188 extensions::utils:138
EventImpl.dispatch_	@	VM182 extensions::event_bindings:387
EventImpl.dispatch	@	VM182 extensions::event_bindings:409
publicClassPrototype.(anonymous function)	@	VM188 extensions::utils:138
messageListener	@	VM189 extensions::messaging:240
EventImpl.dispatchToListener	@	VM182 extensions::event_bindings:403
publicClassPrototype.(anonymous function)	@	VM188 extensions::utils:138
EventImpl.dispatch_	@	VM182 extensions::event_bindings:387
EventImpl.dispatch	@	VM182 extensions::event_bindings:409
publicClassPrototype.(anonymous function)	@	VM188 extensions::utils:138
dispatchOnMessage	@	VM189 extensions::messaging:392
```
After disabling and re-enabling the extension, I found that sometimes it worked.  However, after several refreshes, it might stop working.  This is with no other extensions enabled in the same browser profile.  However, I am sometimes running two different profiles in the same google-chrome browser concurrently.  I checked and there end up being 2 instances of keepassxc-proxy in the process list, as expected.

**Comment by varjolintu** [comment] 2018-06-27 16:58
Running multiple browsers simultanously shouldn't cause this, and it seems you haven't got any error messages in your console. I will try to reproduce this issue when I have the time. In the meantime you can try to debug the background page (available from chrome://extensions when debugging is enabled) and see if it shows any additional messages.

**Comment by nbartos** [comment] 2018-07-13 06:00
Would it be possible to automatically do a "Redetect credential fields" if one of the right-click "Fill ..." options are selected but nothing was filled?  After I've been hitting this more, I have noticed that often doing a redetect, then retrying the fill option does work.

**Comment by varjolintu** [comment] 2018-07-13 10:08
This fill be fixed with https://github.com/keepassxreboot/keepassxc-browser/pull/208. I tested it with adding the following sites manually with Username-Only Detection enabled:
- https://www.amazon.com/ap/*
- https://www.paypal.com/signin*

After that the credentials for those sites worked with filling and with autocomplete menu.

**Closed** 2018-07-18 06:48 UTC
Labels: PR pending, bug
