### ISSUE TITLE
New browser - Firefox plugin forgets connection, reconnects and then errors.

### ISSUE THREAD

**Issue by mannp** [keepassxreboot/keepassxc-browser#49] opened 2018-03-06 12:12 UTC
Firstly, great job with the plugin :+1: 

**Error message from keepassxc on pressing the plugin icon.**

> Cannot encrypt message or public key not found. Is native messaging or support for your browser enabled in KeePassXC?

Pressing the 'Reload' button gives me the following error;

> KeePassXC-Browser has been disconnected from KeePassXC.
> KeePassXC association failed, try again
> 
> Press the reconnect button to establish a new connection. 

## Expected Behavior

Connection is made and never forgotten until the connection is deleted by the user.

After being asked if I want to replace the connection with the same name, I should still only have one active connection showing in the connections section of the plugin.

I have two showing as active with the same name?

## Current Behavior

I have successfully made a connection between keepassxc and the new plugin but after a while the plugin asks again to connect to keepassxc, even though the current one still exists.

I create another connection using the same connection name and it correct asks me if I want to overwite the previous one, to which I say yes.

I start using again, all is well until again it appears to lose connection and give me the above error.

**Debug**

Firefox Plugin:
KeePassXC-Browser Version: 1.0.1
KeePassXC Version: unknown 

KeePassXC - Version 2.3.0-snapshot
Build Type: Snapshot
Revision: a06e85f

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.15.6-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by varjolintu** [comment] 2018-03-06 12:24
Does the extension settings show a paired key in the Connected Databases tab when this situation is seen?

**Comment by mannp** [comment] 2018-03-06 18:28
Yes it does.

There is always one key connected and working when it forgets.

When you reconnect using the same name is suggests replacing the old one, but I end up with 2 valid keys with the same name in the list.

**Comment by varjolintu** [comment] 2018-03-06 18:29
Can you confirm that the entry KeepassXC-Browser Settings in your database has the same keys?

**Comment by mannp** [comment] 2018-03-06 18:34
The is only one key in the database against that identifier and it is the **old** key that should have been replaced already.

The newer key (with the same identifier) in the list of keys in the plugin is not listed against KeepassXC-Browser Settings in the database at all.

**Comment by varjolintu** [comment] 2018-03-06 18:41
So am I correct that the following situation happens:
1) You connect the database
2) An KeePassXC-Browser Settings entry is created which holds the same key with the Connected Databases list
3) Something strange happens
4) Extension says it's not connected but the step 2 is still valid?

Can you confirm this is the exact sequence?

**Comment by mannp** [comment] 2018-03-06 18:56
Yes thank you for articulating better than I did.

When 4. occurs it says it needs to be configured and I configure it again with the same identifier and it appears not to replace the old key in the db with the new one, but leaves the old one in place and works again.

**Comment by mannp** [comment] 2018-03-07 09:42
Ok thanks.

It also doesn't sound right that when the plugin suggests replacing the old key with the same id, that it just adds the new key to the list, with the old key, so there are two valid keys?

**Comment by dnlsrl** [comment] 2018-03-08 16:30
This is not exclusive to Firefox, it happens in Chrome as well, both in Windows and Linux. From my post in #55:

> I'm not sure if this should have its own separate issue, but even the updated extension doesn't recognize the database and one needs to revoke the database to get it working again.

> To be quite specific, it says that there is a database connected but the dropdown of credentials won't appear with the login forms, and the "Redetect credential fields" doesn't help either. When inputting the credentials manually though, the extension does give a notification (can't remember what it says exactly, can't seem to be able to make it appear now). What solves the problems is, just as I said, to revoke the database and connect to it again.

> It happened to me first using Linux (Fedora 28 on FF 58/AppImage build) and I dismissed it as a Linux only issue, but it happened to me with Windows 10 Chrome 64 as well.

> EDIT: Even though I found the solution (or actually, was helped out to find it), this isn't supposed to be expected behavior, is it?

Now, it's a new day and it appeared to have forgotten the renewed connection I made yesterday. I'll update this post with logs, but it'll have to be later.

**Comment by varjolintu** [comment] 2018-03-12 08:31
@dnlsrl Can you check if keepassxc-proxy.exe quits when this error happens?

**Comment by varjolintu** [comment] 2018-04-18 08:49
@mook-as Does the same happen with the latest Firefox release? I suppose you are using ESR.

**Comment by gasinvein** [comment] 2018-04-18 10:50
@varjolintu I'm using Firefox 59 and see the same behaviour.

**Comment by varjolintu** [comment] 2018-04-18 10:57
Please check the [troubleshooting guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide).

**Comment by gasinvein** [comment] 2018-04-18 11:03
@varjolintu Already did. What exactly should I do?

**Comment by varjolintu** [comment] 2018-04-18 11:08
Does it help if you remove the keys from the extension and from KeePassXC both and then try reconnect?

**Comment by gasinvein** [comment] 2018-04-18 11:15
No, nothing changed.

**Comment by z3ntu** [comment] 2018-04-18 19:58
Can confirm that killing keepassxc-proxy and reconnecting fixes the issue.

**Comment by z3ntu** [comment] 2018-05-11 14:41
Seems to be better today as I didn't have to kill the proxy application. Had to do that a lot before the latest release(s).

**Comment by z3ntu** [comment] 2018-05-19 11:34
@varjolintu this can be closed now I think?

**Comment by z3ntu** [comment] 2018-05-20 21:00
Speaking of the devil, it seems it just broke for me again and the browser extension doesn't fill in my passwords...
![image](https://user-images.githubusercontent.com/3768500/40283534-0a95d078-5c80-11e8-8127-f5eabd36e6f9.png)

![image](https://user-images.githubusercontent.com/3768500/40283624-8de969d4-5c81-11e8-8453-60cd9aa40c6e.png)

**Comment by varjolintu** [comment] 2018-05-21 04:28
@z3ntu You have something really strange going on there.. Could you try to delete all databases from the browser extension's settings and also delete KeePassXC-Browser Settings entry from your database so there's a clean slate. Then try to connect and associate your browser again.

**Comment by z3ntu** [comment] 2018-05-21 08:58
Did that and it works now again (without manually killing keepassxc-proxy). I'll tell you when it's broken again ;)

**Comment by mannp** [comment] 2018-05-21 09:15
I am also still getting disconnections, but am trying to isolate where for the problem is for the moment....

**Comment by varjolintu** [comment] 2018-05-21 09:27
@mannp Have you upgraded to KeePassXC 2.3.3 and KeePassXC-Browser 1.1.3?

**Comment by mannp** [comment] 2018-05-23 12:57
@varjolintu Yes I have, I am on the latest git from arch AUS and 1.1.3.

I have resorted to leaving the 'plugins' tab open on firefox, so I can disable and reenable the plugin when it happens.

That seems to resolve the issue for me, but its a pain, until the team have time to look further.

**Comment by varjolintu** [comment] 2018-05-23 13:03
@mannp Is keepassxc-proxy running when this situation happens?

**Comment by mannp** [comment] 2018-05-23 16:04
@varjolintu good question, not exactly sure, except I do have the option enabled to use a proxy application in the advanced settings.

I assume that would be keepassxc-proxy as I have not setup any other.

**Comment by varjolintu** [comment] 2018-05-24 04:32
@mannp Yes, that means `keepassxc-proxy` will be used to transfer data between KeePassXC and the browser extension. If that binary doesn't start or it quits by itself, then we have a problem.

**Comment by mannp** [comment] 2018-05-24 09:55
@varjolintu would disabling and reenabling the browser extension restart the proxy, as restarting the extension always seem to get me going again.

**Comment by varjolintu** [comment] 2018-05-24 12:36
@mannp It should do a restart, yes. But if the keepassxc-proxy quits for some reason, that behaviour is not good and we should solve why it happens.

**Comment by Humphreybas** [comment] 2018-11-28 16:35
I have the same/a similar issue. I hope this is appropriate to add here:

- Ubuntu 18.04
- KeePassXC 2.3.1
- Keepassbrowser 1.3.0
- Firefox 63.0.3
- Google Chrome 70.0.3538.102
- (dropbox is syncing the databasefile)


Steps to reproduce:

 - Everything is setup and works
 - Whenever I lock my system (super+L) and login again Keepassbrowser is not connected anymore
 - Unlock Open database in KeePassXC
 - Try again Keepassbrowser, now it shows `KeePassXC-Browser has not been configured. Press the connect button to pair with KeePassXC.`
 - `/usr/bin/keepassxc-proxy` is not interrupted in the meantime
 - Disable and enable extension does restart the keepassxc-proxy but does not fix the issue
 - Last made connection is still visible in 'connected databases' in keepassbrowser settings screen
 - Connect: `You have received an association request fro the above key` need to fill in a name
Tested for firefox only not chrome: 
 - If you fill in a previously used name which is *not* the current name in the list of currently connected databases, it will still notify you that you will overwrite it (so somehow the previous connection is somewhere..)

Extra remark: on my work laptop I do not have this issue. (also Ubuntu 18.04, I expect all other versions also the same but I should double check tomorrow)

**Comment by varjolintu** [comment] 2018-11-28 17:32
@Humphreybas Try the same with 2.3.4.

**Comment by pstorch** [comment] 2018-12-03 21:03
I also had problems with forgotten connections under Ubuntu 18.04 with Firefox.
After changing to KeePassXC 2.3.4 via PPA (Ubuntu default was 2.3.1), the problem is fixed for me.
Thanks.

**Comment by Humphreybas** [comment] 2018-12-10 13:10
yeah that fixed it, I followed these steps: https://keepassxc.org/blog/2017-10-25-ubuntu-ppa/ after the ppa comment of pstorch
(for some reason it doesn't match websites without the `http(s)://` part anymore in 2.3.4 but that is outside the scope of this issue)

**Comment by varjolintu** [comment] 2018-12-10 13:31
@Humphreybas That is fixed in 2.4.0. The checkbox for disabling scheme match is broken in 2.3.4. You can use a newer [snapshot build](https://snapshot.keepassxc.org/) if you like.

**Comment by droidmonkey** [comment] 2018-12-10 13:56
I believe this issue can be closed.

**Closed** 2018-12-10 15:56 UTC
Labels: browser: Firefox, bug
