### ISSUE TITLE
question: strange http requests made while using the browser plugin (firefox)

### ISSUE THREAD

**Issue by metaphys** [keepassxreboot/keepassxc-browser#1864] opened 2023-02-24 09:34 UTC
## Current Behavior

I'm not sure if this is normal, but i noticed that when I open the browser with the keepassxc extension some connection appears to be made to some external ip. Should I be worried?
jean-louis@fushia:~$ lsof -niTCP
COMMAND     PID       USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
[…]
keepassxc 71153 jean-louis  118u  IPv4 295471      0t0  TCP 192.168.200.235:43286->34.107.221.82:http (ESTABLISHED)
keepassxc 71153 jean-louis  131u  IPv4 295621      0t0  TCP 192.168.200.235:43300->34.107.221.82:http (ESTABLISHED)
keepassxc 71153 jean-louis  133u  IPv4 297446      0t0  TCP 192.168.200.235:57810->34.160.144.191:https (ESTABLISHED)
keepassxc 71153 jean-louis  137u  IPv4 297447      0t0  TCP 192.168.200.235:44508->212.227.211.169:https (ESTABLISHED)
keepassxc 71153 jean-louis  138u  IPv4 294699      0t0  TCP 192.168.200.235:60436->104.16.248.249:https (ESTABLISHED)
keepassxc 71153 jean-louis  139u  IPv4 297449      0t0  TCP 192.168.200.235:57596->104.83.4.139:http (ESTABLISHED)
keepassxc 71153 jean-louis  140u  IPv4 297450      0t0  TCP 192.168.200.235:52142->35.241.9.150:https (ESTABLISHED)
keepassxc 71153 jean-louis  141u  IPv4 295628      0t0  TCP 192.168.200.235:53608->13.32.110.72:https (ESTABLISHED)
keepassxc 71153 jean-louis  144u  IPv4 295629      0t0  TCP 192.168.200.235:57610->104.83.4.139:http (ESTABLISHED)
keepassxc 71153 jean-louis  149u  IPv4 298545      0t0  TCP 192.168.200.235:37374->54.149.149.164:https (ESTABLISHED)

those connections disappear as soon as I turn the plugin off
## Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.4
Operating system: Linux x86_64 (debian bookworm)
Browser: Mozilla Firefox 102.0

**Comment by varjolintu** [comment] 2023-02-24 09:47
Possibly related to this, but it should only affect the proxy: https://github.com/keepassxreboot/keepassxc-browser/issues/100

KeePassXC doesn't make any connections anywhere except if you use automatic update check, HIBP or downloading favicons.

**Comment by vukitoso** [comment] 2023-04-20 12:57
FreeBSD 13.2
Firefox: 102.9.0esr
KeePassXC: 2.7.4

```
# sockstat -4
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS      
bsd      firefox    53249 87 tcp4   192.168.1.2:37864     34.117.237.239:443
bsd      firefox    53249 131 tcp4  192.168.1.2:53340     65.9.55.125:443
bsd      firefox    53249 133 tcp4  192.168.1.2:49824     34.117.65.55:443
bsd      firefox    52677 87 tcp4   192.168.1.2:37864     34.117.237.239:443
bsd      firefox    52677 131 tcp4  192.168.1.2:53340     65.9.55.125:443
bsd      firefox    52677 133 tcp4  192.168.1.2:49824     34.117.65.55:443
bsd      firefox    52222 87 tcp4   192.168.1.2:37864     34.117.237.239:443
bsd      firefox    52222 131 tcp4  192.168.1.2:53340     65.9.55.125:443
bsd      firefox    52222 133 tcp4  192.168.1.2:49824     34.117.65.55:443
bsd      keepassxc- 51762 87 tcp4   192.168.1.2:37864     34.117.237.239:443
bsd      keepassxc- 51762 107 tcp4  192.168.1.2:30673     2.23.167.146:80
bsd      keepassxc- 51762 131 tcp4  192.168.1.2:53340     65.9.55.125:443
bsd      keepassxc- 51762 133 tcp4  192.168.1.2:49824     34.117.65.55:443
bsd      firefox    49213 87 tcp4   192.168.1.2:37864     34.117.237.239:443
bsd      firefox    49213 131 tcp4  192.168.1.2:53340     65.9.55.125:443
bsd      firefox    49213 133 tcp4  192.168.1.2:49824     34.117.65.55:443

# ps uax | grep 51762
bsd        51762   0,0  0,1  1132084  23604  -  I    15:46     0:00,01 /usr/local/bin/keepassxc-proxy /home/bsd/.mozilla/native-messaging-hosts/org.k

```

It's not hard to spot duplicate connections from both firefox and keepassxc-proxy


```
bsd      keepassxc- 51762 87 tcp4   192.168.1.2:37864     34.117.237.239:443
bsd      firefox    53249 87 tcp4   192.168.1.2:37864     34.117.237.239:443
bsd      firefox    52677 87 tcp4   192.168.1.2:37864     34.117.237.239:443
bsd      firefox    52222 87 tcp4   192.168.1.2:37864     34.117.237.239:443
bsd      firefox    49213 87 tcp4   192.168.1.2:37864     34.117.237.239:443
```

**Comment by varjolintu** [comment] 2023-04-20 13:00
Closing this as a duplicate of [#100](https://github.com/keepassxreboot/keepassxc-browser/issues/100).

**Closed by varjolintu** 2023-04-20 13:01 UTC
Labels: question

**Comment by vukitoso** [comment] 2023-04-20 13:12
@droidmonkey 
https://github.com/keepassxreboot/keepassxc-browser/issues/100#issuecomment-379568281
> After I tested this, I personally found that turning off the telemetry and usage data in Firefox prevented the sockets from being opened.

How did you disable telemetry? On the example of Firefox 102 and higher
