### ISSUE TITLE
RTL languages should be right aligned

### ISSUE THREAD

**Issue by avma** [keepassxreboot/keepassxc-browser#1569] opened 2022-03-07 09:46 UTC
Currently, the keepassxc browser using Hebrew is left aligned, however RTL languages should be right aligned.
## Expected Behavior

RTL languages should be right aligned.

## Current Behavior

Currently, the keepassxc browser using Hebrew is left aligned, however RTL languages should be right aligned.
## Steps to Reproduce (for bugs)

-login the system with an RTL language (He for example)
-make sure the Firefox browser also behave RTL.
-click on the keepassxc browser icon.

1.
2.
3.
4.

## Debug info

KeePassXC - 2.7.0-snapshot
KeePassXC-Browser - 1.7.11
Operating system: Linux x86_64
Browser: Mozilla Firefox 97.0

![keepassxc browser RTL_2022-03-07_11-41_](https://user-images.githubusercontent.com/7680483/157006970-e9f16918-e066-414a-bf45-995e9de975a1.png)

**Comment by varjolintu** [comment] 2022-03-07 09:49
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/1383.

**Closed by varjolintu** 2022-03-07 09:49 UTC
Labels: bug, user experience
