### ISSUE TITLE
No logins found with KeePassXC 2.6.1 and browser extensions on chromium / firefox

### ISSUE THREAD

**Issue by BullShark** [keepassxreboot/keepassxc-browser#985] opened 2020-09-01 14:49 UTC
## Expected Behavior
When I click the green button from the browser extension, it should fill in my username and password. It does neither.

## Current Behavior
When I click the green button from the browser extension, I get the message "No logins found", but I have many logins stored and opened in Keepass including for the sites I'm trying to login to.

## Possible Solution
Downgrading to 2.6.0 might fix the issue. I noticed the bug after I upgraded to 2.6.1.

## Steps to Reproduce (for bugs)
1. Screenshots below
2.
3.
4.

## Debug info

There are none?
![image](https://user-images.githubusercontent.com/1526595/91866526-3e8d6900-ec38-11ea-8ed6-fd8451270221.png)

KeePassXC - 2.6.1-1 from here https://www.archlinux.org/packages/community/x86_64/keepassxc/
KeePassXC-Browser - 1.6.6
Operating system: Linux (Manjaro KDE)
Browser: Chrome/Firefox/Vivaldi/Chromium

![Screenshot_20200901_083717](https://user-images.githubusercontent.com/1526595/91859517-2c0f3180-ec30-11ea-8d90-64e35f06703e.png)

![image](https://user-images.githubusercontent.com/1526595/91867059-cd9a8100-ec38-11ea-8a19-eec7b2cad2f9.png)

![image](https://user-images.githubusercontent.com/1526595/91865659-3b45ad80-ec37-11ea-8e9c-4f7d9f66e3ee.png)

**Comment by varjolintu** [comment] 2020-09-01 15:01
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/5299.

**Closed by varjolintu** 2020-09-01 15:01 UTC
