### ISSUE TITLE
Auto-generate browser ID

### ISSUE THREAD

**Issue by l0b0** [keepassxreboot/keepassxc-browser#1971] opened 2023-08-26 21:09 UTC
When using KeePassXC-Browser in a new browser, I get asked to type in a new browser ID. As far as I can tell:

1. The ID can be anything.
2. It doesn't matter what the ID is.
3. I never have to deal with the ID after entering it.

Therefore, I'd rather have KeePassXC-Browser generate an ID for me, so I don't have to deal with the prompt.

## Expected Behavior

Using KeePassXC-Browser in a new browser requires zero setup steps.

## Current Behavior

As described in the first paragraph.

## Possible Solution

A UUID is probably safest. "[browser name]-[hostname]" would work for the vast majority, except that there might be duplicates, for example if running multiple versions of the same browser.

## Debug info

KeePassXC - Version 2.7.4
KeePassXC-Browser - 1.8.7 (2023-07-06)
Operating system: Linux
Browser: Firefox/Chromium

**Comment by droidmonkey** [comment] 2023-08-26 21:58
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/5772

**Comment by l0b0** [comment] 2023-08-27 02:32
@droidmonkey Not really, the other ticket is about suggesting a value, this is about getting rid of the UI entirely.

**Comment by droidmonkey** [comment] 2023-08-27 02:41
We would never get rid of the UI

**Closed** 2023-08-27 05:32 UTC
Labels: feature request

**Comment by l0b0** [comment] 2023-08-27 20:24
In that case, what about replacing it with an "OK" button?

**Comment by droidmonkey** [comment] 2023-08-27 21:30
Head over to the issue I linked and make your suggestion there please
