### ISSUE TITLE
Password Generator; ability to change password strength in popup?

### ISSUE THREAD

**Issue by mxmilkiib** [keepassxreboot/keepassxc-browser#1287] opened 2021-03-29 17:56 UTC
4 small buttons next to the existing yellow ones for toggling symbols, extended ascii, and changing the length, would be handy.

The character inclusion toggles could have three letters of that character class as a label.

**Comment by varjolintu** [comment] 2021-03-29 18:01
I consider this as a duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/932

**Closed by varjolintu** 2021-03-29 18:01 UTC

**Comment by mxmilkiib** [comment] 2021-03-29 18:29
Good point, my search-fu was off there.
