### ISSUE TITLE
Browser action icons which blend in better with the Firefox UI

### ISSUE THREAD

**Issue by neon64** [keepassxreboot/keepassxc-browser#1105] opened 2020-11-11 06:25 UTC
This issue is an expression of interest as to whether others are also interested in a flatter/monochrome/less noisy icon in the toolbar, and/or whether a change like this would be considered for upstream.

As you can see in the screenshot below, KeepassXCBrowser stands out compared to other extension action buttons like the Tree-Style Tabs extension.

![screenshot_2020-11-11_17-21-17_008304135](https://user-images.githubusercontent.com/7961339/98776140-830c6080-2442-11eb-862f-6430f688fe67.png)

I forked the extension package and change the icon to a monochrome version, and it fits in much better. I haven't gone and added all of the different variants though (for disconnected state etc...)

![screenshot_2020-11-11_17-18-30_199590814](https://user-images.githubusercontent.com/7961339/98776135-81db3380-2442-11eb-880e-ba7e35235678.png)

Is this a change that would be considered for upstream?

**Comment by varjolintu** [comment] 2020-11-11 06:32
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/465.

**Closed by varjolintu** 2020-11-11 06:32 UTC

**Comment by neon64** [comment] 2020-11-11 06:33
Sorry about that, I should have searched harder for an existing issue - didn't find that one. Thanks.
