### ISSUE TITLE
Chromium + MacOS: key exchange not successful

### ISSUE THREAD

**Issue by euakll** [keepassxreboot/keepassxc-browser#1391] opened 2021-08-08 14:36 UTC
KeePassXC Browser extension can connect to the KeePassXC App, but can not do a successful key exchange. 
KeePassXC settings allow browser extension support for Chromium.

> KeePassXC-Browser - 1.7.9.1 ( oboonakemofpalcgghocfoadofidjkkk )
> Operating system: MacIntel
> Browser: Chromium 88.0.4324.150 (x86_64)
> KeePassXC - Version 2.6.6
> Revision: 386b79a
> Qt 5.15.2
> macOS 10.15
> Kernel: darwin 19.6.0
> - Auto-Type
> - Browser-Integration
> - SSH-Agent
> - KeeShare
> - YubiKey
> - TouchID
> - libgcrypt 1.9.3

~/Library/Application\ Support/Chromium/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json contains:
`{
    "allowed_origins": [
        "chrome-extension://pdffhmdngciaglkoonimfcmckehcpafo/",
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/Applications/KeePassXC.app/Contents/MacOS/keepassxc-proxy",
    "type": "stdio"
}
`

path to keepassxc-proxy is correct, ID of chrome-extension is also correct

**Comment by varjolintu** [comment] 2021-08-08 15:32
What happens if you try to start `/Applications/KeePassXC.app/Contents/MacOS/keepassxc-proxy` manually from the Terminal?

**Comment by gabedot** [comment] 2021-08-08 16:01
I can execute it, but it kind of hangs. also CTRL + C is not interrupting it.

**Comment by varjolintu** [comment] 2021-08-08 16:12
Strange. Everything should be in order then. Does it matter if you enable Chrome support also?

**Comment by gabedot** [comment] 2021-08-08 16:31
I tried all variations of Browser Support activation. Turning them all on/partially on/all off. It always shows the same error.

**Comment by varjolintu** [comment] 2021-08-08 17:22
What does the browser JavaScript Console say?

**Comment by gabedot** [comment] 2021-08-08 17:33
```
keepass.js:1059 Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:1029 Failed to connect: Access to the specified native messaging host is forbidden.
keepass.js:1262 Error: No content script available for this tab.
keepass.js:1142 Error 5: The connection to KeePassXC is not possible. Check if the browser integration is activated in the KeePassXC settings.
keepass.js:1142 Error 5: The connection to KeePassXC is not possible. Check if the browser integration is activated in the KeePassXC settings.
keepass.js:1059 Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:1029 Failed to connect: Access to the specified native messaging host is forbidden.
keepass.js:1262 Error: No content script available for this tab.
keepass.js:1142 Error 9: Key exchange was not successful.
keepass.js:1262 Error: No content script available for this tab.
```

**Comment by varjolintu** [comment] 2021-08-08 17:39
Interesting. Please check that the Chromium path and the JSON scripts are with correct user permissions. Seems something or someone has possibly changed them?

**Comment by euakll** [comment] 2021-08-08 19:36
> check that the Chromium path and the JSON scripts are with correct user permissions. 

No idea how to do that.

**Comment by varjolintu** [comment] 2021-08-08 19:56
> > check that the Chromium path and the JSON scripts are with correct user permissions.
> 
> No idea how to do that.

Use Finder, right-click the folder and/or file and select Get Info. There should be a section called Sharing & Permissions at the bottom.

**Comment by euakll** [comment] 2021-08-08 20:14
`~/Library/Application\ Support/Google/Chrome/` and `~/Library/Application\ Support/Chromium/` contains only `NativeMessagingHosts` with `org.keepassxc.keepassxc_browser.json`. I have read + write permissions everywhere.

nothing else keepass related there

**Comment by varjolintu** [comment] 2021-08-08 20:20
Then please double check the extension ID you have installed in Chromium using `chrome://extensions`. Did you use the official Chrome Web Store for it?

**Comment by euakll** [comment] 2021-09-03 07:33
it is: `chrome://extensions/?id=nmmcabpmnkjefgdkfbjpaadfffhpplmf`
I extract the extension from the store with "Chrome extension source viewer" and install it manually afterwards.

**Comment by varjolintu** [comment] 2021-09-03 13:13
@euakll In that case you must manually modify the JSON script file and add/edit that extension ID to it.

**Comment by euakll** [comment] 2021-09-03 14:38
okay. well I opened up keepass.js but there is no old ID.
changing `keepass.clientID = '';` to `keepass.clientID = 'nmmcabpmnkjefgdkfbjpaadfffhpplmf';` broke it completely.
which variable do you mean? where can I find it?

**Comment by varjolintu** [comment] 2021-09-03 16:50
@euakll Do not change the extension sources. By JSON script I mean the `org.keepassxc.keepassxc_browser.json` file.

**Comment by euakll** [comment] 2021-09-03 17:46
Ok. So I updated the  `org.keepassxc.keepassxc_browser.json` file:

>     "allowed_origins": [
>        "chrome-extension://pdffhmdngciaglkoonimfcmckehcpafo/",
>        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/",
>        "chrome-extension://nmmcabpmnkjefgdkfbjpaadfffhpplmf/"
>    ],

now I am getting a new error twice:

>DevTools failed to load SourceMap: Could not load content for chrome-extension://nmmcabpmnkjefgdkfbjpaadfffhpplmf/fonts/fork-awesome.min.css.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME`

I tried the solution `disable the options: "Enable javascript source maps" "Enable CSS source maps"` ([source](https://stackoverflow.com/questions/61339968/devtools-failed-to-load-sourcemap-could-not-load-content-for-chrome-extension)) but this eliminates the error messages, not the problem itself

**Comment by varjolintu** [comment] 2021-09-03 19:28
You don't need to worry about the .map error messages.

**Comment by euakll** [comment] 2021-09-04 11:04
okay. 
Well then I quitted Chromium and KeePassXC. Started it up both again. unlocked the database. made sure, that browser integration is activated for chromium: "Key Echange not successfull"
So I checked the JSON file again, and the additional line with the ID was missing. So it actually resets this value every time I start Chromium. maybe I can change the extension ID itself to a value of one of the existing?

**Comment by varjolintu** [comment] 2021-09-04 11:49
Disable "Update native messaging manifest files at startup" from Browser Integration Advanced tab so the file is not overwritten.

**Comment by euakll** [comment] 2021-09-04 12:06
I use https://github.com/Eloston/ungoogled-chromium . thats the only way you can install extensions there.
The checkbox doesnt work. Opened an issue over there: https://github.com/keepassxreboot/keepassxc/issues/6891

**Comment by varjolintu** [comment] 2021-09-04 12:46
Change the file to read-only. Maybe that helps.

**Comment by euakll** [comment] 2021-09-04 12:58
genious. 
Actually still a bug. But hey - I does the trick.

**Comment by varjolintu** [comment] 2021-09-04 14:11
Closing this as it's not a bug in the extension itself.

**Closed by varjolintu** 2021-09-04 14:11 UTC
Labels: bug

**Comment by duviful** [comment] 2021-12-01 09:09
I also use https://github.com/Eloston/ungoogled-chromium and i confirm that manually putting the extension ID in `cat ~/Library/Application\ Support/Chromium/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json` and making it read-only makes the extension works with keepassXC!
