### ISSUE TITLE
After unlocking database from the extension, need to reload page for extension to be able to auto-fill

### ISSUE THREAD

**Issue by lodavid** [keepassxreboot/keepassxc-browser#1817] opened 2023-01-04 06:38 UTC
## Expected Behavior

After unlocking the database in the extension, saved credentials should be available for use on the currently displayed web page in the browser

## Current Behavior

Saved credentials are not visible on the currently displayed web page after unlocking until the page is reloaded

## Steps to Reproduce (for bugs)

1. Lock database in KeepassXC, or lock using the lock database button in the extension
2. Navigate to a web page with saved credentials
3. Unlock the database using "reopen database" button in the extension
4. Attempt to use the extension to auto-fill the login fields, but there are no saved credentials visible, and clicking on the key icon next to the username field doesn't do anything
5. Refresh the page
6. Now the saved credentials are visible in the extension and clicking on the key icon fills in the saved credential

## Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.4
Operating system: Win 10
Browser: Firefox and Chromium (Brave)

**Comment by varjolintu** [comment] 2023-01-04 06:45
Cannot reproduce this. Is there a certain site where this happens, or with every page?

**Comment by lodavid** [comment] 2023-01-04 06:54
This happens on every page for me.

Some additional info that may be relevant:

- Have multiple databases open in KeepassXC (1 main, 2 secondary)
- 2 of the databases are auto-opened when the main DB is unlocked using AutoOpen
- The most reliable repro is to lock all of the databases in KeepassXC (either manually in the app) or by locking the screen
- When doing the above, upon the first unlock of the main database, I see the key icon on the username flash from grey (with a lock) to green back to grey (with a lock icon)

**Comment by varjolintu** [comment] 2023-01-04 07:27
So probably the issue is that when you lock databases only one is opened when you click the lock icon, and your credentials are in the second one that remains locked?

**Comment by lodavid** [comment] 2023-01-04 07:30
All of my databases are opened after unlocking the primary DB, thanks to AutoOpen. Also, this happens for sites in the main DB (the one that is unlocked by the extension).

**Comment by varjolintu** [comment] 2023-01-04 07:31
Any errors in the browser's JavaScript console?

**Comment by lodavid** [comment] 2023-01-04 07:40
No errors in the JS console, or any output in the console, for that matter. Yes, the option to search from multiple databases is enabled in KeepassXC. I've also connected the extension to all of the databases.

**Comment by varjolintu** [comment] 2023-01-04 07:44
No errors? It should be expected that at least "No credentials found" or a similar error would be displayed in the console. Please check the background scripts too via `about:debugging` when inspecting the extension.

**Comment by lodavid** [comment] 2023-01-04 07:49
Ah, thank you for pointing out that I need to go inspect the extension to see the errors for it (it didn't show up in the page's console). Here is the console output:

[Error keepass.js:270] KeePassXC-Browser - 1: Database not opened 2 global.js:177:13
Uncaught (in promise) TypeError: global is null
    <anonymous> moz-extension://55edb697-995d-4769-81ad-85c4118aae02/popups/popup_login.js:16
    async* moz-extension://55edb697-995d-4769-81ad-85c4118aae02/popups/popup_login.js:83
popup_login.js:16:20
    <anonymous> moz-extension://55edb697-995d-4769-81ad-85c4118aae02/popups/popup_login.js:77
    AsyncFunctionNext self-hosted:807
    (Async: async)
    <anonymous> moz-extension://55edb697-995d-4769-81ad-85c4118aae02/popups/popup_login.js:83

**Comment by lodavid** [comment] 2023-01-04 07:55
After unlocking the DB by clicking the extension icon and clicking the Reopen database button, then clicking on the greyed out key icon (DB locked) on the username field, there are no errors on the JS console log. Also nothing happens (no pop up, no prompt to unlock DB, etc.)

More observations:

- Unlocking via clicking the extension icon on the browser toolbar (then clicking Reopen database) leads to the errors and the weird behavior as previously described
- Unlocking via clicking on the greyed out key icon (from a locked DB state) yields somewhat better behavior. The credentials are properly filled in. But then the icon on the username field then transitions back to the greyed out key with a lock, clicking on that icon causes nothing to happen. Clicking on the extension icon on the toolbar doesn't show any credentials (and also gives the following JS error)
Uncaught (in promise) TypeError: global is null
    <anonymous> moz-extension://55edb697-995d-4769-81ad-85c4118aae02/popups/popup_login.js:16
    async* moz-extension://55edb697-995d-4769-81ad-85c4118aae02/popups/popup_login.js:83
[popup_login.js:16:20](moz-extension://55edb697-995d-4769-81ad-85c4118aae02/popups/popup_login.js)
    <anonymous> moz-extension://55edb697-995d-4769-81ad-85c4118aae02/popups/popup_login.js:77
    AsyncFunctionNext self-hosted:807
    (Async: async)
    <anonymous> moz-extension://55edb697-995d-4769-81ad-85c4118aae02/popups/popup_login.js:83

**Comment by varjolintu** [comment] 2023-01-04 07:59
Gotta check out that exception. It doesn't seem normal. Thanks!

**Comment by varjolintu** [comment] 2023-01-10 15:45
I could not reproduce this but I made a PR that cleans the code a little bit. Give it a try if you can, thanks:
https://github.com/keepassxreboot/keepassxc-browser/pull/1822

**Comment by lodavid** [comment] 2023-01-11 06:09
Thanks. I checked out PR 1822, and loaded the temporary extension (following instructions at https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually). The error message in the JS console went away, but my issue still remains.

Experimenting a bit more: when I have 1 Auto-Open database (in addition to the primary DB that I unlock), clicking on the extension icon works (but the key icon in the username box still doesn't work). With 2 Auto-Open databases, then neither the extension icon or the key icon works until I reload the page after unlock.

Using the temporary extension, there are no error messages in the JS console in either case.

Would a screen recording be helpful for you to debug/repro the issue?

**Comment by varjolintu** [comment] 2023-01-11 06:19
Screen recording would definitely help. I'm wondering if this is somehow related to Auto-Open. Maybe the messages that indicate that databases are open are not transferred to the extension etc.

**Comment by lodavid** [comment] 2023-01-11 06:51
Here is the [screen recording](https://user-images.githubusercontent.com/8451692/211737072-f97e18a5-70db-44b3-a903-e468eb84ecf2.mp4) and here is the test databases I used (all fake info in there) with password "abc" to unlock the databases in a ZIP file [testDBs.zip](https://github.com/keepassxreboot/keepassxc-browser/files/10389525/testDBs.zip)

**Comment by varjolintu** [comment] 2023-01-11 11:49
I still could not reproduce this. The icons change normally for me. It's a known issue that the popup content doesn't change dynamically after you login and it's kept open, but otherwise it everything should work.

**Comment by droidmonkey** [comment] 2023-01-11 12:16
I can't reproduce either

**Comment by lodavid** [comment] 2023-01-12 07:39
Hmm I wonder what is so special about my setup. I will try to repro on a different machine when I get a chance. Nevertheless, appreciate both of you trying to repro this.

**Comment by Major-Mike** [comment] 2023-01-15 02:17
I don't believe it is something specific to your setup, unless it is something I am doing too. 

I have mine on:
Windows 11 Pro 22H2
Edge 109.0.1518.52 (Official build) (64-bit)
KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.4

And the same thing happens. At least for you when you reload the page they show up, for me it is hit and miss, sometimes no matter how often you reload the page, nothing ever shows up and even manually choosing to fill credentials nothing loads. 99% of the time it won't prompt to save credentials and despite being set to infinite, after a single reload which is common with most sites, the ones that are detected disappear.

**Comment by lodavid** [comment] 2023-01-15 05:41
Nice to know that my setup isn't that unique!

I tried the other night (on the same machine) on Edge (vanilla, no extensions other than KeePassXC-Browser), and also got the same behavior as I had previously reported.

Sometimes when I'm super quick, I can click the key icon right as it turns green, and the saved logins (from the primary DB) show up as expected. But after clicking one (and getting the login auto-filled), it goes back to the gray locked key icon again.

**Comment by varjolintu** [comment] 2023-01-15 07:08
Are you using the Access Confirm dialog or are your entries automatically allowed for the site?

**Comment by lodavid** [comment] 2023-01-15 10:16
I am using the Access Confirm dialog.

After lots of poking around in the bowels of the extension, I have a working theory of what's happening:
* When Auto-Open opens the child databases, it causes the extension to detect a database change
* In the content script (keepassxc-browser.js:101), it responds first by acting as if the database is locked
* Later, keepassxc-browser.js:113, it will set the icons to the unlocked state
* This part I don't quite understand, but only 1 database change will lead to keepassxc-browser.js:113 due to the hash getting cached somewhere
* In my scenario, when I unlock the primary DB with the 2 Auto-Open DBs, 3 database changes will be detected
* This introduces a race condition: if any one of the children DBs unlocks after keepassxc-browser.js:113 is executed, then it will set the state of the extension to locked and then never recover

The reason why I run into this is because I have an older/slower machine. So when the Auto-Open DBs unlock, this happens after the primary DB unlocks->DB change to extension->extension state changes. This would probably be a lot easier to reproduce if the DB security options are set to have the Decryption time take much longer (i.e. 5.0s).

To test out this theory, I removed the " && response.hash.new !== response.hash.old" part of keepassxc-browser.js:106. After doing this, the extensions behave as expected after I unlock my primary DB that then unlocks the children DB. PR here: https://github.com/keepassxreboot/keepassxc-browser/pull/1825

However, I don't know why this caching check was there in the first place. Will leave that to the experts to evaluate if this is a safe change or not.

**Comment by droidmonkey** [comment] 2023-01-18 22:07
Did you enable "Search in all open databases" in the browser settings in keepassxc?

**Comment by dancojocaru2000** [comment] 2023-01-18 22:09
Yes. However, after AutoOpen, it doesn't work. It only starts working after I visit each tab. If I then go back to the AutoOpen database, after visiting each tab after unlock, the browser extension works.

**Comment by dancojocaru2000** [comment] 2023-01-18 22:25
Hold up, just made a new database to test.

It seems the browser extension shows results only if certain tabs are selected? 

In the new database, I added a dummy entry (invalid username and password) for only one website.

Including this new one, I have 5 databases: Master DB (contains only AutoOpen for others), Keys (contains SSH and GPG keys), TOTP, Passwords, Testing.

When going both to one website in the Testing database, and a different website, the browser extension only shows autocomplete data if the last 3 tabs are selected in the main app. If I select the Master DB or the Keys databases in the GUI, the browser extension stops working.

**Comment by droidmonkey** [comment] 2023-01-18 23:14
Are each of those databases connected to the browser extension (check your database settings -> Browser). If so, recommend just connecting your master db. We may have a logic error when multiple databases are connected and search in all databases is enabled.

**Comment by Major-Mike** [comment] 2023-01-18 23:23
Interesting, I had 3 databases and ended up consolidating into a single one because of this problem, thought it was something I was doing wrong. Hopefully when it is resolved, I can separate out the shared, personal and work entries into their own again.

**Comment by varjolintu** [comment] 2023-01-19 05:44
Could you test the current develop branch? It includes the following fixes related to Auto-Open:
https://github.com/keepassxreboot/keepassxc-browser/pull/1825
https://github.com/keepassxreboot/keepassxc-browser/pull/182

**Comment by lodavid** [comment] 2023-01-19 06:23
> Are each of those databases connected to the browser extension (check your database settings -> Browser). If so, recommend just connecting your master db. We may have a logic error when multiple databases are connected and search in all databases is enabled.

For what it's worth, when I only connected the primary DB (before applying the patches), it also didn't work as expected upon unlocking.

**Closed** 2023-02-22 05:29 UTC
Labels: bug, PR pending
