### ISSUE TITLE
KeePassXC plugin does not work with Chomium Snap under Ubuntu 22.04

### ISSUE THREAD

**Issue by dreibh** [keepassxreboot/keepassxc-browser#1948] opened 2023-07-24 07:53 UTC
I am using the KeePassXC plugin with Firefox under Ubuntu 22.04, using the default Snap-based Firefox installation. This works fine, after `flatpak permission-set webextensions org.keepassxc.keepassxc_browser snap.firefox yes`, as described in the Troubleshooting Guide (https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide).

Now, I am trying to get the KeePassXC plugin working with the Chromium browser (default Snap-based installation) on the same system as well. However, I cannot get it working ("Cannot connect to KeePassXC"). Chromium support is enabled in the KeePassXC settings. There is unfortunately no documentation about Chromium under Ubuntu in the Troubleshooting Guide. Is there a permission setting to be made, just as for Firefox (using the command above with "snap.chromium" does not change anything)? Is Chromium/Snap possible at all? I would like to keep the system as default as possible, i.e. perferably not to install Chromium from a PPA.

**Comment by varjolintu** [comment] 2023-07-24 07:59
This is a know issue, and a duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/1267. Chromium based browsers (Flatpak or Snap) do not support Native Messaging out of the box.

**Closed by varjolintu** 2023-07-24 07:59 UTC
