### ISSUE TITLE
Brwoser integration: cannot add new entry -- dialog banner disappears too fast

### ISSUE THREAD

**Issue by 2019-05-10** [keepassxreboot/keepassxc-browser#958] opened 2020-07-30 10:58 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

logging in with a previously uknown account, keepassxc-browser displays a bar asking wether to update or create a new account.
but before I am able to click either button, the bar disappears again.

I suspect this is caused by the site redirecting to a new URL after successful login (OAuth2).

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. go to for example fitbit.com
2. enter your credentials
3. hit log in
4.  keepassxc-browser briefly displays a bar on top of the page 
5. once you are logged in the bar is gone -- since login usually is fast, it is not possible to hit a button (or, if you're really fast, the bar is gone nonetheless and nothing happens either)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
bar should stay and allow adding a new entry

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
bar vanishes

## Context
[NOTE]: # ( Give us any additional information you may have. )
Chromium Version 83.0.4103.116 (Developer Build) built on Debian bullseye/sid, running on Debian bullseye/sid (64-bit)
in extension settings:
Number of allowed redirects: Infinite

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.14.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux bullseye/sid
CPU architecture: x86_64
Kernel: linux 5.7.0-1-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.6

KeePassXC-Browser: 1.6.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by varjolintu** [comment] 2020-07-30 12:17
Please test this with a stable Chromium build. We don't support Beta or Develop versions. I'll take a look if this happens with a stable version too.

**Comment by 2019-05-10** [comment] 2020-07-30 12:27
Vivaldi	3.1.1929.45 (Stable channel) (64-bit)
same game

**Comment by varjolintu** [comment] 2020-07-30 12:45
Could not reproduce this. Tried both Chromium and Edge.

**Comment by 2019-05-10** [comment] 2020-07-30 12:57
URL?

**Comment by varjolintu** [comment] 2020-07-30 13:04
View -> Developer -> Developer Tools. Select the Console tab.

**Comment by varjolintu** [comment] 2021-04-10 15:57
Closing the issue. Will reopen if the problem still exists.

**Closed by varjolintu** 2021-04-10 15:57 UTC
Labels: bug
