### ISSUE TITLE
keepassxc-proxy is phoning out to remote addresses...

### ISSUE THREAD

**Issue by CyberpunkIsBae** [keepassxreboot/keepassxc-browser#982] opened 2020-08-29 16:31 UTC
Steps to reproduce:

$ watch netstat -natp

Observe that keepassxc-proxy (it may show up for you as "keepassxc-pr" due to truncation, but killall keepassxc-pr will yield no processes) is phoning out to remote addresses.  This either means that the proxy is directly connecting out to websites (which seems a very poor choice from a security perspective, though I would welcome to be refuted here on why) or the entire project is a compromised trojan.

Hoping it's not the second one lol.

**Comment by varjolintu** [comment] 2020-08-29 16:46
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/100. This is NOT a KeePassXC issue.

**Closed by varjolintu** 2020-08-29 16:46 UTC
