### ISSUE TITLE
Doesn't connect after upgrading KeePassXC to 2.4.1

### ISSUE THREAD

**Issue by stevegee58** [keepassxreboot/keepassxc-browser#474] opened 2019-04-17 19:37 UTC
Firefox should connect to KeePassXC 2.4.1 (Windows 7, latest FF)

## Current Behavior

I can't connect to KeePassXC 2.4.1.  Firefox add-on displays "Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings."
I have ensured the checkboxes in KeePassXC settings are checked for enabling browser integration and Firefox 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - 2.4.1
KeePassXC-Browser - 1.3.3
Operating system: Win 7
Browser: Firefox

**Comment by varjolintu** [comment] 2019-04-18 03:51
Are you using a portable version? Please check the [troubleshooting guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide) and check the registry entries.

**Comment by stevegee58** [comment] 2019-04-18 13:20
Yes, portable version.
I fixed the problem by using regedit and changed where HKEY_CURRENT_USER\\Software\\Mozilla\\NativeMessagingHosts\\ was pointing.
Should I have to hand edit this every release or is it a bug?

**Comment by varjolintu** [comment] 2019-04-18 13:33
Then this is duplicate of: https://github.com/keepassxreboot/keepassxc-browser/issues/456.

**Closed by varjolintu** 2019-04-18 13:33 UTC
Labels: duplicate
