### ISSUE TITLE
Translations update, please

### ISSUE THREAD

**Issue by Stephan-P** [keepassxreboot/keepassxc-browser#611] opened 2019-09-27 08:04 UTC
## Expected Behavior
I've spend quite some work updating the Dutch translation in TransiFex. To check things, I've downloaded the messages.json and replaced the original file in my local profile. 
I double checked and yes all messages in there are in Dutch language. 
With messages.json locally updated, I would have expected all of KeePassXC-browser to show up in Dutch language.

## Current Behavior
messages.json locally updated. Many messages in the KeePassXC-browser extension remain in English language.

## Possible Solution
I suspect that some work needs to be done in updating string references

## Steps to Reproduce (for bugs)
1. Login to TransiFex
2. Go to the Dutch language (100% translated)
3. Download messages.json
4. Replace messages.json in your local profile (\users\username\app data\local\vivaldi\default\extensions\...

## Debug info
KeePassXC - 2.4.3
KeePassXC-Browser - 1.5.0
Operating system: Win32 (**Incorrect**! Should be Win64)
Browser: Chrome/Chromium 77.0.3865.93 (**Partly incorrect**. Should be Vivaldi 2.9.1675.11 (Officiële build) (64-bits))

![image](https://user-images.githubusercontent.com/10008599/65752893-120acc00-e10e-11e9-8da6-2cd4062bef8b.png)

**Comment by varjolintu** [comment] 2019-09-27 08:19
If everything is in English, it's probably because of you browser locale. Plus, if you update any of the translation files, you'll have to reload the local extension.

**Comment by Stephan-P** [comment] 2019-09-27 08:48
My locale is in Dutch; for the OS, as well as my browser Vivaldi

Stephan Paternotte
---------------------------------------------
E: stephan@paternottes.net

________________________________

**Comment by varjolintu** [comment] 2019-09-27 11:57
Make sure you are following the correct process of testing translations with Vivaldi. This is not a bug in the extension.

**Comment by Stephan-P** [comment] 2019-09-27 15:51
Thank you for your assistance.
What's the correct process of using the keepassxc-browser in Vivaldi browser?

Stephan Paternotte
---------------------------------------------
E: stephan@paternottes.net

________________________________

**Comment by varjolintu** [comment] 2019-10-15 10:03
I have no information how Vivaldi browser handles the locales and translation files for extensions, but AFAIK it shouldn't differ from Chrome/Chromium.

**Comment by Matthaiks** [comment] 2019-11-02 10:52
messages.json files at Transifex are outdated. Check out this report: [WinMerge File Compare Report.zip](https://github.com/keepassxreboot/keepassxc-browser/files/3800379/WinMerge.File.Compare.Report.zip)

**Comment by varjolintu** [comment] 2019-11-02 10:57
I will update it soon. There's still one PR that has more changes to the translation file, and it hasn't been merged yet. So, waiting for that.

**Comment by Stephan-P** [comment] 2019-11-29 16:06
Meanwhile v1.5.3 of KeePassXC_browser has been released and I'm pretty sure that the Dutch translation in Transifex is kept up to date. Still, the KeePassXC-Browser extension remains untranslated English in my Vivaldi browser in Dutch language. The same counts for the Edge (Chromium) browser in Dutch language: KeepassXC Browser is in English.

Info from Vivaldi 2.9.1735.3 (Officiële build) (64-bits):
KeePassXC - 2.5.1
KeePassXC-Browser - 1.5.3
Operating system: Win32 (incorrect. must be Win64)
Browser: Chrome/Chromium 79.0.3945.45

Info from Edge Dev 80.0.334.4 (Officiële build) dev (64-bits):
KeePassXC - 2.5.1
KeePassXC-Browser - 1.5.3
Operating system: Win32 (incorrect. must be Win64)
Browser: Chrome/Chromium 80.0.3965.0

**Comment by varjolintu** [comment] 2019-11-29 16:30
@Stephan-P And everything is fine with Firefox and Chrome/Chromium?

**Comment by Stephan-P** [comment] 2019-11-29 16:41
I don't have these browsers installed anywhere. Could give it a brief experiment.

**Comment by Stephan-P** [comment] 2019-11-29 16:53
I've just installed Chrome on my laptop, switched its UI to Dutch and installed the KeePassXC-browser extension. Chrome is in Dutch, the extension is in English. Also after a restart of Chrome.
I'm now deleting Google Chrome from my laptop again.

**Comment by Stephan-P** [comment] 2020-01-20 08:31
I'd like to add that Edge (Chromium) Stable too does not display KeePassXC-browser in the correct locale, Dutch in my case.

Info from Microsoft Edge 79.0.309.68 (Officiële build) (64-bits)
KeePassXC - 2.5.3
KeePassXC-Browser - 1.5.4
Operating system: Win32 (incorrect. must be Win64)
Browser: Chrome/Chromium 79.0.3945.130

Info from Vivaldi | 2.11.1789.3 (Officiële build) (64-bits)
KeePassXC - 2.5.3
KeePassXC-Browser - 1.5.4
Operating system: Win32 (incorrect. must be Win64)
Browser: Chrome/Chromium 79.0.3945.118

**Comment by varjolintu** [comment] 2020-01-20 08:33
When I tested the Edge support, for some reason Edge was installed in a wrong language (spanish), and the locale worked just fine.

I haven't heard about these issues from anyone else, and I cannot reproduce them. Can you verify this happens on other computers too?

**Comment by Stephan-P** [comment] 2020-01-20 08:51
On my PC's the installation of Edge was in in English language, but soon enough I changed that into Dutch language for the UI.
On my PC's, the OS is Dutch and most of my apps are in Dutch language, so are my Vivaldi's and Edge's.

But I've got a pleasant surprise for you.
Remember you asked me to also test Firefox? Well I just did.
I downloaded and installed [the Dutch language version of Firefox](https://www.mozilla.org/nl/firefox/all/#product-desktop-release) and added the KPXC-B add-on.
Lo and behold: finally KPXC-B showed up in Dutch language!

So, the issue seems to seems to ly between KPXC-B and the Chromium-based browsers.
Possibly the locale detection is failing for these browsers?

**Comment by Stephan-P** [comment] 2020-01-20 08:56
Is there anything I can do, here on my Dutch browsers, to debug this issue?
With some guidelines from you I might give it a trie.

**Comment by Stephan-P** [comment] 2020-01-20 09:06
Or - if you say that Spanish is working alright - could it be that the Dutch language is not (yet) included in  KeePassXC-Browser v1.5.4?

**Comment by varjolintu** [comment] 2020-01-20 09:10
nl_NL locale is included in the extension.

I'm quite sure this issue has something to do with Chromium-based browsers and not the extension itself. Do you have any other extensions that have the same problem in the same browser?

**Comment by Stephan-P** [comment] 2020-01-20 09:23
Nope, KPXC-B is the only one.

But I've got another clue:
I decided to change the UI language for Edge into Spanish. After the restart KPXC-B showed up in Spanish. Same for French.
So, the issue lies seems to narrow down to the Dutch language.
I don't know how these browsers present their locale to the extension, but could it be the distinction or a mismatch between nl, NL, nl-NL, nl-BE, ....?

**Comment by varjolintu** [comment] 2020-01-20 09:29
That actually could be the issue, because according to this list, the locale should be `nl`: https://developer.chrome.com/webstore/i18n#localeTable

And because translations are received from Transifex, I think the renaming must be done there.

**Comment by varjolintu** [comment] 2020-01-20 09:35
Seems Transifex has both `nl` and `nl-NL` for Dutch (Netherlands). I added the `nl`, but I'm unsure if the same locale can be used for both. I bet you're the professional one here :)

**Comment by Stephan-P** [comment] 2020-01-20 09:48
You've added a new branch nl next to the existing nl-NL.
I can't seem to find a way to copy the existing nl-NL translation to the nl branch.
(I am able to download, but the option to upload to 'nl' does not appear.)
Can you do that easily?

About nl, nl-NL, nl-BE, nl-FY:
nl is the general Dutch language
If one is interested in making distinction between Dutch language from The Netherlands or Dutch language from Belgium, then nl-NL and nl-BE are the respective dialects. There's not much point in this because both countries use a common dictionary and grammar rules.
In the Netherlands we have one official sub language Frysian (nl-FY), but this is not supported from chrome.

So, I guess we can do with one single Dutch language: nl.
You could either rename the old nl-NL into nl, or copy the contents from nl-NL into the new nl and remove the old nl-NL.
Is that something you can do more easily than I can?

**Comment by Stephan-P** [comment] 2020-01-20 09:52
Ha!
I managed to add myself as translator and upload the complete translation I had just downloaded from nl-NL.
It's up to you what to do next: 
- remove nl-NL (with its translators)
- Remove nl and rename nl-NL into nl (keeping its translators)

**Comment by varjolintu** [comment] 2020-01-20 09:55
Let's keep the `nl-NL` intact because that might affect to users that actually use that locale.

**Comment by Stephan-P** [comment] 2020-01-20 10:38
You may want to check the other languages that use the extended coding:
- zh-CN
- zh-TW
- hr-HR
- pt-PT
- pt-BR

my guess is that Croatian, like Ducth should be a short code 'hr'
Not sure about Chinese and Portugese.

**Comment by varjolintu** [comment] 2020-01-20 10:48
Chinese and Portugese are correct. Croatian is not. So we need to change that one too.

**Closed** 2020-03-21 21:16 UTC
Labels: PR pending, i18n

**Comment by Stephan-P** [comment] 2020-03-22 20:37
I may be speaking ahead of time, but since you closed this issue I was interested to see the new "nl" language getting in place.
But https://github.com/keepassxreboot/keepassxc-browser/tree/develop/keepassxc-browser/_locales shows the folder nl-NL from 11 months ago instead of the folder "nl".
I hope that this is still on your to-do list before the new relese

**Comment by varjolintu** [comment] 2020-03-22 20:40
@Stephan-P The translations are downloaded from Transifex when making a new release, so `nl` is there. The repository is just not up-to-date.

**Comment by Matthaiks** [comment] 2020-03-27 15:28
BTW, some translated strings in KeePassXC 2.5.3 are in English only. For instance,
> KeePassXC-Browser is needed for the browser integration to work. <br />Download it for %1 and %2. %3

**Comment by varjolintu** [comment] 2020-03-27 15:35
@Matthaiks That means someone hasn't translated them for your language via Transifex.

**Comment by Matthaiks** [comment] 2020-03-27 16:15
@varjolintu But those strings are translated and that's the problem. I've copied that example above from the fully translated file.

**Comment by Stephan-P** [comment] 2020-03-27 16:30
@Matthaiks if you're talking about the current version of kpxc-browser, then the Dutch translation is not yet in place. This is expected with the next release. Everything is ready place in for this.
@varjolintu if this particular string Matthaiks is referring to should be left untranslated, then I could fix that. Just let me know.

**Comment by Matthaiks** [comment] 2020-03-27 16:49
I'm talking about KeePassXC 2.5.3. It seems that all languages are affected. Some strings are just hard-coded or something.

**Comment by varjolintu** [comment] 2020-03-27 21:58
What are those strings exactly?

**Comment by Stephan-P** [comment] 2020-03-28 05:32
There's a confusion here. Matthaiks is talking about a text text string KPXC, not KPXC-Browser. Wrong Github tree.

**Comment by Matthaiks** [comment] 2020-03-28 07:45
@Stephan-P Yes, sorry for hijacking your thread.

@varjolintu More strings:

From 'Encryption Settings'
> AES: 256-bit
> Twofish: 256-bit
> ChaCha20: 256-bit
> 
> Argon2 (KDBX 4 – recommended)
> AES-KDF (KDBX 4)
> AES-KDF (KDBX 3.1)

From 'Secret Service Integration'
> File Name
> Group
> Application
> Manage
> None
> Edit database settings
> Lock database
> Unlock to show
> Unlock database to show more information

**Comment by varjolintu** [comment] 2020-03-28 07:47
@Matthaiks Those translations are not related to the extension at all. You are referring to the main application translations.

**Comment by Stephan-P** [comment] 2020-03-28 08:36
Best to report them [HERE](https://github.com/keepassxreboot/keepassxc/issues)
