### ISSUE TITLE
Opening KeepassXC in infinte loop

### ISSUE THREAD

**Issue by smoyth** [keepassxreboot/keepassxc-browser#555] opened 2019-05-27 18:15 UTC
## Expected Behavior

Extension should open one copy of KeepassXC per browser profile with extension enabled.

## Current Behavior

It opens infinite copies, about one every second. I have a screen recording I can share if you send me your Google ID.

I am not sure if this is related to the fact that I have two browser profiles using the extension. I have had this working before but sometimes this happens. Haven't been able to isolate what makes it happen. I tried just opening one of the browser profiles but the same thing happens. I tried closing all tabs and starting chrome with just the plain home page, same thing. I tried checking the 'only open one instance' box in KeepassXC but then it is just a race with the extension opening them and KeepassXC shutting them down, making the computer unusable.

## Steps to Reproduce (for bugs)

Not sure honestly. Posting here without the full repro steps in the hope that someone with more knowledge of the internals can help me reproduce.

## Debug info

KeePassXC - 2.4.1
KeePassXC-Browser - 1.4.4
Operating system: Mac
Browser: Chrome

**Comment by varjolintu** [comment] 2019-05-28 05:00
Please try the updated version 1.4.5 and see if it fixes the issue.

**Comment by alexanderadam** [comment] 2019-05-28 05:01
@varjolintu it doesn't. The behaviour still exists.

**Comment by varjolintu** [comment] 2019-05-28 05:03
So this probably happens when you are not using the proxy. Otherwise the KeePassXC shouldn't be launched.

**Comment by alexanderadam** [comment] 2019-05-28 05:05
Disabling `Settings > Automatically reconnect to KeePassXC.` works. :+1:

**Comment by varjolintu** [comment] 2019-05-28 05:07
I'll see to this problem but eventually we are going to move the whole reconnect feature inside the proxy, so that's priority one. Everyone having issues, just disable the automatic reconnect.

**Comment by alexanderadam** [comment] 2019-05-28 05:10
@varjolintu I'm not sure whether it's the same or a different issue:

Keepass now stops opening and closing all the time but I can't connect to it anymore. When I click on the KeepassXC browser it says `checking status` for a short moment, the native KeePassXC instance focusses and the KeePassXC browser modal closes.

Meaning it is impossible to connect.
Is this the same issue or should I create another issue for that?

**Comment by varjolintu** [comment] 2019-05-28 05:14
@alexanderadam Are you using proxy or not? If not, KeePassXC needs to be closed before making a reconnect. Native Messaging cannot connect to an existing process.

**Comment by alexanderadam** [comment] 2019-05-28 05:19
@varjolintu I'm not sure. How can I check that?

I don't think I changed or configured anything regarding the connect. Or can I somehow install an older version of the extension that worked?

**Comment by varjolintu** [comment] 2019-05-28 05:28
@alexanderadam KeePassXC's settings -> Browser Integration -> Advanced (tab) -> [x] Use a proxy application between KeePassXC and browser extension.

**Comment by alexanderadam** [comment] 2019-05-28 05:34
@varjolintu with the proxy setting it is working again.

Yesterday it worked totally fine so I guess the default connection (without a proxy) broke with the last update?

**Comment by varjolintu** [comment] 2019-05-28 05:38
@alexanderadam It's not a big risk after all. The messages are still encrypted all over and are transferred only locally. With proxy everything works better and you can leave KeePassXC open in the background or open it when you want to. It's not ideal (to not to use the proxy) and let your browser handle the KeePassXC process. But some want to do it that way.

**Comment by alexanderadam** [comment] 2019-05-28 05:40
> It's not ideal (to not to use the proxy) and let your browser handle the KeePassXC process. But some want to do it that way.

On the other hand it worked perfectly fine until yesterday :wink:

**Comment by varjolintu** [comment] 2019-05-28 05:41
@alexanderadam I'll check what causes this, of course :)

**Comment by alexanderadam** [comment] 2019-05-28 05:44
@varjolintu thank you so much. :raised_hands: 
Not only for looking into this issue but also for your fast responses and your _amazing_ work in general!

**Comment by smoyth** [comment] 2019-05-28 13:45
Hear hear!

**Comment by varjolintu** [comment] 2019-06-02 06:06
1.4.6 is now released. It force-disables the Auto-Reconnect and it's considered as an experimental feature. Use at your own risk.

If no proxy is used, please check the checkbox "Start only a single instance of KeePassXC" from the application settings. With that setting a new KeePassXC is launched every time KeePassXC is closed if Auto-Reconnect is enabled, but it will not spawn multiple processes. I couldn't reproduce the issue in the first message of the issue thread.

If you have upgraded to KeePassXC 2.4.2 it has a problem with linking keepassxc-proxy correctly on macOS. You can install libsodium via Homebrew for a workaround.

**Closed** 2019-06-30 11:03 UTC
Labels: bug
