### ISSUE TITLE
KeePassXC-Browser not working after update of KeePassXC to version 2.6.1

### ISSUE THREAD

**Issue by mario0511** [keepassxreboot/keepassxc-browser#994] opened 2020-09-03 12:56 UTC
## Expected Behavior

Cant get any credentials suggestions in the browser after update of KeePassXC to version 2.6.1
Looks like the browser can not read from the database or can not compare urls, just a guess.
Already restarted KeePassXS as well as the browser.

## Steps to Reproduce (for bugs)

1. install version 2.6.1

## Debug info

KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.2
Operating system: Windows 10 Pro 64bit
Browser: Chrome

**Comment by varjolintu** [comment] 2020-09-03 13:56
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/5299.

**Closed by varjolintu** 2020-09-03 13:56 UTC
