### ISSUE TITLE
"Choose Custom Login Fields" creates two popups if login form appears inside an iframe

### ISSUE THREAD

**Issue by anon324875693** [keepassxreboot/keepassxc-browser#1028] opened 2020-09-29 12:38 UTC
![double](https://user-images.githubusercontent.com/71826738/94559294-87910700-0250-11eb-9ebb-376e5c4b2086.png)

index.html
```
  <div class="blank" style="height:100px"></div>

  <div class="iframe-wrapper"></div>
    <iframe src="login.html" style="width:800px; height:400px"></iframe>
  </div>
```
login.html
```
<html>

<head>
  <meta charset="utf-8">
  <title></title>
</head>

<body>
  <form novalidate="">
    <div class="accountForm" style="display: block;">
      <div class="row">
        <h3>Login</h3>
      </div>
        <fieldset>
          <input id="loginEmail" type="text" placeholder="Your Email" class="form-control">
          <input id="loginPassword" type="password" placeholder="Password" class="form-control"> 
          <button class="form-control btn btn-success">Log In</button>
        </fieldset>
    </div>
  </form>

</html>

```

This is with browser addon version 2.7.1, the latest.

**Comment by varjolintu** [comment] 2020-09-29 13:17
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/454.

**Closed by varjolintu** 2020-09-29 13:17 UTC
