### ISSUE TITLE
"Generate Password" blocks the GUI even after Closing it via X

### ISSUE THREAD

**Issue by Grizzler89** [keepassxreboot/keepassxc-browser#1635] opened 2022-05-31 18:02 UTC
Opening the "Generate Password"-Tool via Browser (Button next to a password field) results in an modal window. While it is open, the KeePassXC-GUI ist not usable.

After closing the "Generate Password"-Window via the X in the top-right corner, you still can't interact with the KeePassXC-Gui. It's like there still is an modal window.

You can open the "Generate Password"-Tool via Browser again. 

If you close the "Generate Password"-Tool via the "Close"-Button in the bottom-right, everything works fine.

OS: Windows 10 
Browser: Firefox 100

**Comment by Grizzler89** [comment] 2022-05-31 18:15
I'm using KeePassXC 2.7.1 and KeePassXC Browser 1.7.12.

Firefox just updated to 101. I can still reproduce the bug.

**Comment by varjolintu** [comment] 2022-05-31 19:25
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/7952.

**Closed by varjolintu** 2022-05-31 19:25 UTC
