### ISSUE TITLE
After Upgrade (Sept 2nd) cannot connect to self signed cert sites

### ISSUE THREAD

**Issue by emrecio** [keepassxreboot/keepassxc-browser#989] opened 2020-09-02 16:07 UTC
Go to a self-signed certificate site. Attempt to fill in by clicking the icon at the username box. Nothing happens.

What should happen is (from before the forced upgrade of extension and application) I would login to a local site with a self signed cert and it would apply the password.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by varjolintu** [comment] 2020-09-02 16:10
There's no restrictions related to certificates. KeePassXC update is not forced. 2.6.1 has a bug concerning URL matching. Try if the same happens with 2.6.0.

**Comment by yan12125** [comment] 2020-09-02 16:54
> Attempt to fill in by clicking the icon at the username box. Nothing happens.

I got the same issue with all websites I use. Some examples: GitHub login page, https://www.glowing-bear.org/.

From the addon console, I see penty of error messages like

> Could not establish connection. Receiving end does not exist

Haven't had time to check if my configurations are correct. Reinstalling 1.6.6 for now and at least GitHub login page and Glowing Bear work again.

## Debug info

KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.0
Operating system: Arch Linux
Browser: Firefox 80.0.1

**Comment by varjolintu** [comment] 2020-09-02 17:01
Sometimes when the extension update happens on-the-fly browser needs a restart. Consider trying KeePassXC 2.6.0 if you have problems with matching.

**Comment by yan12125** [comment] 2020-09-02 17:15
Thanks for the suggestion. I tried restarting Firefox and the issue still persists with 1.7.0.

Something I forgot to said: with 1.7.0, if I right-click on the username field and select KeePassXC-Browser -> Fill Username and Password from the context menu, everything works. So I assume the issue is not related to URL matching and I did not try KeePassXC 2.6.0.

**Comment by varjolintu** [comment] 2020-09-02 17:19
@yan12125 That sounds strange because GitHub login page is one of those I test constantly. Glowing Bear doesn't give me any headaches either.

Can you verify you are not using any Custom Login Fields etc? Does the autocomplete menu appear if you click the username input field? Also, check the JavaScript console for any error messages. Also, if you have notifications disabled, that might supress any errors shown on the DOM.

**Comment by yan12125** [comment] 2020-09-02 17:26
Thanks I do use custom login fields with Glowing Bear. I'll check out these possibilities.

**Comment by varjolintu** [comment] 2020-09-02 17:29
@yan12125 Sadly the Custom Login Fields behavior is also refactored so the old configurations might not work properly. Also, I noticed that the new implementation is not perfect with the Glowing Bear site, so some fixes may be needed.

**Comment by yan12125** [comment] 2020-09-03 03:20
I guess I know the cause of the issue. I have "Automatically retrieve credentials" un-checked in KeePassXC-Browser preferences. As a result, there are no credentials when the following line is reached

https://github.com/keepassxreboot/keepassxc-browser/blob/591272fd7a3e1a4ac29fe8d2c67f5b8442662f72/keepassxc-browser/content/keepassxc-browser.js#L783

**Comment by varjolintu** [comment] 2020-09-03 18:58
@emrecio Could you please disclose what version of KeePassXC are you using? If you have troubles with 2.6.1, downgrade to 2.6.0.

**Closed** 2020-11-07 17:17 UTC
Labels: bug
