### ISSUE TITLE
"Only returns best matches" is too picky

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#167] opened 2018-05-21 19:27 UTC
I really like you implemented https://www.emailprivacytester.com/, but after some testing Inoticed it is sometimes to picky.

E.g. say I have these two password entries:
* one with URL set to `https://gitlab.com`
* one with URL set to `https://gitlab.com/`

GitLab's login page is at https://gitlab.com/users/sign_in.

So KeePassXC browser only showed me the second entry. When I changed the first one by adding a slash, it also showed me this one.

KeePassXc 2.3.3
KeePassXC browser 1.1.3

**Comment by droidmonkey** [comment] 2018-05-21 21:00
Technically the / added makes it more specific. But I do agree with your assessment.

**Comment by rugk** [comment] 2018-05-21 21:46
Well… I don't know how "Only save domain" is implemented, but if it does not save this `/` at the end, then KeePassXC browser itself will not re-detect that login credentials, which is of course not what is intended.

So IMHO if only the domain is saved, it of course applies to everything below under that domain. (What else?)

**Comment by varjolintu** [comment] 2018-05-22 05:24
I tested the same behaviour with https://github.com/keepassxreboot/keepassxc-browser/pull/151 and it detected both entries.

**Comment by rugk** [comment] 2018-05-22 08:06
> I tested the same behaviour with #151 and without it. Both entries were showed. 

But that PR is about saving. Did you test that you can reproduce the original issue (`https://gitlab.com` not as a suggestion)?
If that would work, it likely does not happen how domains are saved. (In this case without the slash it may even be clearer.)

All I want is that it works to show me the suggestions I want.

**Comment by varjolintu** [comment] 2018-05-22 08:10
@rugk Yes, I made two entries like you did, other one lacks the `/`. Both still work.

**Comment by varjolintu** [comment] 2018-09-09 07:12
Any changes with this issue with the latest KeePassXC release?

**Comment by rugk** [comment] 2018-09-09 08:49
No, can still reproduce.

Note that all other things in the two entries differed. Title, username (mail) and so on. It's just the URL field that has one time `/` and one time has not.
I also switched them around and I can totally reproduce this.

Firefox 62.0
KeePassXC-Browser Version: 1.2.0
KeePassXC Version: 2.3.4

**Comment by varjolintu** [comment] 2018-09-09 09:07
Still cannot reproduce. Not with Chromium 69 and not with Firefox 62.
I can see both entries in the Gitlab login page.

**Comment by varjolintu** [comment] 2018-09-09 09:17
I'm not sure if this is an actual bug, because the best matches does here like it's supposed to do:
`https://gitlab.com/` is closer to the original URL `https://gitlab.com/users/sign_in` than `https://gitlab.com`. If you modify the entry and remove the `https://gitlab.com/` URL, then the other one will be returned as a best match.

**Comment by rugk** [comment] 2018-09-09 16:43
I consider it a bug, because – seeing it from a user's perspective – it does not matter if I go to `https://gitlab.com` or `https://gitlab.com/`, I'll end up at the same site.

**Comment by varjolintu** [comment] 2020-01-08 13:38
Oh, here's finally a fix for this: https://github.com/keepassxreboot/keepassxc/pull/4134. Now the both URL's will receive the same priority.

**Closed** 2020-01-13 09:36 UTC
Labels: bug
