### ISSUE TITLE
b2b.dab-bank.de: login fields (username/password) not detected

### ISSUE THREAD

**Issue by schorfi** [keepassxreboot/keepassxc-browser#1213] opened 2021-02-05 23:34 UTC
The browser extension fails to detect the login fields (username & password) on https:/b2b.dab-bank.de/Tradingcenter/ Neither "Redetect login fields" nor "Choose custom login fields" works.

## Expected Behavior
Login fields should be detected and filled out properly on request. At least saving the credentials manually should work.
Manual selection should of login fields should give the option to select them.

## Current Behavior
I can't save username/password for the site. I tried both "Redetect login fields" and "Choose custom login fields", but neither worked. The login fields are not detected.

## Possible Solution
No clue

## Steps to Reproduce (for bugs)
1. Go to https:/b2b.dab-bank.de/Tradingcenter/
2. try to safe credentials
3. try to select custom login fields

## Debug info

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.6
Operating system: Linux
Browser: Firefox 85.0

**Comment by varjolintu** [comment] 2021-02-06 06:09
Duplicate of #1116.

**Closed by varjolintu** 2021-02-06 06:09 UTC

**Comment by schorfi** [comment] 2021-02-06 10:00
sorry for the dup
