### ISSUE TITLE
Timeout or not connected to KeePassXC

### ISSUE THREAD

**Issue by bigon** [keepassxreboot/keepassxc-browser#130] opened 2018-04-25 11:50 UTC
Hi,

With firefox 59, keepassxc-browser 1.0.1 and keepassxc 2.3.1 on debian unstable I get " Cannot encrypt message or public key not found. Is native messaging or support for your browser enabled in KeePassXC? " the first time I'm opening firefox.

If I start and then quit keepassxc, I then see: "Timeout or not connected to KeePassXC"

Edit: There is a reload button, but no options to start and unlock the db

**Comment by varjolintu** [comment] 2018-04-25 11:57
If you want the browser extension to control (launch and quit) KeePassXC please disable the proxy (meaning `keepassxc-proxy` process) from the Browser Integration's Advanced settings.

By default, KeePassXC must be started for the connection to be established and database must be opened for making the connection permanent to your current database.

**Comment by bigon** [comment] 2018-04-25 12:09
The error messages are less than optional here, maybe that could be improved?

**Comment by varjolintu** [comment] 2018-04-25 12:14
You can always provide the logs from the debugging console and see if there's any more error messages. You can find it from `about:debugging`.

**Comment by abishai** [comment] 2018-04-25 13:07
I have partially working extention as well, and this error in particular.
```
On debug, I see the following error:
13:03:31.220 JSON.parse: unterminated string at line 1 column 61 of the JSON data 1 subprocess_common.jsm:480
	readJSON/< resource://gre/modules/subprocess/subprocess_common.jsm:480:16
```

**Comment by abishai** [comment] 2018-04-25 13:29
@varjolintu this error is seen when database query keepassxc status, producing Timeout or not connected to KeePassXC.  Strangely, Reload button seems to work (if database is opened)

**Comment by varjolintu** [comment] 2018-04-25 13:31
@abishai That's strange. There shouldn't be any response from keepassxc-proxy if KeePassXC is closed.

**Comment by abishai** [comment] 2018-04-25 13:46
@varjolintu Nope, keepass is not closed. I 100% receive it if I click Block database and extension query database status after it.

**Comment by varjolintu** [comment] 2018-04-25 14:03
Cannot reproduce that one.

**Comment by varjolintu** [comment] 2018-04-25 14:30
@abishai I have seen this kind of behaviour when there's some special characters in the JSON data (fixed in 2.3.2).

**Comment by abishai** [comment] 2018-04-25 14:36
I see. Thank for support, will try to compile 2.3.2

**Comment by varjolintu** [comment] 2018-04-27 06:09
@abishai Excellent! So 2.3.2 will definitely deliver the fix for this.

**Comment by emeygret** [comment] 2018-04-27 12:09
Hello, I have the same issue timeout with keepassxc 2.31.
I build 2.3.2 and it seems to be working, but I had to remove this patch whereas build failed on Windows https://github.com/keepassxreboot/keepassxc/pull/1720

**Comment by varjolintu** [comment] 2018-04-27 12:17
@emeygret Looking at this https://github.com/keepassxreboot/keepassxc/commit/062503a903b525a3ebe34e103a6ffb07f85a26e7 you can see a fix was committed 9 hours ago. Try to update the branch and compile again.

**Comment by emeygret** [comment] 2018-04-27 14:26
it is better but missing proxy/NativeMessagingHost.cpp , i had a comment on the fix

**Comment by varjolintu** [comment] 2018-04-27 14:47
Thanks for noticing it. I'll make a new fix.

**Comment by bigon** [comment] 2018-04-27 15:50
Any ETA for a new release?

**Comment by varjolintu** [comment] 2018-05-11 08:25
Please test if this still happens with KeePassXC 2.3.3 and KeePassXC-Browser 1.1.3.

**Comment by emeygret** [comment] 2018-05-11 08:36
for me it is ok, it work fine with 2.3.3/1.1.3, 
and Tested during 2 week with 2.3.2/1.0.1

**Closed** 2018-05-11 15:59 UTC
Labels: bug
