### ISSUE TITLE
Can't modify password generator

### ISSUE THREAD

**Issue by bigfatfrog67** [keepassxreboot/keepassxc-browser#932] opened 2020-07-08 19:24 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: #The Password generator screen when on a webpage doesn't allow configuring of password

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  When on a webpage, click the green key
2.  the dialog  doesn't off a choice to modify how the password is generated
3. 

## Expected Behavior
[NOTE]: # The dialog should include options for included character types (A-Z) (a-z) (0-9) etc

## Actual Behavior
[NOTE]: # It's not possible

## Context
[NOTE]: # It makes the dialog almost useless as each site has different rules for length, format etc of passwords so I nearly always have go to the main KeePassXC window.
![SharedScreenshot](https://user-images.githubusercontent.com/2147089/86961304-e9ae0480-c158-11ea-8283-c96f4b49478e.jpg)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Version 2004
Desktop Env: Windows
Windowing System: Windows

**Comment by wohali** [comment] 2020-07-13 17:57
@droidmonkey This doesn't seem to be the case as of the brand new KeePassXC release.

Previously, I would change my settings in KeePass for a random password to be generated - by default I disable non-alphanumerics and increase the length:

![Snap 2020-07-13, 13_56_31](https://user-images.githubusercontent.com/112292/87336983-b4b30080-c510-11ea-9436-f5db972bc871.png)

Prior to updating KeePassXC to 2.6.0, this worked fine.

As of my update to KeePassXC this morning, the browser plugin is no longer respecting the settings in KeePassXC:

![Snap 2020-07-13, 13_56_41](https://user-images.githubusercontent.com/112292/87337046-ce544800-c510-11ea-8c29-ce607911e948.png)

I'm certain there is some sort of regression introduced by 2.6.0.

**Comment by droidmonkey** [comment] 2020-07-13 18:06
Ping @varjolintu

**Comment by varjolintu** [comment] 2020-07-13 20:04
Cannot reproduce. Please note that you must close the password generator to apply the settings. Those still doesn't change on-the-fly.

**Comment by droidmonkey** [comment] 2020-07-13 20:30
You probably also need to refresh the page as well or at least close/open the generator on the web page.

**Comment by varjolintu** [comment] 2020-07-13 20:33
The generator can be open all the time. The generator just needs to be closed in KeePassXC.

**Comment by wohali** [comment] 2020-07-14 04:59
I hadn't changed the password generator settings in well over a year. But, after reopening and closing that settings window 3 times, it seems to have cleared the issue.

/shrug

**Comment by bigfatfrog67** [comment] 2020-07-14 17:01
Why has this been closed?  My original request hasn't been actioned has it?

**Comment by droidmonkey** [comment] 2020-07-14 19:14
Sorry good point, lots of issues popping in and out

**Comment by ei-ke** [comment] 2020-12-26 14:30
I'd like to add the suggestion to obey the password length that was set for an entry. Regenerating password in an entry itself remembers the length the password had (some websites don't like passwords longer than n), the browser extension follows the general password generators settings.

**Comment by varjolintu** [comment] 2020-12-26 17:52
@ei-ke But that would create a problem that you couldn't make shorter or longer password than in your entry already has?

**Comment by droidmonkey** [comment] 2020-12-26 17:54
the in-browser password generator concept needs a bit of a reboot IMO.

**Comment by varjolintu** [comment] 2020-12-26 18:00
@droidmonkey Sure does. It should directly open the current settings and modify them, or something similar.

**Comment by ei-ke** [comment] 2020-12-26 18:00
@varjolintu That's true and wasn't my personal issue.
My issue was that with websites that allow only certain password length. I thought about opening a feature request and found this issue.
So maybe it would be an option to use the length settings from an entry or even better: use the length/character class set in an entry and giving the option to change the length/character class and also save this to the entry fir future password changes (but maybe the generator used within an entry is based on the current password used and thus the last step is unnecessary. I've nearly no programming knowledge to figure this out.)

**Comment by droidmonkey** [comment] 2021-10-07 11:36
This should be closed with the new method of calling up the keepassxc generator directly in 2.7.0

**Comment by varjolintu** [comment] 2021-10-07 12:40
Closing because of https://github.com/keepassxreboot/keepassxc-browser/pull/1329.

**Closed by varjolintu** 2021-10-07 12:40 UTC
Labels: feature request

**Comment by xcasxcursex** [comment] 2021-11-04 12:13
> This should be closed with the new method of calling up the keepassxc generator directly in 2.7.0

Thanks mate, would you have any idea when that's expected to release? I understand I could get it now in a CI build but they also warn of data loss so perhaps I'd best wait... Depending on how long that wait might be :)

**Comment by varjolintu** [comment] 2021-11-04 14:03
> > This should be closed with the new method of calling up the keepassxc generator directly in 2.7.0
> 
> Thanks mate, would you have any idea when that's expected to release? I understand I could get it now in a CI build but they also warn of data loss so perhaps I'd best wait... Depending on how long that wait might be :)

If everything goes fine, the release will be in this month.

**Comment by xcasxcursex** [comment] 2022-03-18 17:19
Gave the RC a try and 
![image](https://user-images.githubusercontent.com/58130821/159051799-52b59973-90c4-4615-9749-0cb5c34e9738.png)

I feel like this might not be the right place to report it though? Any advice appreciated.

**Comment by varjolintu** [comment] 2022-03-18 17:28
@xcasxcursex Your database must be open, and connected to the extension of course.

**Comment by xcasxcursex** [comment] 2022-03-19 00:31
It is, and working in every way except for the password generator. 

To work around this, I've used the generator in-app, and copypasted into the browser, and the addon detected a new account and created it in my database. It's definitely all connected and working, except the pw gen.

**Comment by varjolintu** [comment] 2022-03-19 08:05
@xcasxcursex The development version of the extension already works. We need the release the update soon after KeePassXC release.

**Comment by xcasxcursex** [comment] 2022-03-19 08:29
So the error I posted above is normal until both the final release of keepassxc and the subsequent updating of this addon?

**Comment by varjolintu** [comment] 2022-03-19 08:32
@xcasxcursex Yes. The new extension version will support older KeePassXC releases, but sadly this does not work another way around.

**Comment by xcasxcursex** [comment] 2022-04-05 00:33
> @xcasxcursex The development version of the extension already works. We need the release the update soon after KeePassXC release.

It's been a couple of years, I've run out of shame, so this is the part where I e-beg ;)
Happy to help with this if you need it.

**Comment by varjolintu** [comment] 2022-04-05 04:28
> > @xcasxcursex The development version of the extension already works. We need the release the update soon after KeePassXC release.
> 
> It's been a couple of years, I've run out of shame, so this is the part where I e-beg ;) Happy to help with this if you need it.

E-beg is a new word for me :) We're getting there. KeePassXC 2.7.0 (and 2.7.1) have been taking time for reviewing extension PR's.

**Comment by xcasxcursex** [comment] 2022-04-05 05:53
Thanks mate. I don't want to rush it, obviously this is one of those apps where some 'carefulling' is appropriate.

**Comment by xcasxcursex** [comment] 2022-04-10 15:59
Fixed as of https://github.com/keepassxreboot/keepassxc-browser/releases/tag/1.7.12 Thanks mate!
