### ISSUE TITLE
Fields are not detected anymore with keepassxc 2.3.4

### ISSUE THREAD

**Issue by hyviquel** [keepassxreboot/keepassxc-browser#278] opened 2018-08-27 09:03 UTC
## Expected Behavior
Automatic completion of credential fields for existing entry in keepassxc

## Current Behavior
Credential are not found since the last update of keepassxc (2.3.4)

## Possible Solution
This is working again when rolling back to keepassxc 2.3.3

## Steps to Reproduce (for bugs)
1. Update keepassxc to 2.3.4
2. Go to a website that you already added the credentials
3. Try to detect the fields

## Debug info
KeePassXC - 2.3.4
keepassxc-browser - 1.2.0
Operating system: Linux (Ubuntu 18.04)
Browser: Tested with Chrome/Firefox//Chromium
Proxy used: NO

```Error 15: Aucun identifiant trouvé keepass.js:976:5```

**Comment by hyviquel** [comment] 2018-08-27 09:04
Corresponding keepassxc issue: https://github.com/keepassxreboot/keepassxc/issues/2236

**Comment by varjolintu** [comment] 2018-08-27 09:34
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/275.

**Closed by varjolintu** 2018-08-27 09:34 UTC
Labels: duplicate
