### ISSUE TITLE
Can we have monochrome icons in the web integration like in the default app?

### ISSUE THREAD

**Issue by Vakke** [keepassxreboot/keepassxc-browser#1475] opened 2021-11-24 11:54 UTC
Hello!

Just making a request that would we be able to have a similar possibility to have monochrome icons like in the deafult app in Windows? 

Preferably all possible icons in monochrome, meaning the top bar addon icon and icons which appear next to the login fields.
## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.10.1
Operating system: Win64
Browser: Mozilla Firefox 95.0

**Comment by varjolintu** [comment] 2021-11-24 12:01
Duplicate of #465.

**Closed by varjolintu** 2021-11-24 12:01 UTC
Labels: duplicate
