### ISSUE TITLE
After unlocking the database from the extension, the password doesn't get filled in

### ISSUE THREAD

**Issue by hkockerbeck** [keepassxreboot/keepassxc-browser#1826] opened 2023-01-15 12:43 UTC
## Expected Behavior
I would like the extension to properly fill in the credentials, regardless whether the database had to be unlocked beforehand or not.

## Current Behavior
When the database was already unlocked before filling in the credentials via the extension, everything works as expected. When the database was locked and gets unlocked before filling in the credentials, only the username gets filled in, but not the password.

## Steps to Reproduce (for bugs)
1. On a login page of a website, click on the icon the extension adds to the user name field to fill in the credentials.
2. Because the database is currently locked, KeePassXC's main window gets focused, so the database can be unlocked by typing in the master password.
3. After unlocking the database, the user name field gets filled out properly, but the password field doesn't.
4. The website answers with "Wrong credentials" or similar, because of the missing password.
5. Click on the icon in the user name field again, while the database is still unlocked. 
6. Both the user name field and the password field get filled out properly, the login is successful.

I've seen this happen on several different, unrelated websites. If I had to guess, my gut feeling would be that it could be related to [issue 1817](https://github.com/keepassxreboot/keepassxc-browser/issues/1817), because there the locked/unlocked state of the database seems relevant as well.

## Debug info
No console messages or other error messages that I'm aware of.

KeePassXC - 2.7.4 Revision: 63b2394
KeePassXC-Browser - 1.8.4
Operating system: Ubuntu Linux 22.04 LTS
Browser: Firefox 109.0

**Comment by HDInfautre** [comment] 2023-01-18 17:32
Hello
You closed my thread ( https://github.com/keepassxreboot/keepassxc-browser/issues/1828 ) and I don't know if you read my reply?
I think the problem is more with the new Firefox v109 version like this thread.
See https://blog.mozilla.org/en/products/firefox/extensions-addons/heres-whats-going-on-in-the-world-of-extensions/ ?
Can you confirm this or reopen my thread?

**Comment by varjolintu** [comment] 2023-01-18 17:38
@HDInfautre Please don't spam issues to another threads. You can still reply to the original thread even if it's closed. I'm just pretty sure it's something related to Snap, and that's Ubuntu's problem.

**Comment by varjolintu** [comment] 2023-01-23 17:22
I haven't been able to reproduce this. Are you able to try the current `develop` branch version and see if the issue is already fixed?

**Comment by hkockerbeck** [comment] 2023-01-23 18:25
Ok, that's... interesting. I tried the current develop branch, and it showed the same behaviour as described above. Then I switched back to the "regular" extension, and it prompted me to re-configure the connection to KeePassXC. I did that, and the extension now does fill out the password field properly. So I'd guess the problem was a messed up / outdated / ... connection between the extension and KeePassXC?

Something else I noticed: Previously filling in the credentials with the extension included pressing the "Submit" button, so to speak. It doesn't do that anymore. Only the username and password fields are filled in, I have to click on "Submit" myself.

**Comment by varjolintu** [comment] 2023-01-23 18:30
Maybe there was something strange with the connection, maybe perhaps a browser update? Sometimes it needs to restart the connection.

The Auto-Submit got disabled by itself?

**Comment by hkockerbeck** [comment] 2023-01-23 18:32
> The Auto-Submit got disabled by itself?

To the best of my knowledge, yes. I assumed that to be a default behaviour that maybe was introduced not too long ago, so the new connection would be showing this default.

**Comment by varjolintu** [comment] 2023-03-01 06:24
This is probably fixed with: #1856. Let's reopen this if the problem still occurs.

**Closed by varjolintu** 2023-03-01 06:24 UTC
Labels: more info needed
