### ISSUE TITLE
Keepassxc browser integration doesn't work for Firefox snap with Keepassxc flatpak/snap

### ISSUE THREAD

**Issue by Leokap** [keepassxreboot/keepassxc-browser#1879] opened 2023-03-10 14:56 UTC
## Overview
I had the normal .deb package installed, *which worked*, saw that it is outdated (2.6.6) removed it and tried both flatpak and snap versions (2.7.4)
(In both versions under settings > Browser integration it says: “Browsers installed as snaps are currently not supported.” But since several other issues with the same problem had been marked resolved in this repo by now and firefox-snap does now support native messaging, I assume that is outdated. (please remove that line in the config))

## Steps to Reproduce
1. (maybe install and configure .deb package first)
2. (remove the deb package and the connection in the settings page of the addon)
3. install snap or flatpak version
4. in the snap case, run the helper script.
5. follow [that guide](https://keepassxc.org/docs/KeePassXC_GettingStarted.html#_setup_browser_integration) until step 5

## Expected Behavior
It should connect as it did in the .deb case.

## Actual Behavior
Now it says in the pop up: "No se puede conectar a KeePassXC. Compruebe que la integración del navegador esté habilitada en la configuración de KeePassXC."
Translation: "Unable to connect to KeePassXC. Check that browser integration is enabled in the KeePassXC configuration."
(It is for firefox)
I also tested with a new Firefox profile and can confirm that the .json files have been written in both cases. Flatpak's example:
`/home/leo/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json`:
```
{
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/var/lib/flatpak/exports/bin/org.keepassxc.KeePassXC",
    "type": "stdio"
}
```
I have accepted the web extensions permission for Firefox once during .deb version setup.

EDIT: If I restart the browser with the original profile and have keepassxc locked the keepass (flatpak) pops up to get unlocked. Afterwords in the addon's pop up it says something like the authorization was unsuccessful and after a reload shows the same text as above.

## Context
since I tested with a new Firefox profile and am only reusing the password database, I don't think the previously installed .deb package can have any influence.

Flatpak example:
KeePassXC - Version 2.7.4
Revision: 63b2394
Distribution: Flatpak

Qt 5.15.8
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 6.1.0-1007-oem

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

error information from addon:
KeePassXC - unknown
KeePassXC-Browser - 1.8.5.1
Operating system: Linux x86_64
Browser: Mozilla Firefox 110.0

Operating System: Linux
Desktop Env: KDE
Windowing System: Wayland

**Comment by varjolintu** [comment] 2023-03-10 16:27
Duplicate of #1875 and #1828.

**Comment by varjolintu** [comment] 2023-03-10 16:28
Use the PPA?

**Closed by varjolintu** 2023-03-10 16:27 UTC
Labels: bug
