### ISSUE TITLE
Octoprint UI is blocked from loading wenn Chrome extension is installed

### ISSUE THREAD

**Issue by sschueller** [keepassxreboot/keepassxc-browser#962] opened 2020-08-03 06:49 UTC
The Chrome extension blocks the Octoprint UI from loading. I have made the corresponding issue at Octoprint as well: https://github.com/OctoPrint/OctoPrint/issues/3670

## Expected Behavior
Page should load

## Current Behavior

Page freezes, browser complains of hanging page

## Possible Solution
Remove extension and it works fine

## Steps to Reproduce (for bugs)

1. Browse to your OctoPrint Instance
2. Page gets stuck at loading UI
3. Doesn't matter if extension is configured or connected. Problem persists.

## Debug info

KeePassXC - 2.6.0
KeePassXC-Browser - 1.6.6
Operating system: Mac/Win
Browser: Chrome
OSX: 10.15.5 (19F101)
Chrome Version 84.0.4147.89 (Official Build) (64-bit)
Also happens on:
Windows 10
Chrome Version 84.0.4147.105 (Official Build) (64-bit)

**Comment by varjolintu** [comment] 2020-08-03 06:54
Duplicate of #944.

**Closed by varjolintu** 2020-08-03 06:54 UTC
