### ISSUE TITLE
Cannot save or update password from browser / instructions needed

### ISSUE THREAD

**Issue by sylvainfaivre** [keepassxreboot/keepassxc-browser#214] opened 2018-06-21 15:13 UTC
Using KeePassXC-Browser 1.1.7.
I looked everywhere and could not find instructions about saving or updating passwords from the browser.
According to some stuff I found in previous bug reports, the KeePassXC-Browser icon should flash red after creating or updating a login on a website, but it doesn't, it stays green.
## Expected Behavior
Can save an entry through the browser extension without having to type it manually in KeepassXC.
## Current Behavior
When I create a new account on a website, for example imgur.com, the KeePassXC-Browser icon stays green and does not allow me to save the credentials.
When I change a password on a website for which my credentials are saved in KeepassXC, the KeePassXC-Browser icon stays green and does not allow me to update the credentials.

## Steps to Reproduce (for bugs)
1. load imgur.com
2. click "sign up"
3. fill the form and submit it

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-23-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

## Firefox Addon settings
Blink Time: 20000
Redirect Offset: 10000
Redirect Allowance: 5
Y Activate password generator.
Y Automatically retrieve credentials.
N Automatically fill-in single credentials entry.
Y Activate autocomplete for username fields.
Y Show notifications.
Y Show a notification when new credentials can be saved to the database.
Y Save domain only.

**Comment by varjolintu** [comment] 2018-06-21 15:23
Duplicate of #184 and maybe #211.

Try the following solution as a workaround: https://github.com/keepassxreboot/keepassxc-browser/issues/184#issuecomment-397826042

**Closed by varjolintu** 2018-06-21 15:23 UTC

**Comment by sylvainfaivre** [comment] 2018-06-22 09:38
Sorry I forgot to add that I read these 2 reports.
I added a site to the ignore list but it changed nothing.
Also I have Firefox 60.0.2 and not nightly.

**Comment by varjolintu** [comment] 2018-06-22 10:09
Can you try to debug the extension and see if there's any error messages? In this case the content script matters, so go to the page where the error happens, right-click on mouse and select Inspect from the context menu.
