### ISSUE TITLE
When creating a new entry, optionally use the website title for the Title

### ISSUE THREAD

**Issue by stdedos** [keepassxreboot/keepassxc-browser#2208] opened 2024-05-28 09:22 UTC
## Expected Behavior

When creating a new entry, optionally use the website title for the Title

## Current Behavior

When creating a new entry, Title is website url (`localhost` for localhost urls)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

https://github.com/keepassxreboot/keepassxc-browser/issues?q=is%3Aissue+create+entry+website+title

**Comment by varjolintu** [comment] 2024-05-28 09:35
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/662

**Closed by varjolintu** 2024-05-28 09:35 UTC
