### ISSUE TITLE
High CPU usage on Firefox 74.0

### ISSUE THREAD

**Issue by pescepalla** [keepassxreboot/keepassxc-browser#835] opened 2020-03-30 17:02 UTC
## Expected Behavior

The KPXC plugin should have a negligible impact on the performance of Firefox 74.

## Current Behavior

KPXC-Browser on some pages (e.g. etherpad) constantly increases its processor usage until FF74 grinds to a halt. This can be verified through the about:performance page

## Steps to Reproduce (for bugs)

1. Have FF74 with the latest version of the KPXC-B
2. Keep FF's about:performance tab open
3. Create a document on e.g. etherpad.devol.it and type on it for a while
4. See the plugin's "Energy impact" stat increasing more and more and making the browser unusable until a) a while after stopped typing or b) the plugin has been disabled.

## Debug info

KeePassXC - 2.5.3
KeePassXC-Browser - 1.6.2
Operating system: Arch Linux
Browser: Firefox

![Screenshot_2020-03-30_19-00-38](https://user-images.githubusercontent.com/46329185/77940318-d1585f00-72b8-11ea-91a9-421d1b94dd63.png)

**Comment by varjolintu** [comment] 2020-03-30 17:03
Thanks. I'll check this ASAP.

**Comment by bwbroersma** [comment] 2020-03-30 18:05
It is giving me problems too, but mainly on pages with (I think) DOM changes, e.g. some web chat apps.
![image](https://user-images.githubusercontent.com/4252918/77944145-b7217f80-72be-11ea-9cd2-179be5b82846.png)

It would be great to debounce the MutationObserver (not done ATM?):
https://github.com/keepassxreboot/keepassxc-browser/blob/11472925eef4575ac2b46293e2bcf728a53aa2dd/keepassxc-browser/content/keepassxc-browser.js#L823-L835

I had some issues with the blacklist of some sites but got it working now. Maybe the procedure is not clear in the documentation / settings.

It will work it you go to Settings (moz-extension://640677b3-c40c-42bc-9ebc-57eb5ab7e849/options/options.html#site-preferences) -> Site Preferences (would be nice if the deep-linking would work) -> Add URL manually -> type in the site -> Add, Ignore: Disable all features, now reload all the tabs that had this site/url open.

**Comment by varjolintu** [comment] 2020-03-30 18:10
@bwbroersma Debouncing would definitely help. For this issue I made a PR that ignores any changes made directly to the main HTML element. This particular Etherpad page made constant alterations to the main HTML element via scripts, and that's just non-useful info for the extension.

**Comment by bwbroersma** [comment] 2020-03-30 18:42
I wonder if my chat app problems are also solved by this. I also had some issues with disabling a specific site (you need to add `/*` at the end of the URL to get it matched because of the `$` in `matchPatternToRegExp`:
https://github.com/keepassxreboot/keepassxc-browser/blob/11472925eef4575ac2b46293e2bcf728a53aa2dd/keepassxc-browser/global.js#L96-L98

**Comment by varjolintu** [comment] 2020-03-30 18:53
@bwbroersma You can download the branch and load it temporarily to your browser (just disable the stable installed version before testing).

**Comment by baldurmen** [comment] 2020-04-01 23:14
I don't know how helpful it is, but I get the same message when using [Glowing Bear](https://www.glowing-bear.org/), when it loads a bunch of messages from an IRC channel.

**Comment by varjolintu** [comment] 2020-04-02 04:59
@baldurmen I'll test that one too.

**Comment by varjolintu** [comment] 2020-04-02 05:54
@baldurmen I didn't see any big issues with Glowing Bear, but I suggest you try the branch yourself and see if the fix works for you.

**Comment by baldurmen** [comment] 2020-04-03 00:50
@varjolintu I've loaded the branch and I can confirm:

1. Keepass still works properly ;)
2. it seems to fix the problem I'm seeing

Cheers!

**Comment by varjolintu** [comment] 2020-04-03 04:30
@baldurmen Excellent! Thank you for testing the fix.

**Comment by brndd** [comment] 2020-04-05 04:40
I get this issue on Wikipedia revision history pages with lots of entries, when clicking on the radio buttons to select two revisions to compare the diff between them. For instance [this page](https://en.wikipedia.org/w/index.php?title=The_Bye_Bye_Man&offset=&limit=500&action=history).

**Comment by pklapperich** [comment] 2020-04-08 21:21
I've tried the branch in Firefox using `web-ext`, and it doesn't solve the issue on the wikipedia page @brndd linked to.

**Comment by varjolintu** [comment] 2020-04-09 05:37
@pklapperich I'll see what I can do. The fix for this is not finished yet.

**Comment by varjolintu** [comment] 2020-04-09 06:38
@pklapperich Please re-try the branch.

**Comment by pklapperich** [comment] 2020-04-10 01:24
@varjolintu that fixed it for the Wikipedia example and also the self-hosted commercial timesheet software my workplace uses! I compared `htop` while using Firefox with/without the extension enabled and don't notice any difference.

**Closed** 2020-04-18 14:32 UTC
Labels: PR pending, bug

**Comment by zzenonn** [comment] 2020-06-24 03:57
I still get this, particularly with Google Docs.

**Comment by varjolintu** [comment] 2020-06-24 05:03
@zzenonn We are already tracking this issue here: https://github.com/keepassxreboot/keepassxc-browser/issues/888
