### ISSUE TITLE
Wrong Entry for wrong URL?!?

### ISSUE THREAD

**Issue by superwinni2** [keepassxreboot/keepassxc-browser#705] opened 2019-12-05 14:37 UTC
Litlle bit more info for my problem:
My Pinter got the IP 10.100.100.108
My Switch got the IP 10.0.100.108
Both got a http interface.

I havn't got any entry for my printer. 
I've got one entry for my Switch.
 -> Title: Switch
 -> Username: admin
 -> Password: secret
 -> URL: http://10.0.100.108
Not more, not less.

## Expected Behavior
It shouldn't be showing the wrong data.

## Current Behavior
When I want to login into my Printer, KeePass shows me the Entry for my switch?!? 

## Steps to Reproduce (for bugs)
Maybe create the same szenario...? 

## Debug info
KeePassXC - 2.5.1
KeePassXC-Browser - 1.5.3
Operating system: Windowns 7
Browser: Chrome

**Comment by varjolintu** [comment] 2019-12-05 14:45
Duplicate of #686. The same bug causes KeePassXC to return false entries if you have one or more invalid URL's in your entries.

**Closed by varjolintu** 2019-12-05 14:45 UTC
