### ISSUE TITLE
Reopen database doesn't show KeePassXC window in foreground

### ISSUE THREAD

**Issue by NN---** [keepassxreboot/keepassxc-browser#235] opened 2018-07-23 11:28 UTC
After database is locked, click on Reopen database shows KeePassXC window in background and not in foreground.

## Expected Behavior
KeePassXC in foreground.

## Current Behavior
KeePassXC in background flashing in taskbar.

**Comment by varjolintu** [comment] 2018-07-23 12:00
Please give some details about the KeePassXC and KeePassXC-Browser versions you are using, including your operating system. Thanks.

**Comment by NN---** [comment] 2018-07-23 13:39
OS: Windows 10x64
Browser: Firefox 61 x64
KeePassXC: 2.3.3
KeePassXC-Browser: 1.1.7  (https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/)

**Comment by varjolintu** [comment] 2018-07-25 06:38
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/1643.

**Closed by varjolintu** 2018-07-25 06:38 UTC
Labels: bug, platform: Windows, user experience
