### ISSUE TITLE
Browser extension does not ask to user to search for credentials, appears to do nothing

### ISSUE THREAD

**Issue by tonydiep** [keepassxreboot/keepassxc-browser#1867] opened 2023-02-28 03:56 UTC
## Overview

When using Chrome or Firefox in Linux to login, KeepassXC extension appears to do nothing, does not ask user to search for correct entry

## Steps to Reproduce

1.Go to a site to login 
2. Click Keepass icon
3. Nothing happens

## Expected Behavior
After clicking icon, if Keepass does not have an entry for the URL:
 then Keepass asks user to search and then associates URL with entry.
 if no entry is found then Keepass associates URL with and saves username and password when the user logs in

## Actual Behavior
Keepass does not do anything, shows no error, shows no prompt. Appears broken.

## Context
Other Keepass clients ask the user to search if the the entry can't be found and then save the URL association.

Keepass 2.7.4
Linux
Gnome
Wayland
Chrome, Firefox

**Comment by varjolintu** [comment] 2023-02-28 05:15
Probably a duplicate of the pinned issue: https://github.com/keepassxreboot/keepassxc-browser/issues/1426

Please check the proper settings if you are using a Snap based browser.

**Closed by varjolintu** 2023-02-28 05:15 UTC
Labels: bug, duplicate

**Comment by tonydiep** [comment] 2023-02-28 13:18
It is not a duplicate because:
1. It happens on Chrome as well as Firefox, and
2. Neither the installed Chrome or Firefox are the Snap versions.

**Comment by varjolintu** [comment] 2023-02-28 13:20
You did not provide that information in the original message. Also, you haven't mentioned how KeePassXC is installed in your system, or what is your distro.

Please go through this guide and report your findings:
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

**Comment by droidmonkey** [comment] 2023-02-28 13:48
Some of the original message is warranted, we really don't do a good job of notifying the end user that they "need to do something" to get credentials to populate. We do that already when the database is not connected, but once connected if no credentials are found we are silent even after the user tries to fill in multiple times.

**Comment by varjolintu** [comment] 2023-02-28 14:37
>     3. The extension does fill in when he URL matches

Wait.. it fills correctly? So are you expecting that if no credentials are found, the extension should provide a way to search all credentials in your database?

**Comment by tonydiep** [comment] 2023-02-28 14:43
That's what my other keepass apps do and that's what I said in the issue.

- Tony Diep

________________________________
