### ISSUE TITLE
v1.1.6 auto-fill broken on sites that work in v1.1.3

### ISSUE THREAD

**Issue by jlindgren90** [keepassxreboot/keepassxc-browser#201] opened 2018-06-13 00:05 UTC
## Expected Behavior
Auto-fill should auto-fill name and password fields.

## Current Behavior
Auto-fill doesn't auto-fill name and password fields.
For an example, try https://www.facebook.com.

## Possible Solution
Revert to the auto-fill behavior of v1.1.3.

## Steps to Reproduce (for bugs)
1. Load https://www.facebook.com.

## Debug info
KeePassXC - 2.3.3 (irrelevant)
keepassxc-browser - 1.1.6
Operating system: Linux
Browser: Firefox
Proxy used: Don't know

**Comment by droidmonkey** [comment] 2018-06-13 03:12
Duplicate of #200

**Closed by droidmonkey** 2018-06-13 03:12 UTC
