### ISSUE TITLE
password generation rules change in popup window

### ISSUE THREAD

**Issue by Novite5** [keepassxreboot/keepassxc-browser#225] opened 2018-07-06 15:48 UTC
## Expected Behavior

Could you in addon's password generation popup window add the rule options?
like the in software:
![grafik](https://user-images.githubusercontent.com/16817335/42387271-6353fbe0-8174-11e8-969f-13d60b5e82d5.png)
Because many sites don't allow all the types of characters as passwords.

## Current Behavior

Now in the popup window, there is no option for the rule.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - {VERSION}
keepassxc-browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium
Proxy used: YES/NO

**Comment by varjolintu** [comment] 2018-07-08 06:09
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/82.

**Closed by varjolintu** 2018-07-08 06:09 UTC
Labels: duplicate, feature request
