### ISSUE TITLE
Credentials should be auto-filled after unlocking a locked database

### ISSUE THREAD

**Issue by normanr** [keepassxreboot/keepassxc-browser#1123] opened 2020-11-25 20:38 UTC
## Expected Behavior
When the database is locked then clicking the username icon will trigger unlock. I expect the username and password to be filled in after the database is unlocked.

## Current Behavior
When the database is locked then clicking the username icon will trigger unlock. I then have to click the username icon again to get the username and password to be filled in.

## Possible Solution
The unlock flow should wait for the database to unlock, and then trigger the fill-in logic. Can it detect if the unlock fails/is aborted? If not then it'll have to have a sensible timeout (eg: 30 seconds).

## Steps to Reproduce (for bugs)
1. Lock database
2. Visit page asking for credentials
3. Click username icon
4. Unlock database
5. Click username icon again (this is the step that this feature request is asking to be removed).
6. Click login

## Debug info
KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.3
Operating system: Linux x86_64
Browser: Chrome-Beta 87.0.4280.66

**Comment by varjolintu** [comment] 2020-11-25 20:43
I use this feature quite often, and for me it never fails to fill the credentials after unlock. Currently it has no timeout, but the flow could probably be improved. If I could reproduce the problem, that is.

**Comment by normanr** [comment] 2020-11-25 20:50
Hmm, which operating system and browser do you generally use? I wonder if that's a difference.

**Comment by varjolintu** [comment] 2020-11-25 20:53
Firefox with Linux and macOS. But I also test everything with Chromium-based browsers, of course.

**Comment by normanr** [comment] 2020-11-25 23:02
Hmm, interesting. I'm using Chrome Beta so I had to enable "Use a custom browser configuration location" and provide `/home/normanr/.config/google-chrome-beta/NativeMessagingHosts` in KeePassXC to get the Browser integration to work. I'd be surprised if that affected this though. Let me try and grab some debug logs.

**Comment by varjolintu** [comment] 2020-11-26 06:25
We don't officially support any Beta of Develop releases because these often have some changes to their JavaScript API's that won't be in the stable build. So any bugs or glitches with these releases are out of our scope.

**Comment by varjolintu** [comment] 2020-12-14 06:34
So, if you cannot reproduce this with stable Chrome, please close the issue.

**Closed** 2021-01-09 07:02 UTC
Labels: bug

**Comment by normanr** [comment] 2021-01-10 19:36
I re-tested, and I can't reproduce. Both Chrome and the extension were upgraded since, so maybe that fixed it.

KeePassXC - 2.6.2 (same as the initial report)
KeePassXC-Browser - 1.7.4 (newer)
Operating system: Linux x86_64
Browser: Chrome/Chromium 88.0.4324.79 (newer)
