### ISSUE TITLE
100% CPU usage in both Firefox and Chrome on specific page

### ISSUE THREAD

**Issue by ergo** [keepassxreboot/keepassxc-browser#923] opened 2020-07-03 09:38 UTC
## Expected Behavior
Normal cpu usage expected on login page.

## Current Behavior
Constant 100% CPU in the tab in both Firefox and Chrome during password screen.

## Steps to Reproduce (for bugs)

Visit: https://system.aliorbank.pl/sign-in
using login 8141111111

## Debug info
KeePassXC - 2.5.4
KeePassXC-Browser - 1.6.4
Operating system: Linux x86_64
Browser: Mozilla Firefox 78.0.1 (64-bit)

**Comment by varjolintu** [comment] 2020-07-03 09:49
Duplicate of #888.

**Closed by varjolintu** 2020-07-03 09:49 UTC
