### ISSUE TITLE
Autofill prevents entering different passwords on the same base URL (on Nextcloud shared folders)

### ISSUE THREAD

**Issue by phipsgabler** [keepassxreboot/keepassxc-browser#1357] opened 2021-06-22 13:06 UTC
Autofill forces you to enter the password for the base URL on password forms starting with the same URL, because typing Enter fills out the account password, instead of submitting a different, pasted password.

## Possible Solution

Add an option to disable the autofill on the current page, or something else to override capturing the Enter key.

## Steps to Reproduce (for bugs)

I discovered this using a Nextcloud shared folder, so:

1. Store your Nextcloud login in KeepassXC and activate autofill for the base URL. (If you don't have any Nextcloud account, you could create a test account [here](https://try.nextcloud.com/).)
2. [Share a folder](https://nextcloud.com/blog/sharing-in-nextcloud/) with password protection.
3. Visit the share URL of that folder (which has the same base URL as the login field).
4. If you paste the share password, the only option to submit is pressing Enter, which however fills in the account password.  You cannot submit the share password.

[Here's](https://demo2.nextcloud.com/index.php/s/CEyWJ6x9sA3AH3p) a temporary share I created for you to look at the form, but that's only valid for 60 minutes... this is the form:

```html
<p>
	<label for="password" class="infield">Password</label>
	<input type="hidden" name="requesttoken" value="ixvJMxkq1rsWGjNbL/cWJqQs5XCIkaBJ74/kz39Osbc=:v3S4GFJb7uNebEpjRLlTUeMalRXx1OZ5g8fRuRgMxuA=">
	<input type="password" name="password" id="password" placeholder="Password" value="" autocomplete="new-password" autocapitalize="none" autocorrect="off" autofocus="">
	<input type="hidden" name="sharingToken" value="CEyWJ6x9sA3AH3p" id="sharingToken">
	<input type="submit" id="password-submit" class="svg icon-confirm input-button-inline" value="" disabled="">
</p>
```

## Debug info

KeePassXC - 2.4.3
KeePassXC-Browser - 1.7.8.1
Operating system: Ubuntu
Browser: Firefox 89.0.1

**Comment by varjolintu** [comment] 2021-06-22 15:59
Pressing Esc before Enter doesn't help?

**Comment by phipsgabler** [comment] 2021-06-23 06:47
@varjolintu It indeed does, thanks! But I wouldn't have thought of it...  So this issue becomes a suggestion for making that clearer in the UI.

**Comment by varjolintu** [comment] 2021-06-23 13:43
Without Enter the Autocomplete Menu is probably visible? The first entry is active by default, so pressing Enter selects it. Esc closes the menu and then you can enter a password manually.

**Comment by phipsgabler** [comment] 2021-06-24 06:38
Ah, yes, it's there as soon as I paste text.  Then the confusion is that while the first is "active", I didn't realize this, as there is only one row.  And there is no way to get rid of that by only using the mouse.

**Comment by varjolintu** [comment] 2021-06-24 12:14
Hmm. Gotta investigate if there's possibility to detect the paste and disable the menu for that kind of situations.

**Comment by varjolintu** [comment] 2023-07-19 05:33
Closing this because I cannot reproduce the issue anymore.

**Closed by varjolintu** 2023-07-19 05:33 UTC
Labels: bug
