### ISSUE TITLE
Automatic reconnect when using the username input icon

### ISSUE THREAD

**Issue by bllngr** [keepassxreboot/keepassxc-browser#650] opened 2019-10-24 13:23 UTC
## Expected Behavior
When using the username field icon with no active connection, a connection is automatically established in the background if possible, and the input fields are filled afterwards. Only a single click is required.

## Current Behavior
Currently, an error message is shown, and the connection needs to be (re-) established manually using the browser extension toolbar icon, and only then can the icon be used. Sometimes, I even have to reload the page. Three or even four manual steps are required.

![keepassxc-browser-extension](https://user-images.githubusercontent.com/303458/67489401-cea26f80-f671-11e9-87dc-47976ad86f6a.gif)

## Debug info

KeePassXC-Browser Version: 1.5.3
KeePassXC Version: 2.4.3 
Operating system: Windows/Linux
Browser: Firefox
"Automatically reconnect to KeePassXC (experimental)" is **enabled**.

**Comment by varjolintu** [comment] 2019-10-24 13:28
So.. automatic reconnect is enabled but you still made the reconnect manually in the video?

**Comment by bllngr** [comment] 2019-10-24 13:51
Yes, I needed to. I'm not sure what the options is supposed to do, but it doesn't work for me in those cases. I always need to manually reconnect.

If it it supposed to work like that, it seems like it there's a bug for my specific setup. If you need any additional information, please don't hesitate to ask!

**Comment by varjolintu** [comment] 2019-10-24 13:56
With the automatic reconnect enabled, you shouldn't even see the popup message for reloading. Could you debug the extension via `about:debugging` and see what the console log shows?

**Comment by bllngr** [comment] 2019-10-24 14:20
Here's the console log:
```
Error 1: Database not opened keepass.js:1060:13
Error: No content script available for this tab. keepass.js:1178:25
Failed to connect: Unknown error keepass.js:947:13
Error: No content script available for this tab. keepass.js:1178:25
Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. 3 keepass.js:1060:13
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:977:13
Server public key: 8y49X8AbP4xyZpiAlU/YmpW/ordNf5W+ywrQMLHxtEY= keepass.js:606:17
```

I figured out how to reproduce the issue. The key point is to close KeepassXC once the connection has been established successfully. Once it's closed, the connection cannot be reestablished again. But it still can be reestablished manually. This is the second try in the log above,

**Comment by varjolintu** [comment] 2019-10-24 14:23
Well that sounds strange. I'll check if I can reproduce it. There has been a lot of fixes for the connection issues lately, so it's possible that something is still broken.

**Comment by Bruceforce** [comment] 2019-11-20 17:00
FYI I have the same issue (also seeing the reload page button despite "auto reconnect" is enabled) in Chrome.

The log just says `Error 7: Die Nachrichtenverschlüsselung ist fehlgeschlagen. Läuft KeePassXC?` This is not only the case after closing KeePassXC but also after doing the following:

1. restart windows
1. open chrome
1. open KeePassXC

**Comment by bllngr** [comment] 2019-12-03 07:46
I've since tested it again in multiple, heterogeneous environments, and found the following:

1. For me, it only happens on Windows. On all my Linux machines, it works without issues.
2. On all Windows machines that are affected, the user is running unprivileged.
3. It happens with "Update native messaging files at startup" both enabled and disabled.

I didn't yet test whether using a proxy application affects the bug. I'm always using a proxy application, thus I'm not sure if it's worth it checking it out.

**Comment by varjolintu** [comment] 2019-12-03 07:54
@bllngr Thanks for the info. I must do some more tests with Windows.

**Comment by lucascosti** [comment] 2020-02-09 06:34
+1 for this. 

I use KeePassXC with Firefox on a Mac and Windows 10.

On the Mac, the browser extension automatically connects to KeePassXC. For Windows, I have to manually press `Reload` in the browser extension for it to connect.

Both have the `Automatically reconnect to KeePassXC` setting enabled.

Windows environment:
Firefox 72.0.2
Windows 10 Pro (1909)
KeePassXC Version: 2.5.3
KeePassXC-Browser Version: 1.5.4

**Comment by Gedankenleser** [comment] 2020-03-03 19:23
Same here.

**Comment by bllngr** [comment] 2020-03-12 08:24
@varjolintu, have you been able to reproduce the issue? Is there anything we can help you with?

**Comment by lucascosti** [comment] 2020-03-12 08:29
To add a little bit more info: I have noticed that this currently happens only for the first unlock of the KeePass database after KeePassXC is opened. When the database is locked and unlocked after that (without closing KeePassXC), it does seem to reconnect automatically.

On MacOS it picks up situations both automatically.

**Comment by varjolintu** [comment] 2020-03-12 09:43
@bllngr I haven't had time to look at it. I'll try to fix this before the next release.

**Comment by varjolintu** [comment] 2020-03-24 06:58
I just tested this with Linux and Windows using Firefox and I couldn't reproduce the issue.

If the automatic reconnect is enabled, and I restart KeePassXC, the icon and popup are functional right away. If I don't open the database, clicking the icon asks for unlocking the database as it's already connected.

**Comment by bllngr** [comment] 2020-03-24 07:03
That's unfortunate. :( Did you test it with both Proxy application and without? Maybe we can help with some (verbose) logging information?

**Comment by varjolintu** [comment] 2020-03-24 07:12
@bllngr I tested with the proxy application because that's the default behavior. The only thing that could help here is to debug the extension's background script file `keepass.js`. Basically anyone could add some extra `console.log()` messages to https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/background/keepass.js#L1133 and see where it returns etc. Using breakpoints can be tricky because that function is called repeatedly.

**Comment by alex-the-man** [comment] 2020-03-29 10:23
Hi, I think I've root caused the issue. On Windows, if we start Chrome before starting KeePassXC, when `keepass.enableAutomaticReconnect()` is called, since KeePassXC isn't running, `keepass.currentKeePassXC` doesn't contain the KeePassXC version and is "".

In `keepass.enableAutomaticReconnect()`, there's a Windows specific version check, it will fail & the function won't set the timer.
```
    if (!page.settings.autoReconnect
        || (navigator.platform.toLowerCase().includes('win') && !keepass.compareVersion('2.3.4', keepass.currentKeePassXC))) {
        return;
    }
```
`keepass.compareVersion('2.3.4', keepass.currentKeePassXC))` this check will fail and we do this only on Windows.

If we start KeePassXC before starting Chrome, you won't hit the issue.
One quick way to fix this is to move the version check inside the reconnectLoop:
```
    if (keepass.reconnectLoop === null) {
        keepass.reconnectLoop = setInterval(async () => {
            if (!keepass.isKeePassXCAvailable) {
                if (navigator.platform.toLowerCase().includes('win') && !keepass.compareVersion('2.3.4', keepass.currentKeePassXC)) return;
                keepass.reconnect();
            }
        }, 1000);
    }
```

**Comment by varjolintu** [comment] 2020-03-29 10:25
@alex-the-man Nice find!

**Closed** 2020-04-11 08:02 UTC
Labels: PR pending, bug

**Comment by bllngr** [comment] 2020-05-13 08:14
I can confirm that it works correctly on my Windows machines with 1.6.3. Thanks @alex-the-man and @varjolintu for the fix!

**Comment by MatthiasSchmitz93** [comment] 2022-07-08 19:33
This problem seems to have come back on Windows.
