### ISSUE TITLE
KeePassXC (Flatpak) Will Not Connect to KeePassXC-Browser On Brave Browser (Flatpak)

### ISSUE THREAD

**Issue by AManNeedsAMaid** [keepassxreboot/keepassxc-browser#1929] opened 2023-06-22 21:18 UTC
## Expected Behavior
Brave browser and KeePassXC flatpaks should be able to use browser integration together.

## Current Behavior
Brave browser cannot detect my database.

## Possible Solution
I tried the troubleshooting guide, and did everything except for debug the Content Scripts, as I couldn't find an instance of KeePassXC-browser's content script being ran. I also tried messing around with Flatseal permissions, but to no avail.

## Steps to Reproduce (for bugs)

1. Download Brave and KeePassXC Flatpaks
2. Install KeePassXC-browser to Brave
3. Enable browser integration and check off Brave in KeePassXC's settings
4. Attempt to connect to database

## Debug info
`KeePassXC-Browser: Connecting to native messaging host org.keepassxc.keepassxc_browser
global.js:145 [Error client.js:337] KeePassXC-Browser - Failed to connect: Native host has exited.
global.js:145 [Error keepass.js:880] KeePassXC-Browser - No content script available for this tab.
global.js:145 [Error page.js:128] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist.
global.js:145 [Error keepass.js:323] KeePassXC-Browser - 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.
global.js:145 [Error keepass.js:323] KeePassXC-Browser - 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.`
KeePassXC - 2.7.5
KeePassXC-Browser - 1.8.6.1
Operating system: Linux
Browser: Chromium / Brave

**Comment by varjolintu** [comment] 2023-06-23 04:35
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/1267 and https://github.com/keepassxreboot/keepassxc-browser/issues/1783. For now Flatpak browsers probably won't work at all.

**Closed by varjolintu** 2023-06-23 04:35 UTC
