### ISSUE TITLE
"Search in all opened databases for matching credentials" with multiple databases and multiple browsers not happening

### ISSUE THREAD

**Issue by MasinAD** [keepassxreboot/keepassxc-browser#1275] opened 2021-03-22 09:23 UTC
## Expected Behavior

I use KeepassXC for private and work credentials but in different databases. I also use two different browsers, Firefox privately and Chrome for work. I have KeepassXC installed in both of them, in Firefox connected to my private database, in Chrome connected to my work databases (there are two actually, a personal one and a shared one).

Basically, both browsers' connections work but I expect them to work independent of which database is currently focussed in KeepassXC.

Also, I don't want Firefox to suggest credentials belonging to my job and Chrome not suggesting private credentials.

## Current Behavior

Instead of searching in all the databases connected to the browser I need to focus on one database connected to the browser to have KeepassXC Browser suggest credentials.

## Possible Solution

Without knowing the code, I guess the add-on checks if the currently selected database has been connected and denies any access if not connected. I'd suggest checking first if any database is connected and then limit the search to those connected independent of current focus.

## Steps to Reproduce (for bugs)

I think my setup is mostly clear at this point.
1. Install two browsers supported by KeepassXC Browser
2. Create to different databases
3. Connect each of the database with only one browser
4. Try to have the add-on access credentials in the unfocussed database by using it in the browser not connected to the focussed database

## Debug info

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.6
Operating system: Mac
Browser: Chrome/Firefox

**Comment by droidmonkey** [comment] 2021-03-22 09:58
Enable the setting in keepassxc under the browser integration page to search all open databases.

**Comment by MasinAD** [comment] 2021-03-22 10:03
Setting is enabled. I even disabled it, saved the settings, then re-enabled it. You know, sometimes a setting needs a friendly reminder ;-).

I can add that the described behaviour occurs at page loading time. When I load a page and the database containing the credentials is not focussed then switching the database does not help. Reloading the page has the add-on finding the credentials. Maybe recognizing the login fields might help, too, but reloading the page is reliable.

**Comment by varjolintu** [comment] 2021-03-22 14:47
@MasinAD Is your second database originally a copy from the first one? You can try to set a new Root Group ID for the second database from KeePassXC's Database Settings. See if it helps.

**Comment by MasinAD** [comment] 2021-03-22 16:44
@varjolintu It took some searching. Of course, I wanted to look first if they are the same but KeepassXC seems to hide this information. Only later I discovered that KeepassXC Browser showed those Root Group IDs. So I regenerated them on my work related databases. No change besides some trouble getting them to connect to Chrome which I could solve by restarting KeepassXC.

After restarting KeepassXC and before switching to a work related database, I tried accessing some credentials in Chrome. But Chrome justs wants to connect my private database instead of using the already connected work-related databases. The button for detecting login fields isn't there, only the connect button. Switching to my personal work database the add-on then shows the button. Switching back to my not-connected private database the button changes back to connect.

So, it doesn't help. But I could add some details which isn't too bad. As long as there are unconnected databases the add-on wants first to connect to them before it searches credentials. Maybe the add-on could show a list of available databases including their respective connections status and a way to connect each database. As soon as one database is connected show the button for detecting login fields and search the databases accessible.

**Comment by varjolintu** [comment] 2021-03-22 17:03
@MasinAD I've already started working on a branch that improves the database handling in a way that it doesn't matter what database is active, but all connected ones are handled normally. Sadly it's a big refactor and takes time. The current implementation is not very good at handling a situation like yours. So for now the only workaround is to use them both at the same time, both being connected. You could possibly distinquish the credentials by putting them to a group and enabling the _Display the group name in autocomplete_ setting from the extension.

**Comment by varjolintu** [comment] 2021-03-22 17:14
@MasinAD This needs changes both KeePassXC and the extension side, so it needs a bigger update.

**Comment by leaumar** [comment] 2021-04-26 11:38
If it's of any value to post, I have the exact same issue between vivaldi and edge on win10 with keepassxc 2.6.4.

**Comment by mlavi** [comment] 2021-05-12 21:27
I also have this issue, I configured KeepassXC Application Settings > Browser Integration > General > Search in all opened databases for matching credentials [checkbox on].

My second database was a copy of the first, so I believe I have verified they share the same root group UUID with this procedure:

1. Select the second database tab to make it active
2. Choose the Root/topmost parent group, right click for a context menu, Edit Group...
3. Choose the Properties menu on the left side
4. Observe the Uuid is the same for your other database(s) root/topmost parent group

What I did not understand is that because the Root group ID is a read-only property in the GUI, you must do the following:

1. Select your second database tab to make it active
2. Choose Database > Database Settings...
3. Choose the Browser Integration menu on the left side
4. Press the "Refresh database root group ID" button
5. Click OK button
6. Close your database to insure everything was saved. :)

**Comment by mlavi** [comment] 2021-05-18 17:57
I also have this issue, I configured KeepassXC Application Settings > Browser Integration > General > Search in all opened databases for matching credentials [checkbox on].

My second database was initially a file copy of the first, so I have verified they share the same root group UUID with this procedure:

1. Select the second database tab to make it active
2. Choose the Root/topmost parent group, right click for a context menu, Edit Group...
3. Choose the Properties menu on the left side
4. Observe the Uuid is the same for your other database(s) root/topmost parent group

What I did not understand is that because the Root group ID is a read-only property in the GUI, so you must do the following to remeidate:

1. Select your second database tab to make it active
2. Choose Database > Database Settings...
3. Choose the Browser Integration menu on the left side
4. Press the "Refresh database root group ID" button
5. Click OK button
6. Close your database to insure everything was saved. :)

**Comment by varjolintu** [comment] 2023-01-29 12:19
Just a little update for this because I've been recently working with the feature fix.

It looks like for backwards compatibility it's best to create a totally new API request `get-database-statuses` (or something similar) which will return the database hash, locked/unlocked and associated status, all in one response. Still lot to do, but it's progressing.

**Comment by droidmonkey** [comment] 2024-08-18 18:24
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/5238

**Closed by droidmonkey** 2024-08-18 18:24 UTC
Labels: bug
