### ISSUE TITLE
Frequently login selection from multiple logins for same URL is not working via keyboard

### ISSUE THREAD

**Issue by foss-** [keepassxreboot/keepassxc-browser#1947] opened 2023-07-23 13:42 UTC
macOS 13.4.1 (c)
Firefox 115.0.2
KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: 9d72d8d

When more than a single entry exists for a domain, searching the login dropdown shwon by keepassxc-browser should is possible by typing an element from the login title.

## Current Behavior
However frequently typing on the keyboard does nothing when the login-list is presented.

## Expected Behavior
Typing should filter logins in dropdown and or pre-select the login matching what is typed.

**Comment by varjolintu** [comment] 2023-07-23 17:24
Duplicate of: https://github.com/keepassxreboot/keepassxc-browser/issues/1780.

**Closed by varjolintu** 2023-07-23 17:24 UTC
