### ISSUE TITLE
Floating Icon after login

### ISSUE THREAD

**Issue by Electronscape** [keepassxreboot/keepassxc-browser#2297] opened 2024-08-02 09:50 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

![image](https://github.com/user-attachments/assets/aefc3d1b-3627-446b-9a68-740bada327f6)
As  you may see, the Keepass icon still floating above the website after a successfull log in

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. simply clicked the icon in the log in screen chose the log in and signed in . 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
i would thing the icon would go away after log in was successful

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
the icon remains there now but interestingly its not visable on other tabs
using FIREFOX 128.0.3 
Windows 10 Pro (disabled updates)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10
Desktop Env: Explorer.exe (windows 10)
Windowing System: Windows 10 cant really say much ( really should switch to Linux, which is best?)

**Comment by droidmonkey** [comment] 2024-08-02 10:17
Duplicate of #945

**Closed by droidmonkey** 2024-08-02 10:17 UTC
Labels: bug
