### ISSUE TITLE
AS+U should fill username only

### ISSUE THREAD

**Issue by AdamPS** [keepassxreboot/keepassxc-browser#513] opened 2019-04-28 11:10 UTC
## Steps to Reproduce
1. Navigate to https://accounts.google.com/ (has username field but no password)
2. Press AS+U

## Expected Behavior
Fill the username only - safe assumption that the user wants this because they explicitly asked for the form to be filled.

## Current Behavior
Nothing happens

## Debug info
KeePassXC - 2.4.1
KeePassXC-Browser - 1.4.3
Operating system: Win
Browser: Firefox

**Comment by droidmonkey** [comment] 2019-04-28 12:26
It may be safe on that particular page, but not on others. This is a duplicate of other issues. We plan to implement a white list for popular sites that use split login forms. Going to close this one.

**Closed by droidmonkey** 2019-04-28 12:26 UTC

**Comment by AdamPS** [comment] 2019-04-28 16:18
Beg pardon but I am confused as to why this idea has been rejected.

> It may be safe on that particular page, but not on others.
Yes but I will only press AS+U on pages where I want the username to be filled.  I don't understand how anyone would prefer the current behaviour (they press AS+U and nothing happens) to my expected behaviour (they press AS+U and the form is filled).  Surely anyone who presses AS+U on a page with only a username is expecting the username to be filled???

> This is a duplicate of other issues
Well maybe there are lots of issues because it's not obvious how to make it work:-)  Having said that I did try to find an issue before I opened mine and didn't find it, so a link to another issue would be useful.

> We plan to implement a white list for popular sites that use split login forms.
A whitelist will definitely reduce the number of people seeing the problem, but the problem definitely remains.  Clearly a whitelist won't include all sites/URLs in the entire world, and it will go out of date.

**Comment by droidmonkey** [comment] 2019-04-28 18:16
I am not rejecting your idea, I'm saying there is no need for this issue because this idea is documented in another issue already. There is no need for an additional keyboard shortcut, the shortcut to fill username+password is sufficient for username-only as well.

**Comment by AdamPS** [comment] 2019-04-28 18:22
Thanks.  I definitely agree that no new key is needed.  However AS+U does not fill username only unless I enable it per site using "Username-only detection".  My proposal is that AS+U should fill username only without needing the setting of "Username-only detection".

Please can you tell me which other issue?  I found #159 but that seems different because it is asking for a new key.

**Comment by droidmonkey** [comment] 2019-04-28 18:35
I looked and actually couldn't find one that fit well. I don't like the way this issue is worded. I will create a new issue that captures the situation.
