### ISSUE TITLE
Bitbucket dashboard CSS for seperators is broken by injected css

### ISSUE THREAD

**Issue by Farix1337** [keepassxreboot/keepassxc-browser#610] opened 2019-09-27 07:31 UTC
Bitbucket dashboard css gets wierd CSS for seperators injected.

## Expected Behavior
Don't touch the CSS of Bitbucket if there are no Login-Fields

## Current Behavior
I guess the injected CSS for .seperators screws up the margin:
```
.separator {
    height: 100% !important;
    border-left: 1px solid rgb(204, 204, 204);
    margin: 10px !important;
}
```
Therefore every open PR in the bitbucket dashboard is shifted very ugly and almost not readable

## Possible Solution
remove the !important in the margin?

## Steps to Reproduce (for bugs)
1. Create a PR on a Bitbucket Repository which contains a slash in the branch-name
2. Open the dashboard

## Debug info

KeePassXC - 2.4.3
KeePassXC-Browser - 1.5.0
Operating system: Mac OS and Windows 10
Browser: Chrome 76.0.3809.132 and 77.0.3865.90

**Comment by varjolintu** [comment] 2019-09-27 07:42
Duplicate of #607.

**Closed by varjolintu** 2019-09-27 07:42 UTC
