### ISSUE TITLE
KeePassXC-Browser doesn't connect to KeePassXC, gives error "Cannot decrypt message"

### ISSUE THREAD

**Issue by tromlet** [keepassxreboot/keepassxc-browser#616] opened 2019-09-29 22:34 UTC
## Expected Behavior
It should connect to my open KeepassXC password database, and offer login credentials to me when I visit websites and attempt to login.

## Current Behavior
Instead of connecting to my password database, the icon in Firefox remains gray with a little red "x", and I don't get any credentials getting piped over. I'm a filthy billion-tab user that keeps his browser open for months, and this is typically when this problem happens. I can probably close out of the browser and all my tabs and it'll start working properly, but god that's a lot of tabs and stuff - it'd be real nice if it just kept working.

## Debug info
KeePassXC - 2.4.3
KeePassXC-Browser - 1.5.1
Operating system: Mac OS X 10.14.6
Browser: Firefox 69.0

**Comment by droidmonkey** [comment] 2019-09-29 23:06
Duplicate of the very next issue in the list. #615

**Closed by droidmonkey** 2019-09-29 23:06 UTC

**Comment by varjolintu** [comment] 2019-09-30 05:28
Did you know that you can reload the extension connection from the popup without closing your browser?
