### ISSUE TITLE
Icloud URL not being recognized

### ISSUE THREAD

**Issue by wildBcat** [keepassxreboot/keepassxc-browser#2081] opened 2024-01-14 16:08 UTC
## Expected Behavior
Go to https://www.icloud.com/. Try to use KeepassXC (via the key icon in the username field).
Result: see your username option

## Current Behavior
Get an error message that states: Error!No logins found. https://idmsa.apple.com

## Possible Solution
I have none so far.

## Steps to Reproduce (for bugs)

1. Add your credentials into KeepassXC
2. Add the URL (either as https://www.icloud.com/, https://idmsa.apple.com, https://*.apple.com, or https://apple.com)
3. Connect the extension on Firefox to your KeepassXC DB
4. Go to https://www.icloud.com/
5. Click on the key icon in the username field

## Debug info
No errors in the console

## Notes
I am relatively new to KeePassXC so I might be doing something wrong. All other passwords seem to be working so far. I have tried all combinations of the URL (https://www.icloud.com/, https://idmsa.apple.com, https://*.apple.com, or https://apple.com) in either the URL field or the additional URL fields. I changed settings in the browser section of KeepassXC and the extension's settings but nothing seems to work. I have screenshots if needed.

**Comment by droidmonkey** [comment] 2024-01-14 16:13
Duplicate of #2076, a fix is in the works

**Closed by droidmonkey** 2024-01-14 16:13 UTC
