### ISSUE TITLE
keepassxc browser extension does not work in firefox 71

### ISSUE THREAD

**Issue by acmondor** [keepassxreboot/keepassxc-browser#708] opened 2019-12-08 14:21 UTC
## Expected Behavior
The keepassxc browser extension should work as advertized.

## Current Behavior
The keepassxc browser extension cannot communicate with the keepassxc app and it can't even access its own settings (ie cannot access anything in the extension's options page).

## Possible Solution
none

## Steps to Reproduce
1. Create a new firefox profile in firefox 71
2. Install the lastest keepassxc browser extension
3. Observe the that keepassxc browser extension cannot communicate with the with the keepassxc app and it can't even access its own settings (ie cannot access anything in the extension's options page). 

** Note, before creating a new browser profile I saw these console logs:
JavaScript error: moz-extension://3f0f2104-ed66-47bd-8249-bd4204cd141c/content/keepassxc-browser.js, line 864: Error: undefined
JavaScript error: moz-extension://3f0f2104-ed66-47bd-8249-bd4204cd141c/content/keepassxc-browser.js, line 0: Error: undefined
JavaScript error: moz-extension://3f0f2104-ed66-47bd-8249-bd4204cd141c/content/keepassxc-browser.js, line 0: Error: undefined 

** Note, after creating a new browser profile I saw these console logs:
$ firefox -P
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 694: Error: Phase "xpcom-will-shutdown" is finished, it is too late to register completion condition "UserInteractionTimer 1 for document 7f41f60a1000"
JavaScript error: resource://services-common/kinto-offline-client.js, line 603: Error: IndexedDB clear() The operation failed for reasons unrelated to the database itself and not covered by any other error code.
1575811906550   addons.webextension.keepassxc-browser@keepassxc.org     WARN    Loading extension 'keepassxc-browser@keepassxc.org': Reading manifest: Warning processing version_name: An unexpected property was found in the WebExtension manifest.
console.error: PushService:
  stateChangeProcessEnqueue: Error transitioning state
  UnknownError
JavaScript error: , line 0: ConstraintError: A mutation operation in the transaction failed because a constraint was not satisfied.
JavaScript error: , line 0: uncaught exception: null
JavaScript error: moz-extension://1b2659b3-f2b8-491f-8841-65c0500fd964/background/browserAction.js, line 94: TypeError: page.tabs[id] is undefined
JavaScript error: moz-extension://1b2659b3-f2b8-491f-8841-65c0500fd964/popups/popup.js, line 12: TypeError: r is undefined
JavaScript error: resource://gre/actors/BrowserElementParent.jsm, line 81: TypeError: browser is null
JavaScript error: , line 0: NS_ERROR_UNEXPECTED:

## Context
This behaviour was observed on Linux (Gentoo), but only with firefox 71. 
The broken keepassxc browser extension means having to go back to manually coping/pasting all loging cridentials from the keepassxc app to firefox.

The keepassxc browser extension worked fine with firefox 70, so I'm going to have to roll back the browser version until this is resolved.

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.12.5
Debugging mode is disabled.

Operating system: Gentoo/Linux
CPU architecture: x86_64
Kernel: linux 4.19.86-gentoo-acmondor-001

Enabled extensions:
- Browser Integration
- SSH Agent
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

Enabled extensions:
- KeePassXC-Browser 1.5.3

**Comment by varjolintu** [comment] 2019-12-08 15:19
Duplicate of #704.

**Closed by varjolintu** 2019-12-08 15:19 UTC
