### ISSUE TITLE
CHANGING THE URL TO https://accounts-emea.f-secure.com DOES NOT WORK !!

### ISSUE THREAD

**Issue by TESTER-sec** [keepassxreboot/keepassxc-browser#2098] opened 2024-01-27 14:39 UTC
The KeePassXC browser extension is not detecting the F-Secure account login page.

This is not a Microsoft Edge issue; it is a KeePassXC browser extension issue.

**CHANGING THE URL TO https://accounts-emea.f-secure.com DOES NOT WORK !!**

Expected Behavior
The KeePassXC browser extension should detect the F-Secure account login page so that the user can use KeePass to log into their F-Secure account. KeePassXC content script should show the KeePassXC element in both the username & password fields. The right-click --> Fill username & password should work. Also KeePassXC should detect the URL and a pop-up should appear so that the user can allow the field fill if they have not already permanently allowed it.

Current Behavior
Steps to Reproduce (for bugs)
Navigate to https://my.f-secure.com/login .
KeePassXC cannot detect a login, even though one exists in KeePassXC.
Debug info
KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.11
Operating system: Windows 11 23H2
Browser: Microsoft Edge

**Comment by varjolintu** [comment] 2024-01-27 14:43
Please. The issue is already fixed in https://github.com/keepassxreboot/keepassxc-browser/pull/2079 and we are releasing a new version soon.

**Closed by varjolintu** 2024-01-27 14:43 UTC

**Comment by varjolintu** [comment] 2024-01-27 14:55
> > Please. The issue is already fixed in #2079 and we are releasing a new version soon.
> 
> Just doing what @droidmonkey said to do. The only way to report that what he said to do does not work is to create another issue.
> 
> He told me to change the URL in KeePassXC and that would solve the problem - which is complete nonsense.
> 
> He doesn't provide very good support. Don't blame the user.

He also said this:
https://github.com/keepassxreboot/keepassxc-browser/issues/2096#issuecomment-1913158116

You are just spamming the issue threads.
