### ISSUE TITLE
option to start keepassxc when browser addon can't connect to DB

### ISSUE THREAD

**Issue by chconnor** [keepassxreboot/keepassxc-browser#2248] opened 2024-06-16 04:52 UTC
I was hoping that when I start e.g. firefox and go to a login page and see the keepassxc icon on the login field and click it, that if it can't connect to the main application it would check to see if the application was running, and if it was not, start it (which would then ask for the password, etc.) Ideally, the user could also configure the command line options that would be sent to start the process.

Is it a choice to not have this option? Or maybe firefox addons are not permitted to do this?

If it's possible, it would be great. As it is, I use my keyboard shortcut to start keepassxc, so it's not the end of the world, I just think it would be a nice lowering of friction.

Thanks!

**Comment by varjolintu** [comment] 2024-06-16 04:59
Duplicate of #707.

**Closed by varjolintu** 2024-06-16 04:59 UTC
Labels: duplicate
