### ISSUE TITLE
everytime loses connection with database.

### ISSUE THREAD

**Issue by c269574** [keepassxreboot/keepassxc-browser#623] opened 2019-10-02 07:30 UTC
![изображение](https://user-images.githubusercontent.com/40603957/66025504-511a9200-e4ff-11e9-860d-9e36632e568d.png)
(Translate from russian - Open database again)

Random actions (delete-install extension, relaunch windows app, relaunch firefox) can restore functionality, but it always loses connection again after closing firefox..

**Comment by varjolintu** [comment] 2019-10-02 07:45
Duplicate of #615.

**Closed by varjolintu** 2019-10-02 07:45 UTC
Labels: duplicate
