### ISSUE TITLE
Username/password field detection stopped working with Firefox 61.0.2

### ISSUE THREAD

**Issue by cryptomilk** [keepassxreboot/keepassxc-browser#282] opened 2018-08-27 16:25 UTC
With an update to Firefox 61.0.2 on openSUSE Tumbleweed. The browser addon stopped working. If I click on a username field, I don't get the selection for the credentials anymore.

I can do a right-click and select KeepassXC-Browser -> Fill User + Pass. Then sometimes it fills it out but not always.

How can I debug and find out what is actually going wrong?

## Debug info

KeePassXC - 2.3.4
keepassxc-browser - 1.2.0
Operating system: Linux (openSUSE Tumbleweed)
Browser: Firefox

**Comment by varjolintu** [comment] 2018-08-27 17:51
Possible duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/275.
Also, check https://github.com/keepassxreboot/keepassxc/issues/2237

**Comment by cryptomilk** [comment] 2018-08-27 17:57
The URL match correctly and even if I make it less strict it doesn't work :-(

Is there a way to get debugging information or see what it is actually doing?

**Comment by cryptomilk** [comment] 2018-08-27 17:57
The same already happened with keepassxc-2.3.3

**Comment by varjolintu** [comment] 2018-08-27 18:13
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#4-debug-the-extension-itself

And to check what content script outputs you can right click the page and select Inspect/Inspect element.

Are the pages with only username field visible, or can you give any of those URL's that don't work for you?

**Comment by cryptomilk** [comment] 2018-08-27 20:14
I don't get KeepassXC login selection for any webpage.

Examples are:
https://www.paypal.com/de/signin
https://bugs.kde.org/
...

I don't get any Errors in the Console. However it looks like something blocks the on click trigger when I select the username field.
In the settings I've deactivated "Ask to save logins and passwords for websites".

I don't find anything which could cause trouble or reports some kind of an error. This is really bizarre.

**Comment by varjolintu** [comment] 2018-08-27 20:47
Have you tried to add https://www.paypal.com/de/signin to Site Preferences and enable the Username-Only Detection?

**Comment by cryptomilk** [comment] 2018-08-28 05:27
Well none of the passwords fields is even detected. Normally it shows the "Password Generator Icon" but it is not shown and it doesn't matter which page I visit. Maybe I need to kill the profile and start from scratch. I have now idea what is broken here.

**Comment by cryptomilk** [comment] 2018-08-28 05:51
I've removed my profile and started from scratch. Everything works now.

**Comment by varjolintu** [comment] 2018-08-28 06:02
Sounds really strange. I have no idea what problem in the profile could cause extensions to break.

**Comment by cryptomilk** [comment] 2018-08-28 06:26
However, thanks for your help!

**Comment by samuel141** [comment] 2018-08-28 08:40
I have the same issue with Firefox 61.0.1 on Ubuntu 18.04.  Only the context menu works. The normal way works only with a new profile.

My versions:
Ubuntu 18.04.1
Firefox 61.0.1
KeePassXC 2.3.4
KeePassXC-Browser 1.2.0

**Comment by cryptomilk** [comment] 2018-08-28 08:44
Oh, should we reopen the bug?

**Comment by varjolintu** [comment] 2018-08-28 08:46
@samuel141 Does downgrading to 2.3.3 work?

I'm not certain if this is a KeePassXC-related issue if creating a new profile works. But it would be nice to know what breaks it.

**Comment by varjolintu** [comment] 2018-08-29 07:41
@samuel141 You could try to remove the extension totally and reinstall it. Currently I have no idea why a lot of issues have been coming in. The extension haven't been updated recently, and downgrading to KeePassXC 2.3.3 doesn't solve the problem either.

**Comment by cryptomilk** [comment] 2018-08-29 11:56
I've created a new profile, installed keepassxc-browser from scratch and it was working just fine.

Till now.

I have absolutely no idea what happened but it stopped working! No username/password selected is offered for any site.

**Comment by cryptomilk** [comment] 2018-08-29 11:57
varjolintu: If you want, we can do a phone call + screen sharing session for debugging.

**Comment by cryptomilk** [comment] 2018-08-29 13:29
@varjolintu bluejeans + tmate, drop me a mail at asn at cryptomilk dot org when you have time, then I will send you the details how to dial in/connect.

**Comment by cryptomilk** [comment] 2018-08-29 16:06
I'm gladiac on freenode

**Comment by varjolintu** [comment] 2018-08-29 19:36
Let's reopen this.

There's a bug in the manual URL adding in Site preferences. If the site has multiple subdomains, that is not handled correctly.

**Closed** 2018-09-11 12:59 UTC
Labels: PR pending, bug

**Comment by zioalex** [comment] 2018-10-25 08:55
Just a small comment. I had the same problem with FF 62.0.3 and I had to install the latest version of every components:
KeePassXC-Browser Version: 1.3.0
KeePassXC Version: 2.3.4 

Now every is working as expected! Fuhhh
