### ISSUE TITLE
Change default title of new credentials from domain to site name

### ISSUE THREAD

**Issue by janicolou** [keepassxreboot/keepassxc-browser#2118] opened 2024-02-15 13:17 UTC
## Expected Behavior

Instead of saving www.github.com as the title, save it as Github.

## Current Behavior

Title saves as domain name by default. 

## Possible Solution

- Save the site name as the title as the default behavior instead of the domain name. 
- In the "Saving Credentials" section in settings, add the "Save Site Name" "When saving new credentials, save only the site name instead of the domain name."

**Comment by varjolintu** [comment] 2024-02-15 14:14
Duplicate of #662.

**Closed by varjolintu** 2024-02-15 14:14 UTC
