### ISSUE TITLE
Multiple passwords for different URLs being presented on some URLs after update

### ISSUE THREAD

**Issue by chc-pr** [keepassxreboot/keepassxc-browser#682] opened 2019-11-12 21:30 UTC
#387  Expected Behavior
Only the logon details for the specified full URL should be presented

## Current Behavior
For some URLs, multiple logon details are being presented which are not applicable to the actual URL being visited

## Steps to Reproduce (for bugs)
Not sure if this will be universal, but this behaviour started after upgrading to the latest version (release 2.5.1)

## Debug info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by varjolintu** [comment] 2019-11-12 21:36
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/3848.

**Closed by varjolintu** 2019-11-12 21:36 UTC
