### ISSUE TITLE
Plugin generated icons mispositioned.

### ISSUE THREAD

**Issue by DonnKey** [keepassxreboot/keepassxc-browser#1011] opened 2020-09-13 18:42 UTC
## Expected Behavior
The website described below shows with the Keepass-XC Browser plugin icons mis-positioned. The website does a "late" change that the browser doesn't see (or act on?)

## Current Behavior
See screen shot: notice green Browser icons are misaligned with text fields.

## Steps to Reproduce (for bugs)
1. (Don't try to skip this step... it won't work). Go to https://www.optumrx.com/public/landing.
2. Click sign-in.
3. It will forward you to a long URL, which gets refreshed to https://hsid11.optum.com/ almost immediately.
4. The user id and password fields will be displayed, and the Browser plugin will place its (green) icons.
5. A half-second or so later, the web page is refreshed by inserting a bar at the top of the page.
6. Which yields the image below.

Yes, this is cosmetic, since everything does work.

## Debug info
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.1
Operating system: Win32
Browser: Chrome/Chromium 85.0.4183.102

![image](https://user-images.githubusercontent.com/44411983/93025720-4690c580-f5b5-11ea-985d-2f06a18a5214.png)

**Comment by varjolintu** [comment] 2020-09-13 19:09
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/856

**Closed by varjolintu** 2020-09-13 19:09 UTC
