### ISSUE TITLE
Cannot autofill sometimes

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#91] opened 2018-03-21 08:03 UTC
## Expected Behavior

Autofill should work as it worked with keepasshttp before.

## Current Behavior

Does not autofill, and I cannot even manually "select the credential fields" or "redetect the fields".

## Steps to Reproduce (for bugs)

0. Save a username/password in KeePassXC with the URL `https://www.openstreetmap.org`.
1. Go to https://www.openstreetmap.org and try to login.

## Debug info

KeePassXC-Browser Version: 1.0.1
KeePassXC Version: 2.3.1 
Operating system: Linux
Browser: Firefox 59
Proxy used: yes

**Comment by rugk** [comment] 2018-03-21 08:36
Okay, it actually seems to be not related to the site. The detection just does not work anywhere.
Needs a browser restart, I think.

**Comment by droidmonkey** [comment] 2018-03-21 10:44
This is a duplicate of my issue.

**Closed by droidmonkey** 2018-03-21 10:44 UTC

**Comment by rugk** [comment] 2018-03-21 15:19
Ah ok, of https://github.com/keepassxreboot/keepassxc-browser/issues/68 to be more exact.
