### ISSUE TITLE
Exclude group for suggestions

### ISSUE THREAD

**Issue by MasinAD** [keepassxreboot/keepassxc-browser#1306] opened 2021-04-13 08:08 UTC
## Feature request

I propose an option to exclude groups and their children from being suggested to fill login fields.

My usecase is the preparation of credentials for new employess. I have a group I use as a template which already contains entries with all the necessary URLs. I don't want keepassxc-browser asking for access to those. In another issue I already reported that neither keepassxc nor keepassxc-browser remember when I set the checkbox in the dialog and deny the access. On further consideration, it was better to just exclude a subtree. On export of the new employee's credentials it woud otherwise export the stored access denial.

Of course, I don't know if the kdbx data model allows such an extension.

**Comment by droidmonkey** [comment] 2021-04-13 10:17
See #4180. It's been coded, just needs to be merged and released. Closing this as duplicate of others. I like the use case.

**Closed by droidmonkey** 2021-04-13 10:17 UTC
