### ISSUE TITLE
"Search in all opened databases" does not work

### ISSUE THREAD

**Issue by mario0511** [keepassxreboot/keepassxc-browser#634] opened 2019-10-15 08:00 UTC
The suggested solution does not work for me

Has something changes since then?

_Originally posted by @mario0511 in https://github.com/keepassxreboot/keepassxc-browser/issues/318#issuecomment-542089343_

**Comment by varjolintu** [comment] 2019-10-15 09:28
Duplicate of #590. Please post any issues in the future.

**Closed by varjolintu** 2019-10-15 09:28 UTC
Labels: duplicate
