### ISSUE TITLE
New version breaks Azure DevOps page.

### ISSUE THREAD

**Issue by CMBulthuis** [keepassxreboot/keepassxc-browser#613] opened 2019-09-27 08:41 UTC
## Expected Behavior
When working in Azure DevOps in your project page the left part of the page provides a list with the main topics Overview, Boards, etc. which contain sub topics.
![image](https://user-images.githubusercontent.com/19352729/65755103-bc84ee00-e112-11e9-8b6b-251a4ba66330.png)

## Current Behavior
Since the new version 1.5.0 the topics are not displayed anymore.
![image](https://user-images.githubusercontent.com/19352729/65755039-9a8b6b80-e112-11e9-846f-58766302a0a9.png)
When switching off the KeePassXC-Browser extension they are back again.

## Possible Solution

Is it possible to provide as a workaround till this is fixed the previous version of the extension?

## Steps to Reproduce (for bugs)
1. Disable the KeePassXC-Browser extension in Chrome
2. Login to https://dev.azure.com
3. Open an existing project or create one if it is the first time
4. On the left part of the page you will see the mentioned topics, Overview, Boards, etc.
5. Enable the KeePassXC-Browser extension in Chrome
6. Refresh the Azure DevOps page.
7. All the topics will disappear.

I created a temporally project to show the behaviour.
Note: Please let me know if above steps to reproduce works, so I can cleanup this temporally configuration.
1. Disable the KeePassXC-Browser extension in Chrome
2. Go to https://dev.azure.com/chris0199/KeePassXC-Browser-issue
4. On the left part of the page you will see the mentioned topics, Overview, Boards, etc.
5. Enable the KeePassXC-Browser extension in Chrome
6. Refresh the Azure DevOps page.
7. All the topics will disappear.

## Debug info

KeePassXC - 2.4.3
KeePassXC-Browser - 1.5.0
Operating system: Mac
Browser: Chrome

**Comment by varjolintu** [comment] 2019-09-27 08:51
Duplicate of #607. I already have the fix ready.

**Closed by varjolintu** 2019-09-27 08:51 UTC

**Comment by CMBulthuis** [comment] 2019-09-29 21:24
Great quick response. Thanks :-).
