### ISSUE TITLE
Login fields on smartbroker.de not recognized

### ISSUE THREAD

**Issue by funnym0nk3y** [keepassxreboot/keepassxc-browser#1346] opened 2021-06-12 08:48 UTC
## Expected Behavior

I expect the browser extension to recognize the login fields on smartbroker.de.

## Current Behavior

Not recognizing the fields.

## Debug info

KeePassXC - latest
KeePassXC-Browser - latest
Operating system: Win
Browser: Firefox

**Comment by varjolintu** [comment] 2021-06-13 04:46
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/1116

**Closed by varjolintu** 2021-06-13 04:46 UTC
Labels: duplicate
