### ISSUE TITLE
Autocomplete, only fill in matches for input text

### ISSUE THREAD

**Issue by anna-springer** [keepassxreboot/keepassxc-browser#1215] opened 2021-02-11 07:49 UTC
I am trying to migrate from chrome password storage to KeePassXC but there is currently one thing holding me back.
Is there a possibility to only show autofill entries for usernames which matches the already typed letters? On Pages with multiple accounts (e.g local test pages) this is very very useful.

## Expected Behavior

Let's say you got the following entries:

tiger@example.com
cat@example.com

When i type in "tiger" into the username field, it should only return me the matching "tiger" entry. On pages with many credentials, this would speed up selecting/getting one a lot.

## Current Behavior
No matter what's in the username box, keepass always shows the complete list of all usernames.

## Debug info

**Comment by varjolintu** [comment] 2021-02-11 09:00
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/478

**Closed by varjolintu** 2021-02-11 09:00 UTC
