### ISSUE TITLE
For new sign-in, allow searching in KeepassXC database and allow adding new reference entries directly

### ISSUE THREAD

**Issue by dieterlohrstraeter** [keepassxreboot/keepassxc-browser#1186] opened 2021-01-18 15:17 UTC
Signing in on a new URL by using an already existing account (e.g. Active-Directory) requires a new entry with reference to it.
I see no option from KeepassXC-Browser to search free in database for any entries, if it is not already offered.

Currently, I switch over to KeepassXC, then search the existing account and create a clone-entry from it.
Afterwards, I have to adjust the clone, like URL, Title etc. manually in KeepassXC, because it is not possible in KeepassXC-Browser.

If everything is correct, I turn back to the Browser and have to reload the sign-in page. If everything is correct, I can choose now the cloned entry.

This requires a lot of manual config and long time.

## Expected Behavior
In any Browser with KeepassXC-Browser extension, when asked for "sign in", it should be possible to search in database for already existing accounts and offer to create a new entry as clone.
As result, a new entry should be created like for a new entry, but using username and password from the selected entry.

## Possible Solution
It would be sufficient to allow searching in the database, by clicking on the KeepassXC-Browser icon, where the box with Preferences and "User defined credentials" is shown. A new entry for the current URL with reference for Userid and Password to the selected entry shall be used.

Alternatively, it would already be helpful to save known user/password as usual and allow to exchange these values in KeepassXC easily by just searching the to be referenced entry and replace user/pw as reference to it.

## Debug info
KeePassXC - 2.6.3
KeePassXC-Browser - 1.7.4
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by varjolintu** [comment] 2021-01-18 16:07
This is by design that it's not possible to search the whole database when using the extension, only the credentials with a matching URL.

**Comment by dieterlohrstraeter** [comment] 2021-01-18 16:31
Okay, but how about allowing it with extra protection, e.g. typing Master-PW explicitly again?

I've also mentioned an alternative design within KeepassXC, by allowing to replace a newly created entry with the references from the other searched entry. It would be more effort for the user, but would help a lot as well.
It would work in the opposite direction as the clone function.

How it could work:
1. Create new entry in KP-DB via KeepassXC-Browser as usual (optionally with incorrect user/pwd).
2. Switch to KeepassXC
3. Select newly created entry and edit
4. Open a new dialog, to search in database for to be referenced entry and click "Create Reference"
5. Save: Overwrites existing username and password with reference to selected entry

**Comment by varjolintu** [comment] 2021-01-18 18:37
> Okay, but how about allowing it with extra protection, e.g. typing Master-PW explicitly again?

This would have to happen in KeePassXC. The browser extension will never ask your master password.

**Comment by varjolintu** [comment] 2021-01-19 18:56
It's better to use something like Global Auto-Type for this. This is out of scope of the extension for now.

**Closed by varjolintu** 2021-01-19 18:56 UTC
