### ISSUE TITLE
Feature Request: Sync settings across multiple Chrome browser Profiles

### ISSUE THREAD

**Issue by nikduvall** [keepassxreboot/keepassxc-browser#2099] opened 2024-01-27 14:58 UTC
## Summary
Please add support to sync keepassxc-browser settings across multiple Chrome browser profiles

## Expected Behavior
Regardless of which Chrome profile is opened, all settings are the same.  When a custom domain is added in one profile, it should automatically work in all other profiles

## Current Behavior
After installing the browser extension in an additional Chrome Profile(s), user must manually apply all customized settings including rebuild custom domain profiles.

## Possible Solution Ideas
1. Use keepass database as source of truth for all extension settings
2. Allow user to specify a Google Drive storage location (or other popular cloud storage options) as source of truth for all extension settings
3. Add trigger(s) to refresh settings from source of truth such as extension load, page load, redetect login fields
4. Add sync button in Extension Settings to force sync
5. Add Extension Settings to change Source of Truth location

## Debug info
KeePassXC - 2.76
KeePassXC-Browser - 1.8.11 + PR2079
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by varjolintu** [comment] 2024-01-27 14:59
Duplicate of #1664.

**Closed by varjolintu** 2024-01-27 14:59 UTC
