### ISSUE TITLE
autofill on google login is broken (endless loop)

### ISSUE THREAD

**Issue by Staubgeborener** [keepassxreboot/keepassxc-browser#1624] opened 2022-05-13 06:34 UTC
## Expected Behavior

I am using the latest version of KeepassXC 2.7.1 on Windows 10 with the KeePassXC browser extension for Firefox 100.0. When logging in with autofill on google relevant website (YouTube, Googlemail, etc.) the username/email address is automatically filled in, the press of the enter key simulates so that the input mask for the password appears and the next simulated press of enter key takes me back to the window for entering the email address. At this point the login should work. This problem does not occur on other websites that split the email address mask and password mask in the same way (e.g. Amazon). If you do nothing, you are in a continuous loop between "Email address autofill" -> "Password autofill" -> "Back to email address autofill" -> ...

If the email address on Google was automatically entered by KeepassXC and the enter key was simulated, I can quickly click "Disconnect Database" in the extension for the password mask and then re-establish the connection. Then Keepass performs the autofill for the password correctly. This problem is currently only known to me via the Google login mask.

## Possible Solution

Obviously, fix the autofill at Google login websites. It is also conceivable that a specific delay for individual database entries could fix the problem, e.g. set a delay of 1000 ms for the entry for my Google account, so that KeePassXC takes 1000 ms to autofill, but this does not affect other entries.

## Steps to Reproduce (for bugs)

1. Create database entry for YouTube in KeePassXC on windows 10
2. Try to login on YouTube with autofill and auto enter key
3. See the endless loop

## Debug info

KeePassXC - 2.7.1
KeePassXC-Browser - 1.7.12
Operating system: Win64
Browser: Mozilla Firefox 100.0

**Comment by varjolintu** [comment] 2022-05-13 06:35
Duplicate of #1356.

**Closed by varjolintu** 2022-05-13 06:35 UTC
Labels: duplicate
