### ISSUE TITLE
Ebay login page does not work on Firefox but works on Chrome

### ISSUE THREAD

**Issue by nbartos** [keepassxreboot/keepassxc-browser#336] opened 2018-11-24 21:42 UTC
## Expected Behavior
Should be able to fill in credentials on Ebay's new login page on both Firefox and Chrome.

## Current Behavior

Credential fill in only works on Chrome for Ebay's new login page.

## Steps to Reproduce (for bugs)

1.  Go to https://www.ebay.com/
2.  In upper left corner, click "Sign in" (should be redirected to "https://signin.ebay.com/ws/eBayISAPI.dll?SignIn&ru=https%3A%2F%2Fwww.ebay.com%2F")
3.  Right click in username field, select Keepass-XC-Brower -> Fill username and password

Additionally, strange behavior when clicking the KeepassXC-Browser extension icon and selecting "choose custom login fields for this page" does not do anything at all.

## Debug info

KeePassXC - 2.3.4
KeePassXC-Browser - 1.3.0
Operating system: Linux
Browser: Chrome 70.0.3538.77, Firefox 63.0.3

**Comment by varjolintu** [comment] 2018-11-25 09:13
Do you have some URL's in the Site Preferences list that could affect this? The page works just fine for me with the latest stable Firefox.

**Comment by droidmonkey** [comment] 2018-11-25 13:04
I can confirm this does not work on Firefox 63.0. No obvious errors popup, but there is the dump from the window:

```
ReferenceError: checkForBrowserAutoComplete is not defined[Learn More] eBayISAPI.dll:93:9
	window.onload https://signin.ebay.com/ws/eBayISAPI.dll:93:9
```

**Comment by nbartos** [comment] 2018-11-25 20:44
I have nothing in the site preferences.

**Comment by varjolintu** [comment] 2018-11-26 06:02
I'm using uBlock with my primary Firefox browser and it works just fine. But if I test the site with `web-ext` (no extensions are installed or activated), the site doesn't work with Firefox. It seems the page scripts somehow detect and override jQuery in the content scripts, and this causes multiple problems. I checked the same page with `no_jquery` branch and it didn't have such problems.

I can try to detect the real cause of course, but it must be related to jQuery. In the meanwhile it's possible to try tweaking adblock rules, even if it's only a workaround.

**Comment by nbartos** [comment] 2018-11-26 06:12
I have tried when keepassxc-browser was the only extension, and also with ublock origin enabled with all sources selected.  Unfortunately neither option works for me.

**Comment by varjolintu** [comment] 2018-11-26 06:34
The thing for me was to disable the JavaScript totally from the login page. I'm using uBlock in Advanced mode.

**Comment by MenNr34** [comment] 2018-11-26 18:55
I have encountered the same problem with Ebay on Firefox. Do multiple log in sites like Outlook still not work because they don't work for me too. I have to use auto type.

**Comment by varjolintu** [comment] 2018-11-27 05:49
@MenNr34 Add those sites to Site Preferences (tab in the extension settings) and enable Username-only detection. This is behind an option because there's no standard way to detect a single login input field from search fields etc.

**Comment by sebast889** [comment] 2018-11-27 11:55
@varjolintu Sorry for slight OT, but what do the Enable/Disable all features and Disable new/modified credentials settings do? Couldn't find any documentation on this.

**Comment by varjolintu** [comment] 2018-11-27 12:00
@sebast889 The tab page has a minimal help text:
```
To ignore new/modified credentials on a specific site, add them below or click the blinking KeePassXC-Browser icon and select Never ask for this page.
If a site is fully ignored (Disable all features is selected), then the plugin will do nothing when visiting that site.
Username-only detection allows KeePassXC-Browser to fill in login details on websites with separate pages for username and password.
```

**Comment by sebast889** [comment] 2018-11-27 12:08
Sorry I meant clearer documentation as I didn't really understand fully what the differences were from that text. But I see now that the KeepassXC github website's documentation explains it slightly better.

**Comment by Olivier-ADLER** [comment] 2018-12-12 14:48
Same problem with Firefox 64.0.

I did not find a simple solution to block only the Ebay login page scripts.
Disabling scripts for the Ebay domains does work but remaining site pages do not work anymore.

Is there a solution using Noscript, Ublock or Umatrix as a temporary workaround ?

Firefox integrated password management is working with Ebay. Seems like the KeypassXC browser plugin would need a higher privilege. If not possible, KeepassXC integration at the main code level would be a nice solution in the long run.
This would give better reliability in the long term if more and more sites use scripts that could block KeypassXC browser like Ebay.
Password management should be a transparent experience.

Last, an external token source like a FIDO U2F key or PGP USB key would be nice for KeypassXC or integrated in Firefox for account and passwords protection. Because regardless what we do, passwords and key files can be logged if entered on the PC keyboard or read in the OS file system.

An external protected source seems the only secure way to go. USB secure keys seems a simple and low cost solution.
Actually the only available method to get such an external token validation is using HMAC-SHA1 challenge response with a Ubikey. But the hmac request and response is the same every time. If the system is compromised this is not very secure. And this is only working with Ubikey.

**Comment by KleinZeta** [comment] 2019-01-17 11:05
...exactly the same problem with Firefox 64.0.2
I use NoScript by default, with enabled scripts for Ebay: ...ebay.de, ...ebay-us.com and ...ebaystatic.com. 
The login with KP-Browser then does not work as described by nbartos:
- The simple (right) click and select Login does not work
- Enter the username by hand and fill in the KP browser password also does not work
- Both ways via shortcut do not work either
- Site preference settings don't work for me either
- User-defined login fields cannot be defined at all.

What´s working:
+ clicking on the user field and fill in with KP Auto-Type works fine
+ What also works for me as a small workarround:
	> block all ebay-scripts with NoScript respectively leave them on default
	> Perform the login with KP 
		>> The login works, the ebay page does not work correctly
	> Allow the blocked scripts temporarily: ...ebay.xx, ...ebay-us.com and ...ebaystatic.com 
		>> The Ebay page should work correctly.
...not very elegant but it can be used to some extent.

**Comment by varjolintu** [comment] 2019-01-17 11:45
I tested this with https://github.com/keepassxreboot/keepassxc-browser/pull/128 and it seems to works. I can see a jQuery error in the console when trying to select custom credential fields on the release version. So there might be something that collides with it. Doesn't explain it why Chrome/Chromium works just fine.

**Comment by varjolintu** [comment] 2019-04-19 12:06
Closing this as eBay site clearly does some heavy scripting with the input fields and messes up with content scripts.

**Closed by varjolintu** 2019-04-19 12:06 UTC
Labels: bug
