### ISSUE TITLE
Browser extension disconnects from database

### ISSUE THREAD

**Issue by maherbo** [keepassxreboot/keepassxc-browser#1753] opened 2022-10-26 16:29 UTC
## Expected Behavior

The database stays connected to the browser extension as long as the browser is running

## Current Behavior

After using keepassxc-browser on one website, it gets disconnected from the database when trying to get on another website. Error is:

_Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings._

The solution is to click reload or to close the browser and open it again. When reloading, the username & password icons, which are usually green, are now gray (but they work as usual).

This behavior began after the last update.

## Possible Solution

???

## Steps to Reproduce (for bugs)

1. Go to a website with managed credentials
2. Login with keepassxc-browser and log off the website
3. Go to another website with managed credentials
4. You have no icon for the username and a gray "key" icon for the password

## Debug info

KeePassXC - 2.7.3
KeePassXC-Browser - 1.8.3
Operating system: Linux x86_64
Browser: Mozilla Firefox 105.0

**Comment by varjolintu** [comment] 2022-10-26 16:51
Duplicate of #1751.

**Closed by varjolintu** 2022-10-26 16:51 UTC
