### ISSUE TITLE
Keepassxc-Browser is "causing Firefox to slow down"

### ISSUE THREAD

**Issue by 5paceToast** [keepassxreboot/keepassxc-browser#146] opened 2018-05-10 23:24 UTC
## Expected Behavior

Keepassxc-Browser does not cause any significant slowdowns.

## Current Behavior

https://twitter.com becomes unresponsive (anytime new content is loaded (often), may affect more websites) and after some time Firefox suggests stopping the "script" that's causing it to slow down.

## Steps to Reproduce (for bugs)

1. Go to https://twitter.com
2. Log in (if not already)
3. Wait a few seconds for the slowdown to kick in.
4. Click "stop it" (the script in question) to see everything load in instantly and go back to being responsive.

## Debug info

KeePassXC - 2.3.3
keepassxc-browser - 1.1.2
Operating system: Win
Browser: Firefox (60.0 and 59.0.3 tested)
Proxy used: NO

## Extra Notes
May potentially be related to #145 (?) though the browser never crashes, and the javascript console doesn't show anything.

## Updates
Also happens on the following websites (will be updated):
- https://glowing-bear.org (I run my own instance, but it's a local javascript application that the website deploys, so it should happen on the official instance as well)

**Comment by droidmonkey** [comment] 2018-05-11 01:41
This seems like a firefox exclusive issue, I do not experience any issues on those websites in Chrome.

**Comment by bullet64** [comment] 2018-05-11 06:32
Same here. Problem since yesterday.

**KeePassXC** 
KeePassXC - Version 2.3.3
Revision: 0a155d8

Bibliotheken:
- Qt 5.5.1
- libgcrypt 1.8.1

Betriebssystem: Linux Mint 18.3
CPU-Architektur: x86_64
Kernel: linux 4.10.0-42-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**KeePassXC-Browser**
KeePassXC-Browser Version: 1.1.1

FireFox
FireFox 59.0.2(64bit)

I am using Linux Mint 18.3 Cinnamon 64bit

**Comment by varjolintu** [comment] 2018-05-11 06:49
The fix has been already made. Waiting for new release.

**Closed** 2018-05-11 08:05 UTC

**Comment by bullet64** [comment] 2018-05-11 09:31
1.1.3 installed and it look like the problem is fixed. Good Job. Thank you!

**Comment by jcosentino** [comment] 2020-04-16 14:37
This is happening to me again.

KeePassXC - 2.5.4
keepassxc-browser - 1.6.2
Operating system: Windows 10 and Max OS 10.15.4
Browser: Firefox 75.0 (happening since the latest 73)
Proxy used: No

This seems to happening only when I am on LinkedIn: https://www.linkedin.com/feed/

**Comment by varjolintu** [comment] 2020-04-16 14:51
@jcosentino It should be already fixed with https://github.com/keepassxreboot/keepassxc-browser/pull/836. Wait for the next release.

**Comment by species-gh** [comment] 2020-06-25 21:00
I've been experiencing this with version 1.6.4 for some days now at Google Play Music and YouTube Music.

Firefox 77.0.1
Ubuntu 18.04
KeePassXC 2.5.4

**Comment by varjolintu** [comment] 2020-06-26 04:31
@species-gh This is already tracker with #888.

**Comment by ManInTheSuit** [comment] 2024-12-30 10:11
Experiencing the same when loading new comments on reddit (old.reddit)

**Comment by varjolintu** [comment] 2024-12-30 12:10
> Experiencing the same when loading new comments on reddit (old.reddit)

I tried this and cannot reproduce. How is it visible for you?

**Comment by ManInTheSuit** [comment] 2024-12-30 13:13
Example, went to reddit popular with >1k comments

https://imgur.com/yj89peW

**Comment by ManInTheSuit** [comment] 2024-12-30 13:13
> > Experiencing the same when loading new comments on reddit (old.reddit)
> 
> I tried this and cannot reproduce. How is it visible for you?

Example, went to reddit popular with >1k comments

https://imgur.com/yj89peW

**Comment by varjolintu** [comment] 2024-12-30 13:37
> > > Experiencing the same when loading new comments on reddit (old.reddit)
> > 
> > 
> > I tried this and cannot reproduce. How is it visible for you?
> 
> Example, went to reddit popular with >1k comments
> 
> https://imgur.com/yj89peW

For me that kind of link just loads a few seconds and then the comments are normally seen. I need some more info, for example: is your database open? Are you having some settings added with Reddit site (in extension settings) etc?

**Comment by ManInTheSuit** [comment] 2024-12-30 13:40
> > > > Experiencing the same when loading new comments on reddit (old.reddit)
> > > 
> > > 
> > > I tried this and cannot reproduce. How is it visible for you?
> > 
> > 
> > Example, went to reddit popular with >1k comments
> > https://imgur.com/yj89peW
> 
> For me that kind of link just loads a few seconds and then the comments are normally seen. I need some more info, for example: is your database open? Are you having some settings added with Reddit site (in extension settings) etc?

database closed, extensions on my browser are: ublock origin, decentraleyes, firefox multicontainers and Plasma integration

I think the key to reproducing is to start another action in browser, for my scrolling (via auto scroll or normal scroll down) works
