### ISSUE TITLE
Can connect to database, cannot detect any fields (previously working), "Error: Cannot load extension settings"

### ISSUE THREAD

**Issue by Ezwen** [keepassxreboot/keepassxc-browser#712] opened 2019-12-12 09:19 UTC
## Expected Behavior

Fields should be detected by the extension, and icons should appear in the fields to easily choose credentials and trigger the autofill.  

## Current Behavior

While the extension does successfully connect to my database, it does not seem to detect fields any more, and does not provide any way to select credentials and trigger autofill.

In the JS console I can see `Error: Cannot load extension settings  keepassxc-browser.js:832:17`

Only a couple of weeks ago this was working perfectly.

## Steps to Reproduce (for bugs)

1. Go to https://github.com/login (I have multiple github credentials in my keepass database)
2. Nothing happens

## Debug info

`Error: Cannot load extension settings  keepassxc-browser.js:832:17`

KeePassXC - 2.5.1
KeePassXC-Browser - 1.5.4
Operating system: Linux (Fedora 31)
Browser: Firefox

**Comment by Ezwen** [comment] 2019-12-12 09:21
Additional note: the settings of the extension appear empty (same for each tab):
![Capture d’écran de 2019-12-12 10-20-37](https://user-images.githubusercontent.com/1388961/70699251-200dc900-1cc9-11ea-8c7b-fd65e57ea11b.png)

**Comment by varjolintu** [comment] 2019-12-12 13:02
Duplicate of #704.

**Closed by varjolintu** 2019-12-12 13:02 UTC

**Comment by Ezwen** [comment] 2019-12-12 13:04
Sorry for the duplicate! I was searching with the wrong keywords.

**Comment by varjolintu** [comment] 2019-12-12 13:05
It was hard to find, so I modified the title and pinned the issue. No worries :)
