### ISSUE TITLE
"Key exchange was not successful" for Brave/Chrome browsers.

### ISSUE THREAD

**Issue by CrodenPT** [keepassxreboot/keepassxc-browser#1485] opened 2021-12-03 09:02 UTC
## Current Behavior
Both on Chrome and Brave browser, whenever I try to connect to the database, this message is displayed: "Key exchange was not successful."
Somehow the connection to the database doesn't seem to be working.
I followed the troubleshooting guide provided, but also seems that it didn't got fixed.
It's important to freeze, that I've installed Firefox to test the same behaviour, but was not reproducible. 
With Firefox I was able to connect to the database with no problems.
The support for Firefox, Chrome and/or Chromium are enable on KeePassXC.

## Steps to Reproduce (for bugs)
1. Click the KeePassXC extension on Brave/Chrome
2. Press the "Reload" button
3. The message "Key exchange was not successful." is displayed.

## Debug info
KeePassXC - unknown
KeePassXC-Browser - 1.7.10.1
Operating system: Win64
Browser: Chrome/Chromium 96.0.4664.45

**Comment by varjolintu** [comment] 2021-12-03 09:05
Duplicate of #1484. Please do not create new issues. Old ones can be reopened.

**Closed by varjolintu** 2021-12-03 09:05 UTC
Labels: duplicate
