### ISSUE TITLE
Version 1.8.3 Breaks browser integration / autofill

### ISSUE THREAD

**Issue by ongun-kanat** [keepassxreboot/keepassxc-browser#1751] opened 2022-10-25 12:35 UTC
Updating Keepass XC to 1.8.3 breaks browser integration. It seems like it is losing the handshake between the application and the extension. The issue exists on both Firefox and Chromium. I realized that there is a problem while using Firefox (my default browser) and then tested on Chromium. Chromium was working until I manually triggered the update to 1.8.3.

## Expected Behavior

Autofill should work

## Current Behavior

KeepassXC Browser is losing the connection between the application and the extension

## Steps to Reproduce (for bugs)

1. Load the browser and visit any page. I used https://kskmse.de and https://hepsiburada.com
2. Wait the autofill icon show up shortly and then disappear
  a. On Firefox the icon turns into a lost connection one: 
![image](https://user-images.githubusercontent.com/3601965/197773740-ca5a77eb-61cc-4a95-8927-60bc77230661.png)
  b. On Chromium it stays as green
4. Triggering the form fill using the right-click context menu doesn't work.

## Debug info

I use Windows 10 AMD64 with Keepass XC 2.7.3. Both browsers seem to generate similar logs in extension debug console.

Firefox v106.0.1:

```
KeePassXC-Browser: Connecting to native messaging host org.keepassxc.keepassxc_browser 2 [client.js:317:13](moz-extension://ebd6e01e-1a92-4433-b62e-13b953636469/background/client.js)
KeePassXC-Browser: Server public key: bKl+O5hcYtKrGqRQb5rJlzoiOGz2lWQDbdj/ndkEjn0= [keepass.js:449:17](moz-extension://ebd6e01e-1a92-4433-b62e-13b953636469/background/keepass.js)
[Error keepass.js:757] KeePassXC-Browser - 9: Key exchange was not successful. [global.js:178:13](moz-extension://ebd6e01e-1a92-4433-b62e-13b953636469/common/global.js)
[Error ] KeePassXC-Browser - Failed to connect: Unknown error [global.js:178:13](moz-extension://ebd6e01e-1a92-4433-b62e-13b953636469/common/global.js)
[Error init.js:66] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist. [global.js:178:13](moz-extension://ebd6e01e-1a92-4433-b62e-13b953636469/common/global.js)
```

Chromium v106.0.5249.119

```
[Error page.js:233] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist.
```

**Comment by varjolintu** [comment] 2022-10-25 12:46
Does the same happen with KeePassXC 2.7.1?

**Comment by varjolintu** [comment] 2022-10-25 14:23
Just tested this with Windows 10 where KeePassXC 2.7.1 was installed along with older Edge version. Updated KeePassXC to 2.7.3 and Edge to the latest version, and had no problems with it. Please see the [Troubleshooting Guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide) and report your findings, thanks.

**Comment by MarkJaroski** [comment] 2022-10-25 16:07
I'm also experiencing this behaviour.

[oboonakemofpalcgghocfoadofidjkkk-1666713987336.log](https://github.com/keepassxreboot/keepassxc-browser/files/9862049/oboonakemofpalcgghocfoadofidjkkk-1666713987336.log)

**Comment by varjolintu** [comment] 2022-10-25 16:23
See https://github.com/keepassxreboot/keepassxc/issues/8634 for checking if the issue is with the socket.

**Comment by varjolintu** [comment] 2022-10-25 16:26
@MarkJaroski Interesting. I haven't seen anything like that on my tests with multiple OS's. I highly suggest you shutdown KeePassXC and your browser, and also make sure `keepassxc-proxy` is killed before starting everything again. Also, are there popups visible on KeePassXC?

**Comment by MarkJaroski** [comment] 2022-10-25 16:28
The advice here solved it for me: 

https://github.com/keepassxreboot/keepassxc/issues/8634#issuecomment-1289080878 

Thanks @varjolintu for the link.

**Comment by varjolintu** [comment] 2022-10-25 18:36
Please try downgrading to 2.7.1 to narrow down the cause of the issue. Browsers should be restarted too.

**Comment by varjolintu** [comment] 2022-10-26 03:49
I finally got this reproduced with 2.7.3. Seems when the window is minimized or in the system tray, the connection drops. Doesn't really make sense, but I'm investigating it.

**Comment by Leseratte10** [comment] 2022-10-26 09:45
I have this same issue in KeepassXC. The suggestion by MarkJaroski didn't work for me, downgrading KeepassXC to 2.7.1 fixes the issue.

**Comment by varjolintu** [comment] 2022-10-26 09:50
The problem is fixed for 2.7.4, but it's necessary to use 2.7.1 meanwhile. Sorry for the trouble!

**Comment by MarkJaroski** [comment] 2022-10-26 13:11
> I have this same issue in KeepassXC, on Linux using Chrome. The suggestion by MarkJaroski didn't work for me, downgrading KeepassXC to 2.7.1 fixes the issue.

It stopped working for me too. It was only because of the restart.

**Comment by VeraSimon** [comment] 2022-10-26 15:49
Was running into this issue with KeePassXC 2.7.3, KeePassXC-Browser 1.8.3, and Firefox 106.0.1 on Windows 10 Pro 21H1. Reverting KeePassXC-Browser to 1.8.2.2 seems to have fixed it.

**Comment by varjolintu** [comment] 2022-10-26 15:51
@VeraSimon So KeePassXC 2.7.1 with extension 1.8.3 didn't work for you?

**Comment by VeraSimon** [comment] 2022-10-26 15:57
> @VeraSimon So KeePassXC 2.7.1 with extension 1.8.3 didn't work for you?

It was easier to revert the addon in the browser than juggle the version of KeePassXC I have installed on multiple machines and OSes, so I didn't try to revert the app. I also wasn't hitting any of the issues fixed in KeePassXC-Browser 1.8.3, so went with the quicker troubleshooting/break-fix. Just figured you might like to know that particular combo was working as expected.

**Comment by sonalvrioss-svyatos** [comment] 2022-10-27 04:04
Having the same problem here. 

My debug info:
```
KeePassXC - 2.7.3
KeePassXC-Browser - 1.8.3
Operating system: Win64
Browser: Mozilla Firefox 106.0
```

Below is my debug log:
```
KeePassXC-Browser: Connecting to native messaging host org.keepassxc.keepassxc_browser [client.js:317:13](moz-extension://8050304e-1486-43f8-ab0b-c6c9de2e67ad/background/client.js)
KeePassXC-Browser: Server public key: FI41QO+lq0fVOvgCnHbiVu1eLCvSOo2eaTgmgwKAWko= [keepass.js:449:17](moz-extension://8050304e-1486-43f8-ab0b-c6c9de2e67ad/background/keepass.js)
[Error ] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist. [global.js:178:13](moz-extension://8050304e-1486-43f8-ab0b-c6c9de2e67ad/common/global.js)
[Error ] KeePassXC-Browser - No content script available for this tab. 2 [global.js:178:13](moz-extension://8050304e-1486-43f8-ab0b-c6c9de2e67ad/common/global.js)
[Error ] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist. [global.js:178:13](moz-extension://8050304e-1486-43f8-ab0b-c6c9de2e67ad/common/global.js)
[Debug ] KeePassXC-Browser - Found 2 entries for url https://purelymail.com/user/login [global.js:170:13](moz-extension://8050304e-1486-43f8-ab0b-c6c9de2e67ad/common/global.js)
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:22:1
[Error ] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist. 8 [global.js:178:13](moz-extension://8050304e-1486-43f8-ab0b-c6c9de2e67ad/common/global.js)
[Error init.js:66] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist. 7 [global.js:178:13](moz-extension://8050304e-1486-43f8-ab0b-c6c9de2e67ad/common/global.js)
```

**Comment by traviss64** [comment] 2022-10-27 06:03
Does reverting back to older version result in default settings of the application? Like setting up the extension link and the settings we made?

**Comment by varjolintu** [comment] 2022-10-27 06:04
@traviss64 Connection settings are stored in your database, not in KeePassXC.

**Comment by chrissi55** [comment] 2022-10-27 12:16
same here issues with browser integration since keepass 2.7.3 <-> keepass xc browser 1.8.3

system is:

KeePassXC - 2.7.3
KeePassXC-Browser - 1.8.3
Operating system: Linux x86_64
Browser: Chrome/Chromium 107.0.0.0

**Comment by usego** [comment] 2022-10-27 14:17
I have the following error message for browser plugin in chrome dev console for 2.7.3 + 1.8.3  win 11:

Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'sha256-4nJ8uLezzRE3SiBFdkVN/uNwV9YTOGCqRXg6AvB5rCY='". Either the 'unsafe-inline' keyword, a hash ('sha256-UD5WN2QEhRDEZ6vkLdHKFlkHwzbemzW2ppJiOLooI8o='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by TopHatProductions115new** [comment] 2022-10-27 21:56
I'm experiencing similar behaviour on all websites I visit. Have to manually copy-paste to use my credentials.

**Comment by varjolintu** [comment] 2022-10-30 12:21
KeePassXC 2.7.4 fixes this issue.

**Closed by varjolintu** 2022-10-30 12:21 UTC
Labels: bug
