### ISSUE TITLE
KeePassXC Browser: Confirm Access - Too Liberal in Some Cases

### ISSUE THREAD

**Issue by b0ssi** [keepassxreboot/keepassxc-browser#733] opened 2020-01-03 06:08 UTC
## Expected Behavior

A given database has two entries:

* entry A specifies `https://www.example.com`
* entry B specifies `https://foo.example.com`

When browsing to entry B (`https://foo.example.com`), the *Confirm Access* dialog (that pops up with a set of entries in the database matching the current tab's domain) should **only** list **entry B**.

### Possible Solution(s)
Two ideas come to mind:
**A**: stricter filtering, so that *entry A* does not get picked up by other sublevel domains on `example.com`.

**B**: Not mutually exclusive to *A*: Have more control over the entries in the *Confirm Access* pop-up dialog, so that the *Confirm*/*Deny* action can be applied to selected entries in the list. As it currently stands, the dialog would display both entries, A and B, forcing the user to either deny every time manually, or permanently deny *all* or allow *all* (which you wouldn't want in many/most cases!). **In addition**: Some control over the ACL in an entry's properties (that stores the domains) would be great, to make adjustments, as there is no way to amend changes at the moment, other than deleting the properties completely. Some interface somewhere would be great.

## Current Behavior

The dialog also lists *entry A*, which is unexpected, may hinder user experience and might be of concern from a security pov (i.e. if different subdomains need to store credentials isolated from each other).

## Steps to Reproduce (for bugs)

1. Issue present in `2.5.1`
2. Create two entries as described above with the domain name, TLD and two (or more) different sub-level domains, with at least one being `www`
3. Browse to one of the URIs not being located at sub domain `www`
4. Observe how the `www` sub domain entries get requested access to

## Debug info

KeePassXC - 2.5.1
KeePassXC-Browser - 1.5.4
Operating system: Arch Linux
Browser: Firefox 71.0 (64-bit)

**Comment by varjolintu** [comment] 2020-01-03 06:11
This is already fixed, and the issue is a duplicate of #686.

**Closed by varjolintu** 2020-01-03 06:11 UTC

**Comment by b0ssi** [comment] 2020-01-03 06:20
Terrific @varjolintu, had a quick look for existing reports but hadn't bumped into that one, cheers.

**Comment by b0ssi** [comment] 2020-01-06 15:30
@varjolintu I have since tested 2.5.2 and, while most of the flaky behavior seems fixed; however, a variant of the issue described above still seems to persist: Given two entries with URLs set to:

a) https://example.com
b) https://foo.example.com

entry b) *and* a) show up when browsing to `foo.example.com`. Should this be the defined behavior? a) would in most cases be a different service than b), I could imagine.

**Comment by droidmonkey** [comment] 2020-01-06 15:38
That is expected behavior. We present the less specific case otherwise if you defined only example.com you would not see credentials if you went to foo.example.com. With the new confirm access dialog, excluding these cases will be trivial with one button press.

**Comment by varjolintu** [comment] 2020-01-06 16:12
In short, entry with https://example.com will match `https://*.example.com` and entry with https://foo.example.com will match `https://*.foo.example.com` etc.

**Comment by b0ssi** [comment] 2020-01-07 04:25
Thanks for clarifying @droidmonkey @varjolintu - I guess that makes sense in most cases. I have a few websites that use independent sets of credentials on the main domain (`example.com`) and subdomains (`foo.example.com`) that would ideally be treated as distinct, isolated websites.

I can see how hard separation of the two could lead to other problems though, and you mention a new confirm access dialog coming soon that allows for this distinction to be made, which sounds like it'll cover this use case I mention, perfect (I've only tested `2.5.2` so far).
