### ISSUE TITLE
Firefox 66.0.3 64bit 

### ISSUE THREAD

**Issue by htttito** [keepassxreboot/keepassxc-browser#489] opened 2019-04-22 21:02 UTC
Hi Keepass Team!
In the new Firefox the Add-On has no function.
And in some websites, there are problems (push some button ...)
You also can not see a logo or something else...

System is Ubuntu 18.04 and up to date....

Thanks!
Tito

**Comment by varjolintu** [comment] 2019-04-23 03:38
Duplicate of #486.

**Closed by varjolintu** 2019-04-23 03:38 UTC
Labels: duplicate
