### ISSUE TITLE
unhelpful error "Key exchange was not successful." when native messaging host not set up

### ISSUE THREAD

**Issue by khazhyk** [keepassxreboot/keepassxc-browser#559] opened 2019-05-31 03:56 UTC
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

it connects to the database

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

first:
"KeePassXC-Browser has encountered an error:

Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. "

then click "reload" gives:
"KeePassXC-Browser has encountered an error:

Key exchange was not successful. "

This happens if keepassXC is open or closed, suggesting to me something broken within the browser extension 

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. start firefox with keepascx-browser
2. click the icon and press reload
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
unusable

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.4.1
KeePassXC-Browser - 1.4.5
Operating system: MacIntel
Browser: Mozilla Firefox 67.0

**Comment by khazhyk** [comment] 2019-05-31 04:05
debug console shows:

Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:1003:13
Failed to connect: Unknown error keepass.js:979:13
Error: Could not establish connection. Receiving end does not exist.

- issue was keepassxc was enabled for chrome but not firefox...

so I guess, change this to... maybe handle this error and give more helpful error message. Perhaps... "KeepassXC is not configured, please set it up in preferences > browser integration and make sure <browser> is checked" or something

**Comment by varjolintu** [comment] 2019-05-31 05:06
Those error messages have been changed few months ago. The problem here is that the same error message is used for several situations, and there's no way to distinguish them.

**Comment by tjuerges** [comment] 2019-06-01 12:06
Independent of whatever the error message stands for, I see the same error message on MacOS with 1.4.5/2.4.2 and Chrome.

Was this ever tested?

**Comment by dxdc** [comment] 2019-06-01 14:46
^^ same here.

**Comment by varjolintu** [comment] 2019-06-01 15:24
Stable 2.4.2 release had a problem with linking keepassxc-proxy so the extension is not the only problem here. The next extension release fixes the rest of reconnect problems. It's recommended to disable it if you encounter any problems. A warning text about it being experimental will be added.

**Comment by dxdc** [comment] 2019-06-01 15:29
@varjolintu I tried deleting the db in the browser extension, but when I press 'Connect' now nothing happens still. 

I tried disabling the proxy setting under 'Advanced' in the 2.4.2 Browser preferences, but that just causes an icon to appear/disappear in the dock every 0.5 sec or so.

Was this all covered by the new release?

KeePassXC - unknown 
KeePassXC-Browser - 1.4.5 
Operating system: MacIntel 
Browser: Chrome/Chromium 74.0.3729.169

**Comment by varjolintu** [comment] 2019-06-01 15:43
@dxdc Without the proxy the connection with KeePassXC is direct. This means KeePassXC must be closed and the browser launches it at connect/reconnect. Make sure auto-reconnect is disabled.

**Comment by dxdc** [comment] 2019-06-01 15:55
@varjolintu I tried that; it's completely unusable. Keepasxc (proxy application) just keeps relaunching/quitting over and over and over. I had to disable the chrome extension, which wasn't easy with the keepassxc window taking focus every 0.5 sec.

**Comment by varjolintu** [comment] 2019-06-01 15:59
@dxdc This is because of the wrong linking I said earlier. Only workaround for that is to load the previous version (or copy the proxy inside that package to the new one) until an update is uploaded.

**Comment by dxdc** [comment] 2019-06-01 16:07
@varjolintu great suggestion.

```bash
cp /Volumes/KeePassXC/KeePassXC.app/Contents/MacOS/keepassxc-proxy /Applications/KeePassXC.app/Contents/MacOS/keepassxc-proxy
```

worked perfectly for now.

**Comment by varjolintu** [comment] 2019-06-02 05:33
Another solution is to install libsodium via Homebrew.

**Comment by NullEnt1ty** [comment] 2019-06-03 09:05
```
brew install libsodium
```

solved my problems on macOS. Thank you, @varjolintu!

**Comment by varjolintu** [comment] 2019-06-03 09:10
And a third workaround that doesn't need any installing (https://github.com/keepassxreboot/keepassxc/issues/3209#issuecomment-498146146):

```
install_name_tool -change /usr/local/opt/libsodium/lib/libsodium.23.dylib "@executable_path/../Frameworks/libsodium.23.dylib" /Applications/KeePassXC.app/Contents/MacOS/keepassxc-proxy
```

**Comment by chundychang** [comment] 2019-06-04 14:55
I'm experiencing the same problem after I installed the newest version of Keepass (2.4.2). I re-installed the chrome extension, re-downloaded the newest version of Keepass (32 bit to match operating system), made sure the "enable browser integration" setting was on. Also, I went into the "Connected Databases" tab in KeepassXC Browser's settings and noticed that there were no connected databases there. I tried to press the "connect" button but nothing happened. 

debug info below:
KeePassXC - 2.4.2
KeePassXC-Browser - 1.4.6 
Operating system: Win32 
Browser: Chrome/Chromium 74.0.3729.169

I am totally new to coding, how do you implement the third workaround for windows 32 @varjolintu?

**Comment by varjolintu** [comment] 2019-06-04 17:29
Are you using the portable version? If so, see https://github.com/keepassxreboot/keepassxc-browser/issues/456.

**Comment by chundychang** [comment] 2019-06-04 18:07
@varjolintu I am using portable, but I don't understand where to find the registry key.

**Comment by varjolintu** [comment] 2019-06-04 18:11
@chundychang See https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide :)

**Comment by buzzik** [comment] 2019-06-17 10:04
@varjolintu Oh cmon, peoples use portable versions when thay haven't admin privileges.
After upgrade to 2.4.3  i getting error "Key exchange was not successful" in Chrome and Firefox.
Is there any way to fix it without admin privileges (that is needed to edit registry)

**Comment by varjolintu** [comment] 2019-06-17 10:23
@buzzik Registry is needed to be modified to include the location of Native Messaging script file locations for Chrome and Firefox. If you cannot edit the registry, there's little you can do.

**Comment by varjolintu** [comment] 2019-07-04 08:52
@buzzik Btw, have your tried to disable the support for your browser and then re-enable it from the KeePassXC settings?

**Comment by stratacast** [comment] 2019-07-19 23:06
> @buzzik Btw, have your tried to disable the support for your browser and then re-enable it from the KeePassXC settings?

This was the solution for me for now

**Comment by RexTC** [comment] 2019-08-07 23:49
Just found the problem maybe on the KeepassXC extension coding or maybe KeepassXC browser.
I have solved this issue by **_changing the folder name length(rename to shorter or move it to reduce folder string length)_** for the too long text string will be problem for extension or XC browser to processing it.
I am 100% sure this is a bug in either one.
I am using portable version of XC browser app,
I also suspect it maybe cause by the partition format of USB that will cause the program to interpret the location of binary file.
I have tested this and duplicate the same issue in different machines(Windows 10), but this does not happen in Ubuntu(Linux).

**Comment by varjolintu** [comment] 2019-08-08 05:50
@RexTC Thank you for the info. Need to test that. The folder name is only used in the Native Messaging JSON script and in the registry. It's also possible that Native Messaging doesn't handle long names properly, but at this point it's hard to say.

**Comment by AustinLiu1988** [comment] 2019-11-29 07:09
> y

what should I modify after I found "org.keepassxc.keepassxc_browser"

**Comment by varjolintu** [comment] 2019-11-29 07:29
@AustinLiu1988 The path, if it's wrong.

**Comment by intika** [comment] 2019-12-09 23:37
Just for the record... was going nut with this issue since a long time and have just find the time to do some debugging and figure it out... i am using **chromium**, (ungoogle-chromium) + **Linux**... but i'll post the solution according to **Firefox** and **other systems** as well... this may help some one with a similar issue...

First thing first here is the detailed documentation (reading it is what lead me to the solution...)
- [Chromium/Chrome Native Messaging](https://developer.chrome.com/extensions/nativeMessaging)
- [Mozilla Native Messaging](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging)
- [KeepassXC-Browser Troubleshooting Wiki](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide)

Also under chromium an easy way to debug is to open **chrome://extensions/** select *developer mode* at the top right then click *Inspect views background...* under the square of KeepassXC extension... also under *details* button you may select *collect errors*... 

Before going further the first thing to do is to follow the [KeepassXC-Browser Troubleshooting Wiki](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide) and update/fix the json manifest file like described there 

Then (and here is where my config/mistake got me stucked) the *native messaging* system have several location where it can be edited **and or limited/denied** for instance for chromium+linux a manifest json policy under `/etc/chromium/policies/managed/manifest.json` that contains `"NativeMessagingUserLevelHosts": false,` will completely block the system and will result in giving `Key exchange was not successful` error in that case just change the value to true or just remove that line and voila :)

The liked documentations describe different locations for the different policies, different browsers and os. 

I'll probably update the wiki to provide a full troubleshooting of the native message system, sometime for some advanced setup, the manifest under the user location is not enough (like my case)

Also during the debugging you may keep the task manager open to see if the browser run keepassxc-proxy binary... also the feature need to be enabled on the KeepassXC settings.

**Comment by varjolintu** [comment] 2019-12-10 06:39
@intika I had no idea the whole native messaging system can be limited and solved by editing the policies JSON. Is this behaviour specific to Ungoogled Chromium?

**Comment by intika** [comment] 2019-12-10 17:09
@varjolintu no it's not specific to Ungoogled Chromium but to any Chromium based browser, in any OS... i believe Firefox have the same policy function

**Comment by hrvojegolcic** [comment] 2020-02-24 00:33
Had the same issue on Windows 8.1 but only with portable KeePassXC. Otherwise works fine

**Comment by masi** [comment] 2020-03-22 15:05
Happens for me on Win10 with FF 74.0 + KeePassXC-Browser 1.6.0 2and KeePassXC 2.5.3. But this is just the current setup. I don't recall with what version the connection started to fail.

As Hrvoje Golčić I am using a portable installation of KeePassX.

**Comment by moeffju** [comment] 2021-02-17 17:26
This has started happening to me seemingly at random a day or two ago. 

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.6
Operating system: Win64
Browser: Mozilla Firefox 86.0

Tried toggling Browser Integration, restarting KPXC, all to no avail.

**Comment by varjolintu** [comment] 2021-02-17 17:36
@moeffju Any messages in the JavaScript console, or background page console (you can find it from `about:debugging`)?

**Comment by moeffju** [comment] 2021-02-18 07:17
@varjolintu I was looking for the debug console but couldn't find it, and then restarted the browser again before seeing your response. That restart seemed to have fixed it however. I did disconnect the database beforehand as well. If it happens again I'll make sure to check the debug console.

**Comment by Ferk** [comment] 2021-03-05 10:29
I have the same issue, but here is in Windows. I had no issued with Google Chrome and KeepassXC.

However, I needed to switch to use Firefox and even though the Chrome connection works flawlessly, Firefox keeps giving the same "Key exchange was not successful".

I tried to "Disconnect all browsers" to see if the previous Chrome connection was interfering, but even after doing that I cannot connect from Firefox. I tried again to make a new connection from Chrome and it worked again, so I'm wondering if this is a Firefox issue.

**Comment by Ferk** [comment] 2021-03-05 10:34
I went into about:devtools-toolbox?id=keepassxc-browser%40keepassxc.org&type=extension

Then I was able to see the logs for the extension, which constantly spout the following lines:

```
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:1059:13
Failed to connect: Unknown error keepass.js:1029:13
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:1059:13
Failed to connect: Unknown error keepass.js:1029:13
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:1059:13
Failed to connect: Unknown error keepass.js:1029:13
```
```

**Comment by varjolintu** [comment] 2021-03-05 12:51
@Ferk Have you checked out the [Troubleshooting Guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide)?

**Comment by JightningZ** [comment] 2021-05-01 09:28
I had this issue and was able to solve it. I was using the extension on Edge and wanted to start using Chrome.  After uninstalling everything and going through the troubleshooting guide I finally figured out how to get it to work.

I am not using the portable version.  Under Application Settings -> Browser Integration -> Make sure you have your browser type checked.  I only had Edge checked.  Once I checked the Chrome box it started working for me!

**Comment by Bohaska** [comment] 2021-05-06 03:28
Also having this problem. I checked and browser integration was on for all browsers.
KeePassXC-Browser - 1.7.8.1
Operating system: MacIntel
Browser: Chrome/Chromium 87.0.4280.141

**Comment by Sarlay** [comment] 2021-05-17 07:41
I have the same issue but once I reboot my computer (w10) the issue is gone and comes back after some time.
os: W10
browser: chromium 92.0.4490.0
extension: 1.7.8.1
keepassxc: unknow
I also did those [steps](https://github.com/keepassxreboot/keepassxc/issues/4657#issuecomment-618960627) and everything seems to be ok (the path points to C:\\Program Files\\KeePassXC\\keepassxc-proxy.exe)
The allowed_origins matches the chrome-extension id

**Comment by sakthimaan** [comment] 2021-08-20 06:56
2021.. still facing this error in firefox

![image](https://user-images.githubusercontent.com/14888257/130193012-2dbadcbc-2d87-4a35-9efa-3be02a5feea4.png)

**Comment by varjolintu** [comment] 2021-08-20 06:59
> 2021.. still facing this error in firefox
> 
> ![image](https://user-images.githubusercontent.com/14888257/130193012-2dbadcbc-2d87-4a35-9efa-3be02a5feea4.png)

See my first reply in this thread. Things haven't changed.

**Comment by iammursalin** [comment] 2021-11-06 13:11
I am facing this error in Brave.

**Comment by varjolintu** [comment] 2021-11-06 13:20
> I am facing this error in Brave. On Firefox it's working.

Try to enable support for Chrome and Chromium. Then try again.

**Comment by Mayurifag** [comment] 2021-11-07 16:42
For any people using librewolf on linux, this dirty hotfix may help you

```sh
ln -s ~/.mozilla/native-messaging-hosts ~/.librewolf/native-messaging-hosts
```

source: https://github.com/keepassxreboot/keepassxc/issues/6907

**Comment by varjolintu** [comment] 2021-11-07 17:07
> For any people using librewolf on linux, this dirty hotfix may help you
> 
> ```shell
> ln -s ~/.mozilla/native-messaging-hosts ~/.librewolf/native-messaging-hosts
> ```
> 
> source: [keepassxreboot/keepassxc#6907](https://github.com/keepassxreboot/keepassxc/issues/6907)

..or you can just use the Custom Browser option in KeePassXC's Browser Integration settings, Advanced tab.

**Comment by rafalglowacz** [comment] 2021-11-17 10:25
I just started getting this error in Firefox after a fresh Ubuntu installation. I hadn't used FF for a while but I remembered that it worked flawlessly before. 

Apparently FF is now installed with snap in Ubuntu and snaps are not supported by KeePassXC, so the solution was to simply:

```
sudo snap remove firefox
sudo apt install -y firefox
```

**Comment by RebelCoderRU** [comment] 2021-11-17 11:53
I am on Linux and I use Brave browser, but **beta** and **nightly** builds.

![Screenshot_20211117_115233](https://user-images.githubusercontent.com/20476773/142195702-b0074c21-d386-43fd-8dec-f7abe24cc5f3.png)

It works only on the main Brave browser (when executable is called brave/brave-browser)

It **does not** work if the executable name is: **brave-beta** or **brave-nightly**

Is there a way to make it work for those two? Is this something that can be configured from here:

![image](https://user-images.githubusercontent.com/20476773/142195850-ae0b6e72-38ac-47b2-b2f4-a69d51385695.png)

If yes, how can this be done?

**Comment by varjolintu** [comment] 2021-11-17 11:58
@RebelCoderRU Check what path Brave beta/nightly uses. It's probably `~/.config/BraveSoftware/Brave-Browser-Beta/NativeMessagingHosts` or something similar.

**Comment by RebelCoderRU** [comment] 2021-11-17 12:06
> @RebelCoderRU Check what path Brave beta/nightly uses. It's probably `.config/BraveSoftware/Brave-Browser-Beta/NativeMessagingHosts` or something similar. Enter that path to the config.

Hey! Yes, I just did try, and it still does not work.

A few issues:
1. Custom config only has FF & Chromium (can this be why custom Brave config is not being picked up?):

https://user-images.githubusercontent.com/20476773/142197558-12fa6bef-2d30-4b6b-89aa-575711def25c.mp4

2. Those folders supposed to be empty?:
![Screenshot_20211117_120355](https://user-images.githubusercontent.com/20476773/142197645-2dff90fc-346e-4f2e-8f74-68e75b23bf93.png)
![Screenshot_20211117_120323](https://user-images.githubusercontent.com/20476773/142197647-099af86e-b3cb-46a6-856e-22127d67d62a.png)

**Comment by varjolintu** [comment] 2021-11-17 12:10
@RebelCoderRU Chromium here means it's a Chromium-based browser, just like Brave. You can use the whole path you can see in `pwd` in the config page.

**Comment by RebelCoderRU** [comment] 2021-11-17 12:19
> @RebelCoderRU Chromium here means it's a Chromium-based browser, just like Brave. You can use the whole path you can see in `pwd` in the config page.

Thanks! That worked. Trying to figure out how to enable more than 1 browser that way now. I need Nightly and Beta.

**Comment by varjolintu** [comment] 2021-11-17 12:20
> > @RebelCoderRU Chromium here means it's a Chromium-based browser, just like Brave. You can use the whole path you can see in `pwd` in the config page.
> 
> Thanks! That worked. Trying to figure out how to enable more than 1 browser that way now. I need Nightly and Beta.

The easiest way to do that is to copy the script file to each folder, or make a symbolic link.

**Comment by RebelCoderRU** [comment] 2021-11-17 12:23
> > > @RebelCoderRU Chromium here means it's a Chromium-based browser, just like Brave. You can use the whole path you can see in `pwd` in the config page.
> > 
> > 
> > Thanks! That worked. Trying to figure out how to enable more than 1 browser that way now. I need Nightly and Beta.
> 
> The easiest way to do that is to copy the script file to each folder, or make a symbolic link.

Looks like setting `pwd` for one version, enabling everything, setting the `pwd` for another and also enabling works. So I enabled one after another that way. But your solution also is something I will try if this will stop working. Thank you.

**Comment by CubicrootXYZ** [comment] 2021-12-05 19:04
For those using the firefox that came with the ubuntu image:
```
$ sudo snap remove firefox
$ apt install firefox
```

This is described in the troubleshooting, however not with this exact commands.

**Comment by cjpoor** [comment] 2022-05-11 23:55
The error message should be changed as suggested by Khazhyk on 31 May 2019.
Copied from Khazhyk:

debug console shows:

Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:1003:13
Failed to connect: Unknown error keepass.js:979:13
Error: Could not establish connection. Receiving end does not exist.

so the issue was keepassxc was enabled for chrome but not firefox...

so I guess, change this to... maybe handle this error and give more helpful error message. Perhaps... "KeepassXC is not configured, please set it up in preferences > browser integration and make sure <browser> is checked" or something

This problem arose for me when transferring database from linux machine to Macbook.
Double-clicking the database opened KeepassXC on Macbook with no prompt to configure.
Attempting to connect for Firefox password entry gave error message: 
"Failed to connect"
Please add something like Khazhyk suggested:
"KeepassXC is not configured, please set it up in preferences > browser integration and make sure <browser> is checked"

**Comment by varjolintu** [comment] 2022-05-12 04:08
@cjpoor These two were just recently added to the next version:
https://github.com/keepassxreboot/keepassxc-browser/pull/1604
https://github.com/keepassxreboot/keepassxc-browser/pull/1606

**Comment by CubicrootXYZ** [comment] 2022-06-08 16:57
@topwebmaster for ubuntu 22.04 the apt package is some intermediate solution that indeed is blocking the keepass plugin to connect to keepass. You can install firefox directly from mozilla by downloading it here: https://www.mozilla.org/en-US/firefox/all/#product-desktop-release

**Comment by georgehank** [comment] 2022-07-02 00:19
Just ran into this myself.  Restarted browser (after making sure KeepassXC itself was the newest versions).  Same error.
Then restarted KeepassXC, and that "fixed" it.

**Comment by ziggurad** [comment] 2022-08-09 07:08
Ubuntu 22.04
KeePassXC-Browser Version: 1.8.1
Keepassxc 2.7.1

Firefox 103.0.1 - did not work "Key exchange was not successful."
Chromium Version 104.0.5112.79 (Official Build) snap (64-bit) - did not work "Key exchange was not successful."
Chrome Version 103.0.5060.134 (Official Build) (64-bit) - works

any advice?

**Comment by CubicrootXYZ** [comment] 2022-08-09 07:16
> Ubuntu 22.04
> KeePassXC-Browser Version: 1.8.1
> Keepassxc 2.7.1
> 
> Firefox 103.0.1 - did not work "Key exchange was not successful."
> Chromium Version 104.0.5112.79 (Official Build) snap (64-bit) - did not work "Key exchange was not successful."
> Chrome Version 103.0.5060.134 (Official Build) (64-bit) - works
> 
> any advice?
> 
> 
> 
> 

Snap is using some containerization on its packages which might interfere with your browser talking to other components on your system. Try installing the browser directly from the official sources instead of using snap or apt.

**Comment by varjolintu** [comment] 2022-08-09 08:18
@ziggurad See https://github.com/keepassxreboot/keepassxc-browser/issues/1426.

**Comment by ziggurad** [comment] 2022-08-09 08:21
@CubicrootXYZ thank you for your response/

When I used "Easy Script to download and run latest Linux build:" from: https://www.chromium.org/getting-involved/download-chromium/ integration for KeepassXC started to work.

Unfortunately, Chromium running this way must always be launched from the console, the application cannot be added to the preferred (it will always be at the bottom of the list in Ubuntu Dock). Is there any solution to this?

@varjolintu thanks for link!

**Comment by varjolintu** [comment] 2022-08-09 08:26
In the future, please refer your issues to a correct thread. This one already has two or three different issues.
The latest extension version already directs the user to the Getting Started and Troubleshooting Guide on error situations, so closing this as the original issue is already improved.

**Closed by varjolintu** 2022-08-09 08:26 UTC
Labels: bug

**Comment by berot3** [comment] 2023-02-16 16:04
> removing the extension. Closing the browser and install again the extension.

Thanks @abathelt it did! just re-installing the extension did not help, I also had to restart the browser.
I hope it will stay connected now! :)

**Comment by saywebsolutions** [comment] 2023-09-13 18:04
There are a variety of issues being discussed on this page / under the umbrella of this set of common error messages, but in my case I encountered this attempting to setup the extension with `brave-browser-nightly` on Ubuntu 20.04.6 LTS.

I finally got everything to work by checking the 'Brave' checkbox under 'Enable integration for these browsers' setting in the main KeepassXC Tools -> Settings -> Browser Integration settings.

Then setting up the following symlink:
`ln -s ~/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json ~/.config/BraveSoftware/Brave-Browser-Nightly/NativeMessagingHosts/`

**Comment by FaintShadow** [comment] 2024-10-22 12:15
If you're having trouble connecting KeePassXC with Brave browser on Fedora 40, I've found a solution that might help. I recently encountered this exact issue where KeePassXC wouldn't connect to Brave (standard release), and neither reinstalling the extension nor trying custom browser paths solved the problem. After some troubleshooting, I discovered the issue lies in a configuration file located at `~/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json`. The key is to ensure this file contains the correct proxy path: `"/usr/bin/keepassxc-proxy"` at least for me. The problem probably occured due to permission issues or incorrect proxy paths in the native messaging configuration.

If you are installing KeePassXC on Fedora I would recommend selecting this repo:
![image](https://github.com/user-attachments/assets/05089b9a-3921-4a5a-b5fb-b881a0c3f0bc)

**Comment by schizovivek** [comment] 2025-01-01 19:52
> If you are installing KeePassXC on Fedora I would recommend selecting this repo: ![image](https://github.com/user-attachments/assets/05089b9a-3921-4a5a-b5fb-b881a0c3f0bc)

for anyone on fedora. this is how i resolved my issue. thanks @FaintShadow ! Looks like installing the RPM package is the only way for it to work
