### ISSUE TITLE
No logins found - Firefox

### ISSUE THREAD

**Issue by flanger001** [keepassxreboot/keepassxc-browser#535] opened 2019-05-08 15:09 UTC
## Expected Behavior
Browser extension finds login for site

## Current Behavior
Browser extension does not find login for site
No logins found

## Steps to Reproduce (for bugs)
1. Open Firefox
2. Connect to db (either manually or automatically)
3. Visit site that has entry in the db, in this case https://www.reddit.com
4. I browsed manually to reddit.com/login so as to avoid the ajax form issues
5. Click in username field, expect to see username dropdown
6. Right click username field, KeepassXC-Browser > Fill Username and Password
7. No logins found

## Debug info
KeePassXC - 2.4.1
KeePassXC-Browser - 1.4.3
Operating system: Mac
Browser: Firefox 66.0.5
I have Firefox Multi-Account Containers but this behavior occurs whether it's enabled or not

I also tried debugging it using Firefox's extension debugging but all I get is "Error 15: No logins found." No idea where it's actually failing.

**Comment by droidmonkey** [comment] 2019-05-08 15:11
Does your entry in the database have https in front of the url?

**Comment by flanger001** [comment] 2019-05-08 15:14
@droidmonkey Yep!

**Comment by varjolintu** [comment] 2019-05-08 15:20
Change your entry's URL to `https://reddit.com` and try again.

**Comment by flanger001** [comment] 2019-05-08 15:22
@varjolintu No dice. Also, why would it not work if the entry was `https://www.reddit.com` and I browsed to `https://www.reddit.com/`?

**Comment by varjolintu** [comment] 2019-05-08 15:23
I cannot reproduce it. Reddit (the old.reddit.com included) works just fine for me.

**Comment by flanger001** [comment] 2019-05-08 15:25
I have these extensions:

* KeepassXC-Browser
* Facebook Container
* Firefox Multi-Account Containers
* 1Password Extension
* uBlock Origin
* Reddit Enhancement Suite

That's it.

**Comment by flanger001** [comment] 2019-05-08 15:30
I should add that I've tried all the steps here: https://keepassxc.org/docs/keepassxc-browser-migration/

And this is what my settings look like

![Screen Shot 2019-05-08 at 11 29 28 AM](https://user-images.githubusercontent.com/1645017/57387595-a044dc80-7184-11e9-878b-490e2a1a26d3.png)
![Screen Shot 2019-05-08 at 11 29 22 AM](https://user-images.githubusercontent.com/1645017/57387602-a20ea000-7184-11e9-9f75-0bf21a6ff843.png)

**Comment by flanger001** [comment] 2019-05-08 15:38
Ok, so I just noticed something else with the entry:

My Reddit entry had expired. I changed the expiration to a date in the future and the login started working. Then I changed the expiration back to a past date and the login stopped working again.

Is this expected behavior?

**Comment by droidmonkey** [comment] 2019-05-08 15:46
That makes sense to me

**Comment by flanger001** [comment] 2019-05-08 15:48
Hmm, in that case I'd say without any other indication that's a bug. Password "expiration" is more of a thing to notify the user to regularly change passwords and shouldn't prevent an otherwise valid password from being filled in imo.

**Comment by varjolintu** [comment] 2019-05-08 16:16
This behaviour was fixed with https://github.com/keepassxreboot/keepassxc/issues/2111.

In my opinion, if the password is expired, and you have set it so, it shouldn't be used manually or by the extension.

**Comment by flanger001** [comment] 2019-05-08 16:18
@varjolintu I would agree with you but that expectation is not ever set implicitly or explicitly, so whether it is a bug or not, it _feels_ like a bug. I assumed expiration was more of a reminder to the user and not something to base behavior on.

**Comment by flanger001** [comment] 2019-05-08 16:20
As an additional update, I tried this with Twitter.

Twitter entry is `https://twitter.com` and has an expiration date of May 22, 2019. I browsed to https://twitter.com and the extension isn't finding the entry.

**Comment by flanger001** [comment] 2019-05-08 17:58
Update to previous update: I opened up the debug tool and I keep getting `Error 8: KeePassXC association failed, try again` as the error. Database is open, the Twitter entry exists.

**Comment by droidmonkey** [comment] 2019-05-08 18:13
@varjolintu perhaps we can add a setting such as "Return expired credentials" which is default off. Either that or return expired credentials, but annotate the title with ```(expired)``` such that it displays like that in the browser. The latter option would be nice to indicate to the user they need to update their password.

**Comment by varjolintu** [comment] 2019-05-09 03:47
@droidmonkey That could be done.

**Comment by varjolintu** [comment] 2019-05-09 05:56
Here's the KeePassXC side PR: https://github.com/keepassxreboot/keepassxc/pull/3134
And KeePassXC-Browser support for it: https://github.com/keepassxreboot/keepassxc-browser/pull/537

**Comment by flanger001** [comment] 2019-05-09 13:08
Thank you both!

**Closed** 2019-05-24 09:02 UTC
