### ISSUE TITLE
Keypress event should be triggered for last character of each field

### ISSUE THREAD

**Issue by idontusenumbers** [keepassxreboot/keepassxc-browser#861] opened 2020-04-16 07:56 UTC
## Expected Behavior

Login button is clickable

## Current Behavior

Login button is disabled. It is enabled upon keypress including pressing an arrow key and not actually changing the text.

## Possible Solution

Trigger keypress event upon populating the field

## Steps to Reproduce (for bugs)

1. Open pnc.com with saved password
2. Try to click login button

## Debug info

KeePassXC - 2.5.3
KeePassXC-Browser - 1.6.2
Operating system: MacIntel
Browser: Chrome/Chromium 80.0.3987.163

**Comment by droidmonkey** [comment] 2020-04-16 10:54
Agree and same for password fields. Some sites think they are smart but really just dumb.

**Comment by varjolintu** [comment] 2020-04-16 14:45
I have a hard time to get this work 100% of the fills. At `pnc.com` it works if I fill it quickly after a page reload. If a wait a little, dispatcing the event has no use.

You can use this branch to test it:
https://github.com/keepassxreboot/keepassxc-browser/tree/fix/dispatch_keydown_on_fill

**Comment by varjolintu** [comment] 2020-08-01 06:19
Just tested this with my refactor branch (not public yet). This bug will be fixed with 1.7.0.

**Comment by idontusenumbers** [comment] 2020-08-01 16:58
I noticed pnc.com seems to be working now so they might have fixed it on their end.

Another idea: enabling submit button after populating fields

**Comment by varjolintu** [comment] 2021-01-18 05:04
I cannot reproduce this anymore.

**Closed by varjolintu** 2021-01-18 05:04 UTC
Labels: bug
