### ISSUE TITLE
Wrong input choosen to fillin with password

### ISSUE THREAD

**Issue by kris7453** [keepassxreboot/keepassxc-browser#1277] opened 2021-03-23 21:46 UTC
I can't fill in correct input with password chosen from context menu.
## Expected Behavior
Extension fill in correct input (target input) with option chosen from context menu (e.g. password only).

## Current Behavior
Extension fill in first password input found on page. I chose fill only password on "blue" field, but "red" field has been filled in instead. Both fields have "password" type and name "password".
![plemiona](https://user-images.githubusercontent.com/20442936/112221713-12632500-8c28-11eb-8b43-ac84facc605e.PNG)

## Possible Solution
Check first if event target is an input element. If it is, then fill in with chosen option (e.g. password).

## Debug info

KeePassXC - 2.6.3
KeePassXC-Browser - 1.7.6
Operating system: Windows 10
Browser: Firefox

**Comment by varjolintu** [comment] 2021-03-24 05:16
Duplicate of #1244.

**Closed by varjolintu** 2021-03-24 05:16 UTC
