### ISSUE TITLE
No http auth on current stable 2.5.3 and Firefox/Chrome

### ISSUE THREAD

**Issue by RolandSM** [keepassxreboot/keepassxc-browser#799] opened 2020-03-05 16:12 UTC
Hello,

I found this option and selected, I have one HTTP auth for a Domain and a seconde for the admin login into the cms.

Every http auth is not working for me not on firefox and not on chrome. I have enabled in the browser plugin to fill and send on http. The popup comes of the request of all entries and I can allow or deny. next time the popup is only coming again but filles not the form...

Greets

**Comment by droidmonkey** [comment] 2020-03-05 16:23
Can you clarify because your last paragraph does not make sense.

**Comment by RolandSM** [comment] 2020-03-05 16:51
Don´t know what you mean?

The complete http-auth is not working on my linux system, not for firefox and not for chrome...

**Comment by varjolintu** [comment] 2020-03-05 20:04
Cannot reproduce this.

**Comment by RolandSM** [comment] 2020-03-06 05:11
Sorry, it works now. But Http-auth asks every time on more entries? There is no checkbox to save or select one special entry?

**Comment by varjolintu** [comment] 2020-03-06 06:15
Confirmation for HTTP Auth is always asked by default. You can disable the check from _Browser Integration settings -> Advanced -> Do not ask permission for HTTP Basic Auth_.

I'm not sure what you mean with "special entry". Saving a new credentials from HTTP Basic Auth is not yet implemented, if that's what you meant.

**Comment by RolandSM** [comment] 2020-03-07 17:57
Okay, there are news about.
If there is only one matching entry in KeePassXC, also http-auth works. Sorry my fault.

But let me describe some scenario:
I have a main page like main.de
There are two entries, both with:
`allow from main.de deny from test.main.de`

Now I have a test site on a subdomain like test.main.de.
One entry for the admin-login on test.main.de/admin with:
`allow from test.main.de`
One entry for the http-auth on test.main.de with:
`allow from test.main.de` and the option that this is only http

The complete test.main.de is locked by the http-auth. If I enter, the KeePassRC popup is coming with requesting following entries:
2x main.de
1x test.main.de admin
1x test.main.de http

When I select the last one and allow, nothing happens, only the login box from browser comes up.
If I hide the test.main.de admin or remove, its working?

First of all, why test.main.de http shows also the main.de entries?
Why is the http not working, if my admin user exists in KeePassXC?

Perhaps I make something wrong?

Of course I show only best matching results, all entries should be correct filtered with allow and deny entries.

**Comment by varjolintu** [comment] 2020-03-07 18:00
If your entry's URL is `main.de` it will work as a wildcard for `*.main.de`. Also, check that the scheme's match.

**Comment by RolandSM** [comment] 2020-03-08 05:50
Hello, 
"schemes match"?
My entries are ALL with https://main.de or some few with http://
Is "https://main.de" also with wildcard subdomains?

Greets

**Comment by varjolintu** [comment] 2020-03-08 07:32
If "Match URL scheme" option is enabled and your entry has `https://main.de` as the URL, addresses with `http` scheme are ignored.

**Comment by RolandSM** [comment] 2020-03-08 10:41
Yes I know,
in KeePassXC settings I have checked "Compare URL Scheme" and also "Return only best matching login data". 
But also my topics see on top...

**Comment by varjolintu** [comment] 2020-03-10 11:51
I'm not sure if I understand what the problem here is.

**Comment by RolandSM** [comment] 2020-03-10 19:01
The Problem is that http auth is not working if another login exists for example a CMS login...

**Comment by varjolintu** [comment] 2020-03-10 19:39
One thing you can try is this new setting: _Edit Entry -> Browser Integration -> [x] Use this entry only with HTTP Basic Auth_, if you want to force some entries just for the HTTP Auth use.

To reproduce this problem, I suggest you write clear steps how you do it. What is the entry/entries URL('s) etc. Step by step instructions.

**Comment by RolandSM** [comment] 2020-03-12 08:35
Okay I try to describe more better:

I have a main page like https://main.de (Frontend from an CMS) 
I have 3 entries in KeePassXC:
1. https://main.de (Frontend Demo User Login) 
2. https://main.de/admin (Backend Admin User Login) 
3. https://main.de/admin (http Auth for complete admin sectio before Login) 
This entries have "allow from main.de" and "deny from "test.main.de"

Also I have a test Page installed on https://test.main.de
Also with 3 entries in KeePassXC like before but with this new URL. 
This entries have "allow from test.main.de". 

3. Entries have checkbox that Its only a http Auth. 
Basic Settings is only ship matching result. 

First Problem on both pages:
The http Auth popup is coming and I select the http one - allow - nothing happens only http Login comes up. 
Only if I deaktivate Entry 2 it works! But after http Auth I need also to Login into CMS. 

Second Problem on test.main.de
The Auth field Shows also the entries from main.de but These are denied??? 

Greets

**Comment by varjolintu** [comment] 2020-03-12 09:48
There might be a bug in the Allow/Deny settings. Gotta check that.

What do you mean by "select the http one"? How many credentials is the HTTP Auth popup showing?

**Comment by RolandSM** [comment] 2020-03-12 15:10
Ah okay. The http auth shows ALL 6 entries...

**Comment by varjolintu** [comment] 2020-03-12 15:25
As said before, using `https://main.de` works as a wilcard for `https://*.main.de`, so that's why it happens.

**Comment by RolandSM** [comment] 2020-03-12 15:52
Is it possible to make only a wildcard entry, if nothing before is? For example "main.de" is also "*.main.de"
But "http://main.de" is not "http://*.main.de"?

Also it would be fine, that the entry for URL "http://main.de" is only shown here, and the entry for "http://main.de/admin" is only shown here... Currently on the last one, the one before is also shown....

**Comment by varjolintu** [comment] 2020-03-12 15:54
Are those three extra credentials for `test.main.de` using the same usernames and passwords? If so, you can add the URL to Additional URL's list instead of making new entries.

**Comment by RolandSM** [comment] 2020-03-12 15:55
No, all are different...

**Comment by varjolintu** [comment] 2020-11-07 15:39
Still having the problem?

**Comment by varjolintu** [comment] 2021-04-10 15:54
Closing the issue. Will reopen if the problem still exists.

**Closed by varjolintu** 2021-04-10 15:54 UTC
Labels: bug
