### ISSUE TITLE
"No TOTP found" on auto-complete in Firefox

### ISSUE THREAD

**Issue by schiessle** [keepassxreboot/keepassxc-browser#1432] opened 2021-10-20 20:29 UTC
## Overview

KeepassXC version: 2.6.2 on Debian Bullseye
Firefox: 93
KeepassXC Plugin: 1.7.9.1

## Steps to Reproduce

1. Setup TOTP for a password entry
2. Login to the page
3. On the TOTP input field try to click the "auto-fill" button from the keypassxc plugin

## Expected Behavior

TOTP code gets added to the input field to complete the login

## Actual Behavior

Error message is shown: "Warning! No TOTP found."

If I open KeepassXC, go to the password entry, right click, TOTP and "copy TOTP" I get a valid TOTP token and can manually past it to the input field. The basic TOTP setup seems to be correct but the browser plugins fails to fetch it.

**Comment by JonFStr** [comment] 2021-11-16 21:07
I had the same problem, and after the update to 1.7.10 today it's gone

**Comment by schiessle** [comment] 2021-11-18 18:16
Yes, I can confirm that it works for me as well with 1.7.10.1... Thanks for fixing it!

**Comment by schiessle** [comment] 2021-12-22 10:21
In general it still works but I experience a strange behavior.

If I click on "fill TOTP from KeePassXC" in the input field I get the error "Warning! No TOTP found". Than I click on the KeePassX icon on the toolbar I see "Select the login information you would like to get entered into the page" and it shows the right KeePassX entry, I select it and afterwards the "fill TOTP from KeePassXC" works. But I always have to do this three steps. Any ideas?

* Firefox 95.0 (64-bit) on Fedore 35
* KeePassXC-Browser Version: 1.7.11
* KeePassXC Version: 2.6.6

**Comment by droidmonkey** [comment] 2021-12-22 10:35
Only for one particular site? TOTP filling, for me, works with one click every time. What you describe sounds like the connection to keepassxc is getting hung up. By clicking the icon in the toolbar you effectively restart the connection which pulls the credential for the site. Then you are able to fill totp because it has the credentials again.

**Comment by varjolintu** [comment] 2021-12-22 13:01
This can also happen if credentials are cleared in the background during a tab change/timeout and the fill is made after that. It means that if only the TOTP field is found, currently the credentials must be selected manually again before filling.

This of course, could be improved a bit so this is automatic.

**Comment by matthiasballreich** [comment] 2022-01-18 09:47
Same here. I'm using:

- KeePassXC 2.6.6 on Windows 11
- KeePassXC-Browser 1.7.11 Browser Extension on Microsoft Edge Chromium 97.0.1072.62

Database is connected, password will be automatically retreived, but OTP-Code not. Everytime i got the error message: "Warning! Kein OTP gefunden." 

OTP Code was configured in KeePassXC. Addiotional attribute with name otp is set to the related entry.

**Comment by varjolintu** [comment] 2022-01-18 09:52
I cannot wait for the next version where some debug logging will be added. It's gonna make solving these problems a bit easier.

**Comment by varjolintu** [comment] 2022-01-18 16:33
I managed to reproduce the issue. I'm not sure if it's the same case as yours, but the steps to reproduce this are:
- Login to a page, wait for TOTP input field
- Switch to another tab and fill credentials
- Go back to the previous tab with TOTP -> No TOTP found when filling

I could make a quick fix for this that tries to fill the first TOTP found if there's one in the credentials for the current page, even if the `loginId` used to track the login does not match. Another option would be that I'll try to move the `loginId` to the tab's properties so it can be set per tab. Gotta do some testing.

**Comment by varjolintu** [comment] 2022-01-18 17:25
Please check if these changes fixes the issue: https://github.com/keepassxreboot/keepassxc-browser/pull/1530

**Closed** 2022-01-21 09:36 UTC

**Comment by theking2** [comment] 2026-02-28 18:03
still a problem on 1.9.11 (2025-11-26)
