### ISSUE TITLE
prevent creation of duplicated database entries after initial Save credentials and banner header appearance 

### ISSUE THREAD

**Issue by tuxcrafter** [keepassxreboot/keepassxc-browser#1225] opened 2021-02-18 17:39 UTC
KeePassXC-Browser 1.7.6
KeePassXC 2.6.4

steps: fill in credentials on webpage -> right mouse -> KeePassXC-Browser -> Save credentials -> 

Then the banner header appears to Username or password changed! Save it? -> New

1. Please change this banner header when it is a new database entry, because the username or password did not change!

Now we login and the banner header appears again with the same message, there is no Update option, only New -> Press New and a second copy of the database entry will be created.

This behavior is sadly to complicated for our average users and I would love to see this being improved.

2 Please change this, after the "Save credentials" reload the webpage so the new credentials are available or use some other mechanism to not show the "Username or password changed! header again after a successful login.

3. When connecting the KeePassXC-Browser to KeePassXC  please reload the webpage as well, so the credentials become available for the current webpage.

4. When disabling the "Show a banner on the page when new credentials can be saved to the database" the right mouse -> Save credentials options does not work anymore. Can we directly add the credentials without the banner header showing?

I will donate a 150 euro bounty when these above issues are fixed in the next KeePassXC-Browser release for Firefox and Chrome.

![2021-02-18-181308_1028x686_scrot](https://user-images.githubusercontent.com/9133399/108397594-68534000-7218-11eb-8d76-57317afc02d7.png)
![2021-02-18-181353_1477x69_scrot](https://user-images.githubusercontent.com/9133399/108397596-68ebd680-7218-11eb-9a86-dc923cb5e9cd.png)

Jelle de Jong

**Comment by varjolintu** [comment] 2021-02-18 19:29
I would need more info about this. The current behavior for me is:
- If there's no previous credentials for the page and I choose Save Credentials, the banner is shown only with the New button.
- If there are previous credentials for page page, I get both New and Update.
- If I try to save credentials that have no update for username or password, I will get a warning notification that identical credentials already exist.

So, does the page already match some credentials for you before you try saving?

**Comment by tuxcrafter** [comment] 2021-02-18 19:55
There are no matching credentials before do the Save credentials, if there are I get the Warning! Identical credentials already exist. 

The steps to reproduce are to fill in the credentials in de dialogs on the webpage -> then press Save credentials you get a banner header "Username or password changed! Save it?" with only the option new. Then you login and you get the same banner header again with also only the option New, if you press New you now have to of the same entries in the database!

Username or password changed! Save it? is also not the right description for a new entry, it suggest that something that exist is changed, but there are no excising entries.

**Comment by varjolintu** [comment] 2021-02-18 19:58
Ok, now I understood what you meant. Here the problem is that people don't expect the page to reload after saving credentials, so we just need to update those after the save was made.

**Comment by varjolintu** [comment] 2021-02-18 20:22
Fixed it. The updated credentials will also appear to the Autocomplete Menu and the popup login menu immediately after the save.

**Comment by tuxcrafter** [comment] 2021-02-18 20:25
That is point 2 fixed thank you.

**Comment by varjolintu** [comment] 2021-02-18 20:33
I can check if the point 3 also works now. It shouldn't be hard to add if not. With point 4 the credentials would be directly added to the KeePassXC-Browser Passwords group.

**Comment by tuxcrafter** [comment] 2021-02-19 11:07
With point 4 it would be great to use the same notification system was with the "Warning! Identical credentials already exist." message. Only with "Save credentials" as a new entry then -> "Success! Credentials saved." and when the password changed -> "Success! Credentials updated." So we got three states -> new -> updated -> identical and maybe error if something went wrong. This way we the Save credentials is fully usable without needing the banner header feature.

**Comment by varjolintu** [comment] 2021-02-19 13:35
@tuxcrafter My idea is to get point 4 working exactly like that.

**Comment by varjolintu** [comment] 2021-02-19 16:19
@tuxcrafter All points are now made. Still, I discovered that Point 3 will not work with Firefox because of the following bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1665380. For some reason resolving Promises inside the popup can cause this, and I'm still trying to find a workaround for it. With Chromium-based browsers that feature works just fine now.

**Comment by tuxcrafter** [comment] 2021-02-19 17:12
Thank you that is great work! Did you change the banner headers as well of point 1, when can I expect to install and test the updated KeePassXC-Browser plugins?

**Comment by varjolintu** [comment] 2021-02-19 17:37
@tuxcrafter The headers should change because the credentials are reloaded so they won't appear as "new". You can already test the PR branch manually if you wish to.
https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually

**Closed** 2021-02-22 19:42 UTC
Labels: bug

**Comment by tuxcrafter** [comment] 2021-02-22 20:23
Where do you want me to sent the bounty to when the new browser add-ons are released?

**Comment by varjolintu** [comment] 2021-02-22 20:31
I'll send you some mail after the release.
