### ISSUE TITLE
"Search all databases" – ignore locked databases…

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#206] opened 2018-06-15 17:50 UTC
This is a follow-up of https://github.com/keepassxreboot/keepassxc-browser/issues/83, because my use case described there is still not satisfied. :wink: 

When I select the checkbox to search in all databases and select a tab with a closed database.

What I imagine:
1. It should not matter, what database I have selected in KeePassXC.

How?
* Just search all opened DBs first.
* Only if nothing could be found, show an error.

Or:
* Somehow remember the databases used/connected to the browser? see https://github.com/keepassxreboot/keepassxc-browser/issues/205

**Comment by varjolintu** [comment] 2018-06-15 20:23
Hmm. This needs to be tested if it's even possible. You'd need to return database closed message at the same time, but still return some results.

**Comment by varjolintu** [comment] 2023-03-02 05:59
Related: https://github.com/keepassxreboot/keepassxc-browser/issues/1275

**Comment by varjolintu** [comment] 2023-07-23 06:11
https://github.com/keepassxreboot/keepassxc-browser/issues/1888 Will solve this.

**Comment by droidmonkey** [comment] 2024-08-18 18:25
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/5238

**Closed by droidmonkey** 2024-08-18 18:25 UTC
Labels: feature request
