### ISSUE TITLE
The error message "KeePassXC-Browser a rencontré une erreur :  Impossible de déchiffrer le message" appears randomly 

### ISSUE THREAD

**Issue by CLeBeRFR** [keepassxreboot/keepassxc-browser#631] opened 2019-10-10 18:29 UTC
## Expected Behavior

By clicking on KeePassXC-Browser add-on icon, I should be able to select my credential for the current website. 

## Current Behavior

When I want to fill a form with my credentials, on KeePassXC-Browser icon, the message "KeePassXC-Browser a rencontré une erreur :  Impossible de déchiffrer le message" appears.
This is the translation of the error : "KeePassXC-Browser encountered an error: Unable to decrypt the message"

## Possible Solution

I am obligated to close and reopen several times Firefox to solve the problem.

## Steps to Reproduce (for bugs)

I don't know why the bug appears so I don't have specifics steps to reproduce the bug.

## Debug info

KeePassXC - 2.4.3
KeePassXC-Browser - 1.5.1
Operating system: Linux x86_64
Browser: Mozilla Firefox 69.0

**Comment by varjolintu** [comment] 2019-10-10 20:07
Duplicate of #615.

**Closed by varjolintu** 2019-10-10 20:07 UTC
Labels: duplicate
