### ISSUE TITLE
Input fields not detected on DAB Bank B2B Portal (e.g. Smartbroker)

### ISSUE THREAD

**Issue by bllngr** [keepassxreboot/keepassxc-browser#1041] opened 2020-10-12 07:59 UTC
## Expected Behavior
Username and password fields are detected automatically, showing the expected KPXC icon. Alternatively, manually choosing custom login fields works.

## Current Behavior
Input fields are not detected automatically. Trying to manually choose custom login fields doesn't work either, since the input fields cannot be selected.

## Steps to Reproduce (for bugs)
0. Add and configure an KPXC entry for https://b2b.dab-bank.de
1. Visit  https://b2b.dab-bank.de/smartbroker/ or https://b2b.dab-bank.de/Systeme-Tools/Login/
1. Notice the credentials not being entered automatically.
1. Notice the absence of the KPXC icon in the username field
2. Select "Choose custom login fields" from the browser extension button
3. Try to select the username or password field

## Debug info

KeePassXC-Browser Version: 1.7.1
KeePassXC Version: 2.6.0 
Operating system: Win/Linux
Browser: Firefox 81

**Comment by varjolintu** [comment] 2020-10-12 14:42
This happens because both pages has forms which `height` calculated using `getBoundingClientRect()` returns zero. That means the extension thinks the form is not visible at all, and ignores it.

**Comment by l33** [comment] 2021-05-31 10:25
Duplicate of #1116 or the other way around?

**Comment by varjolintu** [comment] 2021-06-22 16:13
Duplicate.

**Closed by varjolintu** 2021-06-22 16:13 UTC
Labels: bug
