### ISSUE TITLE
Logins not sent from connected DB unless it is the active tab in KeePassXC 

### ISSUE THREAD

**Issue by fusionneur** [keepassxreboot/keepassxc-browser#1969] opened 2023-08-23 18:26 UTC
## Expected Behavior

trying to autocomplete a password on a website (eg. on https://app.standardnotes.com/)

## Current Behavior

unable to fill password from keepassXC entry in website

## Steps to Reproduce (for bugs)

1. have multiple keepass databases opened and unlocked (eg. db1 db2 db3)
2. only one of the keepass databases has the password for the domain trying to autocomplete (eg. db1)
3. the keepass db holding the password is out of focus and also not linked with the browser (eg. db3 is selected in the keepassXC gui, rather than db1)
4. try to login on a domain by clicking the keepass icon in the form
5. a banner shows an error message: "Error!No logins found. https://app.standardnotes.com"
6. try to click addon icon in browser => it is suggested to connect to keepass db
7. switch focus to db1 OR connect(link) db3 with browser by clicking keepass addon icon
8. press keepass addon icon in browser => autocomplete entry is shown properly this time

## Debug info

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.7
Operating system: Win11
Browser: Brave v1.57.49

**Comment by droidmonkey** [comment] 2023-08-23 22:28
@varjolintu we really need to fix this UX

**Comment by varjolintu** [comment] 2023-08-24 04:42
This is a duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/1275. The Protocol V2 will fix this. There's no easy solution to do a "quick fix".

**Closed** 2023-09-16 16:26 UTC
Labels: duplicate
