### ISSUE TITLE
Firefox browser integration problem/Key exchange was not successful

### ISSUE THREAD

**Issue by GCseke** [keepassxreboot/keepassxc-browser#1754] opened 2022-10-26 18:01 UTC
After updating from Win 10 to Win 11 Pro I am no longer able to use KeepassXC on Firefox.

I have tried to follow this guide https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide but without success. 

Even tried to install older versions of KeepassXC and Firefox but the result was the same.

My main browser is Firefox that's why I'm desperate to solve this issue.

## Current Behavior

The error is: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.

It works perfectly on Edge browser and Chrome as well.

## Debug info

KeePassXC - 2.7.3
KeePassXC-Browser - 1.8.3
Operating system: Windows 11 Pro
Browser: Mozilla Firefox 106.0.1

**Comment by varjolintu** [comment] 2022-10-26 18:35
Duplicate of #1751

**Closed by varjolintu** 2022-10-26 18:35 UTC
