### ISSUE TITLE
ERROR: No Login found - Plugin does not recognize any form

### ISSUE THREAD

**Issue by masi** [keepassxreboot/keepassxc-browser#986] opened 2020-09-02 07:59 UTC
When I am on a page that has credentials in the DB I expect that the plugin finds them.

Since yesterday I always get the report "ERROR: No login found" (actually I get "Keine Anmledung gefunden," since I use a german system). It happens on all pages.
The plugin reports that it is connected to KeePassXC and configured correctly.

KeePassXC - 2.6.1
KeePassXC-Browser - 1.5.4
Operating system: Linux, Fedora (Wayland)
Browser: Firefox 80.0

**Comment by varjolintu** [comment] 2020-09-02 08:13
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/5299.

**Closed by varjolintu** 2020-09-02 08:13 UTC
