### ISSUE TITLE
Flatpak KeePassXC cannot be connected to from Vivaldi (native)

### ISSUE THREAD

**Issue by totalolage** [keepassxreboot/keepassxc-browser#1611] opened 2022-04-18 18:54 UTC
## Expected Behavior
Database should connect and unlock from the extension

## Current Behavior
Spams in console:
```
Connecting to native messaging host org.keepassxc.keepassxc_browser
Failed to connect: Native host has exited.
```

Does not connect, gives "Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings." in the extension window.
On reconnect "Key exchange was not successful." (in the console: `Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.` and `Error 9: Key exchange was not successful.`)
On database connect in the console: `Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.`

## Steps taken to attempt fix
I tried restarting everything.
I verified that KeePassXC was writing the `org.keepassxc.keepassxc_browser.json` file in `~/.config/vivaldi/NativeMessagingHosts/` (by deleting it and re-enabling browser support which wrote it again).
I tried running `flatpak run --command=keepassxc-proxy org.keepassxc.KeePassXC` in console while I try to connect db.
Tried giving flatpak applications all the permissions that could possibly be relevant (session dbus, system bus, shared memory... everything I could think of)

## Steps to Reproduce (for bugs)

1. Install KeePassXC from flathub (`flatpak install org.keepassxc.KeePassXC`)
2. Install vivaldi-stable from pacman (`pacman -S vivaldi`)
3. Install KeePassXC-Browser extension 
4. Open passwords DB and enable browser support
5. Open vivaldi and click "Reload" in extension window

## Debug info

KeePassXC - 2.7.1
KeePassXC-Browser - 1.7.12
Operating system: Arch Linux 5.15.34-1-lts
Browser: Vivaldi 5.2.2623.39 (Stable channel) stable (64-bit)

**Comment by droidmonkey** [comment] 2022-04-18 19:03
Can you test if the appimage works?

**Comment by varjolintu** [comment] 2022-04-18 19:14
Where's the `path` inside the JSON script pointing to?

**Comment by totalolage** [comment] 2022-04-21 06:15
> Where's the `path` inside the JSON script pointing to?
```
❯ cat .config/vivaldi/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json
{
    "allowed_origins": [
        "chrome-extension://pdffhmdngciaglkoonimfcmckehcpafo/",
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/var/lib/flatpak/exports/bin/org.keepassxc.KeePassXC",
    "type": "stdio"
}
❯ stat /var/lib/flatpak/exports/bin/org.keepassxc.KeePassXC
  File: /var/lib/flatpak/exports/bin/org.keepassxc.KeePassXC -> ../../app/org.keepassxc.KeePassXC/current/active/export/bin/org.keepassxc.KeePassXC
  Size: 83        	Blocks: 8          IO Block: 4096   symbolic link
Device: 0,26	Inode: 16757804    Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-04-21 08:12:08.525403849 +0200
Modify: 2022-04-21 08:12:08.505403115 +0200
Change: 2022-04-21 08:12:08.505403115 +0200
 Birth: 2022-04-21 08:12:08.505403115 +0200
```

**Comment by varjolintu** [comment] 2022-04-21 06:18
@totalolage Where did you install the extension? Does its ID match with `oboonakemofpalcgghocfoadofidjkkk`?

**Comment by totalolage** [comment] 2022-04-21 06:19
> Can you test if the appimage works?

Yes, both AppImage and native package work as expected.

**Comment by totalolage** [comment] 2022-04-21 06:20
> @totalolage Where did you install the extension? Does its ID match with `oboonakemofpalcgghocfoadofidjkkk`?

Yes, in "Developer mode" I can see the extensions has the ID oboonakemofpalcgghocfoadofidjkkk

**Comment by RolfTMeles** [comment] 2022-04-22 11:41
Same for me.
I added the addon using the google chrome addon page. It installed, but

> KeePassXC-Browser has encountered an error:
> Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.

And when clicking the "connect" button to connect to my database, nothing happens at all.

### Debug Info

KeePassXC - unknown
KeePassXC-Browser - 1.7.12
Operating system: Linux x86_64
Browser: Chrome/Chromium 100.0.4896.133

**Comment by totalolage** [comment] 2022-04-22 16:43
> For me it works.
> 
> I use the flatpak version on my computer. In the flatpack app I activated browser integration, chose vivaldi and everything worked fine.
> 
> ### Debug Info
> KeePassXC - 2.7.1 KeePassXC-Browser - 1.7.12 Operating system: Linux x86_64 Browser: Chrome/Chromium 100.0.4896.133

Yes, it works fine on Chrome. This seems to be a Vivaldi specific bug.

**Comment by RolfTMeles** [comment] 2022-04-22 16:54
I use vivaldi. It just shows chrome in the Debug Info, no Idea why. I use 
"Vivaldi | 5.2.2623.39 (Stable channel) stable (64-bit)"

**Comment by varjolintu** [comment] 2022-04-22 16:56
Can you compare the Chromium and Vivaldi output with https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#find-the-native-messaging-configuration-path-with-strace ?

**Comment by totalolage** [comment] 2022-04-22 17:52
> Can you compare the Chromium and Vivaldi output with https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#find-the-native-messaging-configuration-path-with-strace ?

The vivaldi strace was getting spammed, I noticed it's spawning a `bwrap --args 39 xdg-dbus-proxy --args=41` process every few seconds which then instantly crashes. I clicked reconnect db, but I can't tell if the output changed at all: https://pastebin.com/mKtU5RPt

Chrome: https://pastebin.com/1mns4Bax

**Comment by varjolintu** [comment] 2022-04-22 18:16
Vivaldi:
```
[pid 758839] execve("/home/user/.nvm/versions/node/v14.18.1/bin/bwrap", ["bwrap", "--args", "39", "keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x557d33d36250 /* 0 vars */) = -1 ENOENT (No such file or directory)
[pid 758839] execve("/home/user/.local/bin/bwrap", ["bwrap", "--args", "39", "keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x557d33d36250 /* 0 vars */) = -1 ENOENT (No such file or directory)
[pid 758839] execve("/usr/local/sbin/bwrap", ["bwrap", "--args", "39", "keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x557d33d36250 /* 0 vars */) = -1 ENOENT (No such file or directory)
[pid 758839] execve("/usr/local/bin/bwrap", ["bwrap", "--args", "39", "keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x557d33d36250 /* 0 vars */) = -1 ENOENT (No such file or directory)
[pid 758839] execve("/usr/bin/bwrap", ["bwrap", "--args", "39", "keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x557d33d36250 /* 0 vars */ <unfinished ...>
```

Chrome:
```
[pid 966741] execve("/home/totalolage/.nvm/versions/node/v14.18.1/bin/bwrap", ["bwrap", "--args", "39", "keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x565194683cd0 /* 0 vars */ <unfinished ...>
[pid 966741] execve("/home/totalolage/.local/bin/bwrap", ["bwrap", "--args", "39", "keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x565194683cd0 /* 0 vars */ <unfinished ...>
[pid 966741] execve("/usr/local/sbin/bwrap", ["bwrap", "--args", "39", "keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x565194683cd0 /* 0 vars */ <unfinished ...>
[pid 966741] execve("/usr/local/bin/bwrap", ["bwrap", "--args", "39", "keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x565194683cd0 /* 0 vars */ <unfinished ...>
[pid 966741] execve("/usr/bin/bwrap", ["bwrap", "--args", "39", "keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x565194683cd0 /* 0 vars */ <unfinished ...>
```

Later Chrome succeeds (Vivaldi doesn't even call this):
```
[pid 966871] execve("/app/bin/keepassxc-wrapper", ["keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x5651be7c3ac0 /* 73 vars */ <unfinished ...>
[pid 966871] execve("/app/bin/bash", ["bash", "/app/bin/keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x7fffcc69e590 /* 73 vars */ <unfinished ...>
[pid 966871] execve("/usr/bin/bash", ["bash", "/app/bin/keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x7fffcc69e590 /* 73 vars */ <unfinished ...>
[pid 966871] openat(AT_FDCWD, "/app/bin/keepassxc-wrapper", O_RDONLY) = 3
```

@totalolage So you were running this with the same user? I noticed Chrome used `/home/totalolage/` but Vivaldi has `/home/user/`.

**Comment by totalolage** [comment] 2022-04-22 20:15
> Relevant lines below.
> 
> Vivaldi:
> 
> ```
> [pid 758839] execve("/home/user/.nvm/versions/node/v14.18.1/bin/bwrap", ["bwrap", "--args", "39", "keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x557d33d36250 /* 0 vars */) = -1 ENOENT (No such file or directory)
> [pid 758839] execve("/home/user/.local/bin/bwrap", ["bwrap", "--args", "39", "keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x557d33d36250 /* 0 vars */) = -1 ENOENT (No such file or directory)
> [pid 758839] execve("/usr/local/sbin/bwrap", ["bwrap", "--args", "39", "keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x557d33d36250 /* 0 vars */) = -1 ENOENT (No such file or directory)
> [pid 758839] execve("/usr/local/bin/bwrap", ["bwrap", "--args", "39", "keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x557d33d36250 /* 0 vars */) = -1 ENOENT (No such file or directory)
> [pid 758839] execve("/usr/bin/bwrap", ["bwrap", "--args", "39", "keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x557d33d36250 /* 0 vars */ <unfinished ...>
> ```
> 
> Chrome:
> 
> ```
> [pid 966741] execve("/home/totalolage/.nvm/versions/node/v14.18.1/bin/bwrap", ["bwrap", "--args", "39", "keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x565194683cd0 /* 0 vars */ <unfinished ...>
> [pid 966741] execve("/home/totalolage/.local/bin/bwrap", ["bwrap", "--args", "39", "keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x565194683cd0 /* 0 vars */ <unfinished ...>
> [pid 966741] execve("/usr/local/sbin/bwrap", ["bwrap", "--args", "39", "keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x565194683cd0 /* 0 vars */ <unfinished ...>
> [pid 966741] execve("/usr/local/bin/bwrap", ["bwrap", "--args", "39", "keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x565194683cd0 /* 0 vars */ <unfinished ...>
> [pid 966741] execve("/usr/bin/bwrap", ["bwrap", "--args", "39", "keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x565194683cd0 /* 0 vars */ <unfinished ...>
> ```
> 
> Later Chrome succeeds (Vivaldi doesn't even call this):
> 
> ```
> [pid 966871] execve("/app/bin/keepassxc-wrapper", ["keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x5651be7c3ac0 /* 73 vars */ <unfinished ...>
> [pid 966871] execve("/app/bin/bash", ["bash", "/app/bin/keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x7fffcc69e590 /* 73 vars */ <unfinished ...>
> [pid 966871] execve("/usr/bin/bash", ["bash", "/app/bin/keepassxc-wrapper", "chrome-extension://oboonakemofpa"...], 0x7fffcc69e590 /* 73 vars */ <unfinished ...>
> [pid 966871] openat(AT_FDCWD, "/app/bin/keepassxc-wrapper", O_RDONLY) = 3
> ```
> 
> @totalolage So you were running this with the same user? I noticed Chrome used `/home/totalolage/` but Vivaldi has `/home/user/`.

yeah it is I sed-ed one of the logs and forgot about it before pasting, both are under the same user.

**Comment by varjolintu** [comment] 2022-04-23 05:09
Sadly I couldn't reproduce the problem with at least with Linux Mint. Installed the deb from Vivaldi's site, installed KeePassXC's official Flatpak package, enabled Vivaldi support in KeePassXC.. Everything just worked.

**Comment by droidmonkey** [comment] 2022-04-23 10:54
Closing this as it is most likely a problem with the individuals computer / configuration. Make sure you don't have vivaldi running inside firejail or similar.

**Closed by droidmonkey** 2022-04-23 10:54 UTC
