### ISSUE TITLE
Extension disables mouseUp event on some pages

### ISSUE THREAD

**Issue by artfb** [keepassxreboot/keepassxc-browser#1459] opened 2021-11-19 09:40 UTC
## Expected Behavior
Be able to resize element

## Current Behavior

When trying to resize element, pointer is locked on `mouseDown`, and not releasing with `mouseUp`

## Possible Solution

Found out that attaching listeners to pointer events in that specific library
https://github.com/bokuweb/re-resizable
`mouseUp` -> `pointerUp` fixes the issue

## Steps to Reproduce (for bugs)

1. Go to: http://bokuweb.github.io/re-resizable/?path=/story/aspect--default
2. Try to resize element
3. Cursor gets locked
4. ¯\_(ツ)_/¯

## Debug info

KeePassXC - 2.6.4 (?)
KeePassXC-Browser - 1.7.10
Operating system: Mac
Browser: Chrome

**Comment by varjolintu** [comment] 2021-11-19 09:47
Duplicate of #1452. The issue has been already solved but Google removed our extension from the store (and it still is not back), so the latest version is not updated to Chrome users.

**Closed by varjolintu** 2021-11-19 09:47 UTC
Labels: duplicate

**Comment by artfb** [comment] 2021-11-19 09:52
Oh, sorry. I looked at open issues. Cool!
