### ISSUE TITLE
Within Brave on MacOS, I can't have KeePassXC Extension connect to KeePassXC

### ISSUE THREAD

**Issue by pingouiny** [keepassxreboot/keepassxc-browser#541] opened 2019-05-12 08:54 UTC
## Expected Behavior
Would like to connect the KeePassXC Browser extension from within Brave, to the KeePassXC DB

## Current Behavior
When pressing on the "Connect" button, nothing happen.  Chromium & Brave browser integration are enabled in KeePassXC.

## Steps to Reproduce (for bugs)
1. Keepass Icon > Settings > Connected Database > press the "Connect"button

## Debug info

KeePassXC - Version 2.4.1  Revision: 7bafe65
KeePassXC-Browser - Version 1.4.3
Operating system - macOS Mojave (10.14)
Browser - Brave Version 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)

**Comment by droidmonkey** [comment] 2019-05-12 13:23
Confirmed it does not work. Brave + macOS

**Comment by varjolintu** [comment] 2019-05-12 14:15
I've never succeed to get Brave working with macOS, even if the original PR that added support for it was approved and merged.

**Comment by droidmonkey** [comment] 2019-05-12 14:22
I wonder if they have sandboxed Brave and did not open the native messaging capability

**Comment by derzahla** [comment] 2019-06-29 17:02
Same here.  I use the latest Brave Dev but also tried Brave stable.  Here's some debug info I captured:

> Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:969 Failed to connect: Specified native messaging host not found.
keepass.js:1192 Objectmessage: (...)get message: ƒ ()arguments: (...)caller: (...)length: 0name: ""__proto__: ƒ ()apply: ƒ apply()arguments: (...)bind: ƒ bind()call: ƒ call()caller: (...)constructor: ƒ Function()length: 0name: ""toString: ƒ toString()Symbol(Symbol.hasInstance): ƒ [Symbol.hasInstance]()get arguments: ƒ ()set arguments: ƒ ()get caller: ƒ ()set caller: ƒ ()__proto__: Object[[FunctionLocation]]: <unknown>[[Scopes]]: Scopes[0]No properties[[Scopes]]: Scopes[0]No properties__proto__: Object
browser-polyfill.min.js:1 Returning a Promise is the preferred way to send a reply from an onMessage/onMessageExternal listener, as the sendResponse will be removed from the specs (See https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage) Error
    at B (chrome-extension://oboonakemofpalcgghocfoadofidjkkk/browser-polyfill.min.js:1:8152)
    at chrome-extension://oboonakemofpalcgghocfoadofidjkkk/background/event.js:108:9
B @ browser-polyfill.min.js:1
keepass.js:1078 Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.
keepass.js:993 Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:969 Failed to connect: Specified native messaging host not found.
keepass.js:1192 {}message: (...)get message: ƒ ()arguments: (...)caller: (...)length: 0name: ""__proto__: ƒ ()apply: ƒ apply()arguments: (...)bind: ƒ bind()call: ƒ call()caller: (...)constructor: ƒ Function()length: 0name: ""toString: ƒ toString()Symbol(Symbol.hasInstance): ƒ [Symbol.hasInstance]()get arguments: ƒ ()set arguments: ƒ ()get caller: ƒ ()set caller: ƒ ()__proto__: Object[[FunctionLocation]]: <unknown>[[Scopes]]: Scopes[0][[Scopes]]: Scopes[0]No properties__proto__: constructor: ƒ ()__proto__: Object
keepass.js:1078 Error 9: Key exchange was not successful.

**Comment by varjolintu** [comment] 2019-06-30 05:26
That debug doesn't provide any new info. The native messaging host (meaning the proxy) cannot be found by the browser.

**Comment by JPfeifer** [comment] 2019-08-08 07:30
Removing 
~/Library/Application\ Support/BraveSoftware/Brave-Browser/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json
solved the issue for me.

KeePassXC - Version 2.4.3 Revision: 5d6ef0c
KeePassXC-Browser - Version  1.4.7
Operating system - macOS Mojave (10.14)
Browser - Brave Version 0.67.124 Chromium: 76.0.3809.100  (Official Build) (64-bit)

**Comment by Carlossuss** [comment] 2019-08-23 17:15
I have a similar problem with Brave 0.68.131 on Ubuntu Mate 18.04, just installed KeePassXC 2.3.1, which seems to be the latest version using apt install. When clicking the icon in the browser I receive the message "Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.", than after clicking reload I get "Key exchange was not successful.". I followed instructions in the documents on the KeePassXC website.

**Comment by varjolintu** [comment] 2019-08-24 05:02
@Carlossuss Use the official PPA to install the latest version.

**Comment by Carlossuss** [comment] 2019-08-24 17:23
> @Carlossuss Use the official PPA to install the latest version.

Thank you, that worked.

**Comment by HarukaMa** [comment] 2019-10-12 18:38
(Copy-paste from https://github.com/brave/brave-browser/issues/5074#issuecomment-541350928)

According to https://github.com/browserpass/browserpass-native/issues/43#issuecomment-481794094, this is caused by Brave browser still looking for native messaging hosts definitions from `~/Library/Application Support/Google/Chrome/NativeMessagingHosts`, not `~/Library/Application Support/BraveSoftware/Brave-Browser{,-Dev,...}/NativeMessagingHosts`. 

I think this is a completely unexpected behavior and a bug of Brave browser.

**Comment by Birkenstab** [comment] 2019-10-12 20:11
Yeah, I noticed that too. I had to enable Chrome integration in KepassXC instead of Brave integration

**Comment by varjolintu** [comment] 2019-10-13 06:43
If this is really a Brave bug, then this issue is closed.

**Closed by varjolintu** 2019-10-13 06:43 UTC
Labels: bug, platform: macOS

**Comment by droidmonkey** [comment] 2019-10-13 11:27
Nice fix to just choose chrome though!

**Comment by lugipfupf** [comment] 2020-09-25 07:58
I know, this is old & closed. But almost a year later, I ran into the same problem. The simple solution provided by @Birkenstab did the job. Thank you.

**Comment by yarongon** [comment] 2021-09-22 09:21
Again, another year passed and I have the same problem. How do I enable Chrome integration? I went over all the configurations and did not see such an option.

**Comment by varjolintu** [comment] 2021-09-22 13:21
@yarongon Hmm? You are writing about Chrome issue to Brave thread? Could you elaborate your problem a little bit more? KeePassXC settings -> Browser Integration has all the browser options available.

**Comment by yarongon** [comment] 2021-09-23 07:49
@varjolintu sorry, I did not realize I had to enable it from the KeePassXC app. Its working now. Thanks!
