### ISSUE TITLE
Propose TOTP autofill

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [keepassxreboot/keepassxc-browser#1482] opened 2021-12-02 12:30 UTC
## Expected Behavior

TOTP filled, at least for entries that I have chosen and asked to fill TOTP on next step.

## Current Behavior

Need to click TOTP icon manually.

## Possible Solution

Create an option switch, to allow enabling autofill of TOTP codes into TOTP field for ~previous~ selected entry or if fill single entry automatically enabled, also fill TOTP along other fields.

## Debug info

KeePassXC - Version 1.7.10.1
KeePassXC-Browser - Firefox 
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by varjolintu** [comment] 2021-12-02 12:32
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/728.

**Closed by varjolintu** 2021-12-02 12:32 UTC
Labels: duplicate

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment] 2021-12-02 12:35
Sorry, prior to open this I searched for "TOTP" issues and did not found it existing already...
