### ISSUE TITLE
Network connections to sites I browse from keepassxc-proxy

### ISSUE THREAD

**Issue by j1warren** [keepassxreboot/keepassxc-browser#651] opened 2019-10-26 07:37 UTC
Network connections to sites I browse from keepassxc-proxy

## Expected Behavior
There should be no internet connections from keepassxc-proxy.

## Current Behavior
> tcp        0      0 192.168.1.2:55004    116.X.93.22:443       ESTABLISHED 
10258/keepassxc-pro 
> tcp        1      0 192.168.1.2:42504    185.X.61.111:443       CLOSE_WAIT  
10258/keepassxc-pro 
> tcp        0      0 192.168.1.2:57524    172.X.160.68:443      ESTABLISHED 
10258/keepassxc-pro 
> tcp        0      0 192.168.1.2:43912    195.X.76.124:443      ESTABLISHED 
10258/keepassxc-pro 
> tcp        1      0 192.168.1.2:42498    185.X.61.111:443       CLOSE_WAIT  
10258/keepassxc-pro 
> tcp        0      0 192.168.1.2:35328    104.X.53.166:443       ESTABLISHED 
10258/keepassxc-pro 
> tcp        0      0 192.168.1.2:57340    178.X.235.57:443      ESTABLISHED 
10258/keepassxc-pro 

## Steps to Reproduce (for bugs)
1. Run keepassxc
2. see netstat -anp

## Debug info
 KeePassXC-Browser Version: 1.5.3
KeePassXC Version: 2.4.3 
Operating system: Linux
Browser: Firefox 68.2

**Comment by varjolintu** [comment] 2019-10-26 07:58
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/100.

**Closed by varjolintu** 2019-10-26 07:58 UTC
Labels: duplicate
